INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "79 anos", null, null, null, 1198, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "94-95 anos", null, null, null, 1198, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "+100 anos", null, null, null, 1198, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "28", null, null, null, 1228, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, null, 1228, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "36", "51.5 Kg", "163 cm", null, 1240, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "39", "51.5 Kg", "163 cm", null, 1240, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "51-52 anos", "48.9 kg", "163.1 cm", "Kage", 1241, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "53-58 anos", "48.9 kg", "163.1 cm", "Kage", 1241, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "63-64 anos", null, "163.1 cm", null, 1241, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "25", null, null, null, 1248, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, null, 1248, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "8-9", null, "127.5", "Estudante da Academia", 1251, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "11-12", null, "142.9", "Genin", 1251, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27-28", null, null, "Jonin", 1251, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "46", null, null, null, 1262, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "49", null, null, null, 1262, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "22-23", "50.5 kg", "169.2 cm", "Anbu", 1273, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "25-26", "50.5 kg", "169.2 cm", "Anbu", 1273, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Kage", 1282, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Kage", 1282, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32", null, null, null, 1285, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, null, 1285, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "26-27 anos", null, null, null, 1291, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "42-43 anos", null, null, null, 1291, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27", "50.1 Kg", "170.1 cm", null, 1293, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, null, 1293, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "107 cm", null, 1299, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "148 cm", null, 1299, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Chunin", 1305, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Chunin", 1305, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "26", "72 kg", "183 cm", null, 1324, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "26", "72 kg", "183 cm", null, 1324, 2);