INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 1198, 437);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 1198, 638);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto ", 1198, 624);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 1200, 1193);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1200, 936);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1201, 215);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 1201, 672);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 1201, 1235);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Ancestral", 1212, 344);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1219, 1009);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai Adotivo", 1219, 996);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão Adotivo", 1219, 1024);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Parente Distante", 1234, 1008);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1235, 1201);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 1235, 215);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 1235, 672);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1236, 849);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 1240, 346);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1240, 549);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Bisavô", 1241, 93);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 1241, 356);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio-avô", 1241, 1189);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio-avô", 1241, 442);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio-avô", 1241, 538);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 1241, 738);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais novo", 1241, 808);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Namorado", 1241, 164);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1242, 1112);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1242, 421);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 1242, 497);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha", 1257, 1288);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 1261, 775);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 1261, 1288);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 1262, 1141);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe Adotiva", 1263, 824);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão Adotivo", 1263, 482);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho Adotivo ", 1263, 1016);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Namorado", 1273, 360);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 1276, 788);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1279, 850);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 1280, 677);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto ", 1282, 493);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1288, 775);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 1288, 1261);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 1288, 1257);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 1293, 528);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha", 1293, 1116);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 1293, 514);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 1293, 245);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho-Neto", 1293, 1005);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Cunhado", 1293, 890);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 1302, 1064);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1302, 1100);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1305, 1007);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 1305, 1006);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 1305, 1005);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Nora", 1305, 1116);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 1315, 1125);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criadora", 1334, 494);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Encarnação com Kaguya Ōtsutsuki", 1336, 177);