INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador e modelo genético", 598, 1198);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Fonte genética", 598, 1332);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 609, 539);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 609, 56);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Bisavô", 614, 963);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 614, 387);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 614, 83);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 614, 60);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Prima", 614, 732);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tia", 614, 634);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai/Mãe", 614, 851);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 623, 926);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 623, 187);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 624, 1198);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tataravô", 624, 437);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 629, 630);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 630, 629);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 633, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 634, 1022);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 634, 732);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Namorado", 634, 60);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogra", 634, 83);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogro", 634, 387);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais novo", 635, 464);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 635, 1075);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 635, 437);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 636, 20);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "PaiŌnoki ", 638, 579);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tataravô", 638, 437);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio ", 638, 598);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 642, 802);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 642, 728);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 642, 86);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 642, 375);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Nora", 642, 380);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 655, 118);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 655, 722);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 659, 838);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 659, 740);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 666, 159);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 667, 1087);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 667, 455);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 672, 1201);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 672, 215);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 672, 1235);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 675, 1090);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 675, 972);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 677, 1280);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Clone Alterado", 680, 681);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Doador Genético", 681, 680);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 681, 482);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais novo", 682, 1054);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 689, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 695, 583);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 695, 946);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 695, 957);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Genro", 695, 964);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 696, 838);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 697, 838);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais velho", 699, 306);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 707, 728);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 707, 642);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 708, 728);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 708, 642);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 709, 908);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão gêmeo", 710, 208);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão Gêmeo", 711, 307);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 713, 503);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 713, 373);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Ex-Esposa", 713, 32);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 720, 721);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 721, 720);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 722, 118);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 722, 655);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Dono", 724, 740);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 725, 948);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 727, 225);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 727, 441);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 727, 964);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 727, 957);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 728, 802);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 728, 642);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 728, 86);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 728, 375);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Nora", 728, 380);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 732, 1022);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 732, 634);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Bisavô", 732, 963);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 732, 387);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 732, 83);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 732, 60);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Primo", 732, 614);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 733, 1029);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 738, 356);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 738, 1241);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 738, 808);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Cunhado", 738, 1189);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 740, 838);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 740, 659);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Namorada", 743, 1227);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "irmã", 753, 961);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai adotivo", 755, 568);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 763, 238);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 768, 774);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 774, 768);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 775, 1288);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 775, 1261);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai ", 777, 839);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 780, 108);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 780, 114);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta ", 780, 104);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Nora", 780, 527);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho  Pai de Haku ", 781, 337);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 782, 365);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 782, 380);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 782, 347);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Genro", 782, 802);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 782, 86);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 782, 375);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 783, 423);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 783, 425);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 783, 426);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 784, 526);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 785, 846);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 785, 916);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 786, 962);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposo", 786, 847);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 787, 1041);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "filho", 788, 1276);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai Fusō ", 793, 435);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Parentesco desconhecido", 794, 159);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 797, 885);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 802, 728);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 802, 642);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 802, 375);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 802, 86);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Padrinho", 802, 477);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 802, 380);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 806, 1065);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 806, 401);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 808, 1241);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 808, 356);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 808, 738);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio-avô", 808, 1189);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio-avô", 808, 442);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio-avô", 808, 538);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Bisavô", 808, 93);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 809, 39);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 809, 391);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 809, 365);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Prima", 809, 347);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Prima", 809, 380);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Primo de Segundo Grau", 809, 86);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Prima de Segundo Grau", 809, 375);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 811, 1095);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 815, 119);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho adotivo", 824, 482);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho adotivo", 824, 1263);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Doador Genético", 826, 356);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 826, 1101);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó ", 829, 62);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 838, 659);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 838, 740);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 839, 777);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 844, 18);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 845, 337);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 845, 781);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 846, 785);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 846, 916);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 847, 129);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 847, 962);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 847, 786);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 847, 190);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 848, 999);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 849, 1236);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 850, 1279);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão/Cunhado", 851, 60);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe/Sogra", 851, 83);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai/Sogro", 851, 387);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 851, 614);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha", 851, 732);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 851, 963);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 857, 561);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 878, 496);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 878, 338);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 881, 90);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 882, 212);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 885, 797);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 890, 245);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 890, 514);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 890, 1116);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 890, 1005);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 890, 528);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 890, 1020);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Cunhado", 890, 1293);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Genro", 890, 1007);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais Novo", 898, 465);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais Novo", 898, 912);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 908, 709);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 910, 11);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 910, 289);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 910, 461);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais velho", 912, 898);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais velho", 912, 465);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai Adotivo", 916, 276);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 916, 846);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 916, 785);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa ", 921, 1142);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 923, 201);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 924, 925);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 924, 218);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 925, 924);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 925, 218);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 926, 623);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 926, 187);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 932, 556);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 936, 1193);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 936, 1200);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Namorada", 937, 1041);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão Adotivo", 938, 1015);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 938, 423);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 938, 426);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogro", 938, 425);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogra ", 938, 783);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 939, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 945, 502);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 946, 583);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 946, 695);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 946, 957);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 946, 964);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogro", 946, 225);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogra", 946, 727);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Cunhado", 946, 441);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 948, 725);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 950, 61);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 955, 524);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 957, 225);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 957, 727);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 957, 441);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 957, 964);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 957, 946);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 957, 695);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 957, 583);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Primo", 960, 49);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "irmão", 961, 753);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 962, 129);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 962, 847);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 962, 786);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio-avô", 962, 190);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 963, 387);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 963, 60);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Bisneta", 963, 732);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Bisneto", 963, 614);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 964, 225);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 964, 727);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 964, 441);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 964, 957);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 964, 946);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 965, 225);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 965, 727);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 965, 441);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 972, 1090);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 972, 675);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 977, 1198);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Fonte Genética", 977, 1332);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 996, 1024);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho Adotivo", 996, 1219);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 999, 848);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Noiva", 1000, 342);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 1004, 342);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô Paterno", 1005, 1006);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó Paterna", 1005, 1305);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1005, 1007);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 1005, 1116);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô Materno", 1005, 890);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó Materna", 1005, 528);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 1005, 514);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 1005, 245);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Primo", 1005, 1020);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1006, 1007);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa Shikadai Nara ", 1006, 1305);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1007, 1006);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 1007, 1305);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1007, 1005);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 1007, 1116);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Parente Distante", 1008, 1234);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1009, 1219);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 1010, 228);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão Adotivo", 1015, 938);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 1017, 235);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô Adotivo", 1020, 890);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó Adotiva", 1020, 528);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai Adotivo", 1020, 245);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio Adotivo", 1020, 514);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tia Adotiva", 1020, 1116);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Primo Postiço", 1020, 1005);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio Adotivo", 1020, 1007);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 1022, 634);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 1022, 732);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1024, 996);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão Adotivo ", 1024, 1219);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1025, 996);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 1029, 733);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1032, 327);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 1037, 183);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Antepassado", 1039, 485);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 1041, 787);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Namorado", 1041, 937);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Namorada", 1043, 90);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 1044, 164);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 1046, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 1049, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1050, 545);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais velho", 1054, 682);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1064, 1100);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 1064, 1302);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1065, 401);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 1065, 806);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1068, 1101);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais novo", 1075, 464);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais velho", 1075, 635);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 1075, 437);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1082, 290);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1087, 667);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1087, 455);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 1090, 675);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 1090, 972);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 1094, 1098);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 1095, 811);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Namorado", 1095, 549);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogra", 1095, 1240);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Cunhada", 1095, 346);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 1098, 1094);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1100, 1064);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 1100, 1302);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 1101, 1068);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 1103, 474);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 1109, 52);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 1112, 1242);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 1112, 421);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1116, 890);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 1116, 528);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 1116, 245);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 1116, 514);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho Yashamaru ", 1116, 1005);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 1116, 1007);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 1116, 1020);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogro", 1116, 1006);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogra", 1116, 1305);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1120, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 1120, 57);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 1120, 422);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1120, 344);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Amante", 1120, 494);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1122, 564);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 1122, 895);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1123, 418);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 1125, 1315);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 1140, 63);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 1141, 1262);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 1142, 921);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1189, 93);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 1189, 356);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 1189, 442);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 1189, 538);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha neta", 1189, 1241);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho neto", 1189, 808);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 1190, 24);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 1191, 571);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 1193, 936);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 1193, 1200);