INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 2, 4);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão Adotivo", 2, 560);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Primo", 2, 84);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 4, 2);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 4, 84);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 8, 294);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 11, 289);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 11, 461);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 11, 910);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 18, 844);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 20, 636);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 24, 1190);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 32, 373);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Ex-Marido", 32, 713);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 38, 403);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 39, 365);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 39, 347);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 39, 380);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 39, 391);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 39, 809);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Bisneto", 39, 86);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Bisneta", 39, 375);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Prima", 49, 960);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "filha", 52, 1109);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 56, 539);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 56, 609);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 57, 494);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô ", 57, 1120);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 57, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 57, 344);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 57, 422);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa ", 57, 515);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 60, 963);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 60, 387);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 60, 83);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 60, 732);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 60, 614);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Namorada", 60, 634);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogro", 60, 1022);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 61, 950);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 62, 829);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 63, 1140);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 65, 121);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 83, 387);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 83, 60);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 83, 732);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 83, 614);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 84, 4);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Primo", 84, 2);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 86, 728);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 86, 642);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 86, 802);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 86, 375);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe Neji Hyūga ", 86, 380);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó ", 86, 782);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 86, 365);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tia", 86, 347);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio-Avô", 86, 391);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Bisavô", 86, 39);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 90, 881);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Namorado", 90, 1043);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 93, 442);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 93, 538);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 93, 1189);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 93, 356);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Bisneto", 93, 808);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Bisneta", 93, 1241);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 103, 114);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 103, 108);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha-Neta", 103, 104);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio-avô ", 104, 103);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 104, 114);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 104, 780);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 104, 108);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 104, 527);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 108, 103);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 108, 114);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 108, 780);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 108, 104);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 108, 527);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 111, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 114, 780);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 114, 108);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 114, 104);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Nora", 114, 527);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão ", 114, 103);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 118, 655);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 118, 722);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 119, 815);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 121, 65);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 126, 195);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 129, 847);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 129, 962);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais novo", 129, 190);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 130, 153);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Doador genético", 133, 802);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Doador do chakra", 133, 633);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 153, 129);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 159, 666);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Parentesco desconhecido", 159, 794);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha", 164, 1044);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Namorada", 164, 1241);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 176, 202);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Encarnação com a Árvore DivinaÁrvore Divina ", 177, 494);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Forma Enfraquecida", 177, 206);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 183, 1037);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha", 187, 623);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 187, 926);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 190, 129);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 190, 847);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho-neto", 190, 962);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 195, 126);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 196, 400);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 202, 176);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 205, 576);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Forma original", 206, 177);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão gêmeo", 208, 710);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 212, 882);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 215, 1201);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 215, 672);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 215, 1235);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 218, 924);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "avó", 218, 925);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 219, 287);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 225, 727);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 225, 441);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 225, 964);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 225, 957);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Nora", 225, 946);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 228, 1010);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 235, 1017);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 238, 763);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 239, 793);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 239, 435);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 245, 890);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 245, 528);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 245, 514);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 245, 1116);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 245, 1020);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 245, 1005);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 245, 1293);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 249, 254);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 249, 258);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 254, 249);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 254, 258);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 258, 249);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 258, 254);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho Adotivo", 276, 916);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 287, 219);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 289, 11);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 289, 461);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 289, 910);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 290, 1082);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 294, 8);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 296, 566);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 298, 432);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 306, 699);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão Gêmeo", 307, 711);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 317, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 327, 1032);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 329, 494);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 329, 1120);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 329, 344);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 329, 57);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho Membros do Clã Uchiha, Clã Uzumaki e Clã Senju  ", 329, 422);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 337, 845);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 337, 781);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 338, 496);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 338, 878);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 342, 1004);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Noivo", 342, 1000);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 344, 494);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 344, 1120);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 344, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 344, 57);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 344, 422);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "descendente", 344, 1212);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 346, 1240);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 346, 549);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 347, 39);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 347, 365);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe ", 347, 782);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã mais velha", 347, 380);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 347, 391);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Primo", 347, 809);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 347, 86);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha", 347, 375);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Cunhado", 347, 802);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 356, 93);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 356, 442);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 356, 538);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 356, 1189);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 356, 738);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 356, 1241);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 356, 808);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Namorada", 360, 1273);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 361, 453);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 365, 39);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 365, 391);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 365, 782);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 365, 380);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 365, 347);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 365, 809);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 365, 86);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 365, 375);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Genro", 365, 802);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 373, 713);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avõ", 373, 503);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 373, 32);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 374, 1042);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 375, 728);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 375, 642);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 375, 802);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 375, 86);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 375, 380);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó ", 375, 782);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 375, 365);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tia", 375, 347);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Primo Segundo", 375, 809);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio-Avô", 375, 391);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Bisavô", 375, 39);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 380, 39);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 380, 365);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe ", 380, 782);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 380, 347);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 380, 391);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Primo", 380, 809);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 380, 802);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 380, 86);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 380, 375);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogro", 380, 728);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogra", 380, 642);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Primo", 381, 809);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 381, 365);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 387, 963);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 387, 60);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 387, 732);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 387, 83);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 387, 614);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 391, 39);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 391, 809);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 391, 365);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha", 391, 347);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha", 391, 380);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho-neto", 391, 86);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha-neta", 391, 375);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 392, 39);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 392, 809);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 392, 365);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha", 392, 380);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 401, 1065);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 401, 806);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 405, 38);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais novo ", 407, 414);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais Velho", 414, 407);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 417, 431);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 417, 586);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 418, 1123);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 421, 1112);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 421, 1242);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Padrasto", 421, 497);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó", 422, 494);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô ", 422, 1120);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 422, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 422, 344);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão Membros do Clã Uchiha ", 422, 57);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 423, 425);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 423, 783);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 423, 426);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 423, 938);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 424, 425);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 425, 423);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa ", 425, 783);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 425, 426);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Genro", 425, 938);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avó ", 426, 783);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 426, 425);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 426, 423);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 426, 938);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 431, 417);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 431, 586);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 433, 298);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 435, 793);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 435, 239);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta ", 437, 1075);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto ", 437, 464);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto ", 437, 635);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tataraneto ", 437, 624);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tataraneta", 437, 638);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto ", 437, 598);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 438, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Receptáculo", 440, 466);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 441, 225);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 441, 727);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 441, 964);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Cunhada", 441, 946);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha", 441, 957);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 442, 93);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 442, 356);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 442, 538);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 442, 1189);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha-neta", 442, 1241);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho-neto", 442, 808);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 446, 447);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 446, 451);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 447, 446);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 447, 451);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 451, 447);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 451, 446);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe ", 453, 361);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 455, 1087);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 455, 667);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 461, 11);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 461, 289);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 461, 910);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 464, 1075);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais velho", 464, 635);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 464, 437);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais Velho", 465, 898);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão mais Novo", 465, 912);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 474, 1103);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Afilhado", 477, 802);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe Adotiva", 482, 824);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão Adotivo", 482, 1263);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filhos Adotivos ", 482, 1016);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Descendente", 485, 1039);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 489, 534);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 493, 1282);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 494, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 494, 57);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 494, 422);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 494, 344);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Amante", 494, 1120);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criação", 494, 1334);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Encarnação com o Shinju", 494, 177);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Forma enfraquecida", 494, 206);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 496, 338);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 496, 878);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 497, 1242);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogro", 497, 1112);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Enteado", 497, 421);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 501, 1198);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Fonte Genética", 501, 1332);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 502, 945);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 503, 713);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 503, 373);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 514, 890);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 514, 528);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 514, 245);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 514, 1116);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 514, 1005);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Tio", 514, 1293);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho", 514, 1020);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Cunhado", 514, 1007);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 515, 57);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Cunhado", 515, 422);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogro", 515, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 524, 955);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe ", 526, 784);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogro", 527, 114);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sogra", 527, 780);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 527, 108);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 527, 104);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 528, 245);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 528, 514);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 528, 1116);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 528, 1005);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 528, 890);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 528, 1293);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neto", 528, 1020);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 534, 489);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai adotivo", 537, 466);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 538, 93);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 538, 356);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 538, 442);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 538, 1189);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinha-neta", 538, 1241);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Sobrinho-neto", 538, 808);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 539, 56);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 539, 609);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 545, 1050);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 549, 1240);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmã", 549, 346);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Amante", 549, 1095);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Mãe", 550, 346);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 550, 1240);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 556, 932);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai Adotivo", 560, 4);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão Adotivo", 560, 2);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Primo Adotivo", 560, 84);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 561, 857);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 564, 1122);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 564, 895);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 566, 296);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho adotivo", 568, 755);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 570, 1198);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Fonte Genética", 570, 1332);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Pai", 572, 1191);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 576, 205);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "FilhaŌnoki ", 579, 638);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Avô", 579, 437);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Irmão", 579, 598);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Esposa", 583, 695);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filha", 583, 946);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Neta", 583, 957);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Genro", 583, 964);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Filho", 586, 431);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Marido", 586, 417);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 590, 329);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Criador", 592, 1198);
INSERT INTO `family`(`id`, `relationship`, `parentFromId`, `parentToId`) VALUES (null, "Fonte Genética", 592, 1332);