INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "6", null, null, null, 605, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "-", null, null, null, 605, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "8-9 anos", "27.8 kg - 29.5 kg", null, "Estudante da Academia", 614, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "11-12 anos", "36.9 kg", null, "Genin", 614, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27-28 anos", null, null, "Jonin", 614, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "24", "52.3 kg", "167.5 cm", null, 621, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "28-29", "52.3 kg", "167.5 cm", null, 621, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27-28 anos", null, null, null, 634, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "31-32 anos", null, null, null, 634, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "47-48 anos", null, null, null, 634, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "18 anos", null, null, "Jonin", 638, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "33-34 anos", null, null, "Kage", 638, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "24", "59.2 kg", "175.6 cm", null, 671, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "24", "59.2 kg", "175.6 cm", null, 671, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "38", null, null, null, 679, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, null, 679, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "31 anos", null, null, null, 698, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "46-47 anos", null, null, null, 698, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "19", "62 kg", "173.5 cm", null, 716, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, null, 716, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "20", null, null, null, 717, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "20", null, null, null, 717, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "26-27", null, null, "Jonin", 721, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "29-31", null, null, "Jonin", 721, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "46-47", null, null, "Jonin", 721, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Kage", 728, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Kage", 728, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "8-9 anos", null, "121.8 kg", "Estudante da Academia", 748, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "11-12 anos", null, "139", "Genin", 748, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27-28 anos", null, null, "Jonin", 748, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12-13 anos", "40.1 - 40.6 kg", "145.3 cm - 147.5 cm", "Genin", 802, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "15-20 anos", "50.9 kg", "166 cm", "Genin", 802, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33 anos", null, "180 cm", "Kage", 802, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "13-14 anos", "45.8 kg - 46.8 kg", "159.2 cm - 160.1 cm", "Genin", 809, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "17-18 anos", "54.2 kg", "172.1 cm", "Jonin", 809, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "29-31 anos", "55.9 kg - 70.3 kg", "175.0 cm - 182.0 cm", null, 829, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "13 anos", "44.5 kg", "154.2 cm", null, 829, 3);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "16", null, null, null, 836, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "31-32", null, null, null, 836, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "50-51 anos", "63.9 kg", "172 cm", null, 838, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "53-54 anos", "57.3 kg", "179.4 cm", null, 838, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "69-70 anos", null, null, null, 838, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "31-32", null, null, null, 880, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "35", null, null, null, 880, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "13-14 anos", "46.6 kg - 47.5 kg", "158.5 cm - 162.1 cm", "Genin", 908, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "17-18 anos", "54.7 kg", "172 cm - 177 cm", "Chunin", 908, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "33-34 anos", null, null, "Jonin", 908, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "16-17 anos", null, "172.1 cm", "Anbu", 938, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "20 anos", null, "176 cm", null, 938, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33 anos", null, null, "Chubu", 938, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12-13 anos", "35.4 kg - 35.9 kg", "148.5 cm - 150.1 cm", "Genin", 946, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "15-17 anos", "45.4 kg", "161 cm", "Chunin. Iryo-nin", 946, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33 anos", null, "165 cm", "Jonin. Iryo-nin", 946, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "125 cm", null, 957, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "147 cm - 150 cm", null, 957, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12-13 anos", "42.2 kg - 43.5 kg", "150.8 cm - 153.2 cm", null, 964, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "15-17 anos", "52.2 kg", "168 cm", null, 964, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33 anos", null, "182 cm", null, 964, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "130 cm", null, 981, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "172 cm", null, 981, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "39", "68.9 kg", "181.3 cm", null, 996, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "42", "68.9 kg", "181.3 cm", null, 996, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "19 Anos", "80 kg", "195.6 cm", null, 1001, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "19 Anos", "80 kg", "195.6 cm", null, 1001, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "38 anos", null, null, "Jonin", 1006, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "41-42 anos", null, null, "Jonin", 1006, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12-13", "42-42.9", null, "Genin /  Chunin", 1007, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "15-17", "53.4", "170", "Chunin", 1007, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "19", null, "176", null, 1007, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33", null, null, "Jonin", 1007, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12-13 anos", "45.8 kg - 48.5 kg", "156.2 cm - 161.1 cm", "Genin", 1024, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "15-17 anos", "56.6 kg", "175.1 cm", "Chunin", 1024, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33 anos", null, null, "Jonin", 1024, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "125 cm", null, 1031, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "175 cm", null, 1031, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "28", null, null, null, 1044, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "30-31", null, null, null, 1044, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "34-35", null, null, null, 1044, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "45-46", null, null, null, 1044, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "16-17", null, "177.4 cm", null, 1054, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33", null, "178.6 cm", null, 1054, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 1058, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Chunin", 1058, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "26", null, null, null, 1066, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "26", null, null, null, 1066, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "59-60", null, null, null, 1112, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "62-64", null, null, null, 1112, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "15-16 anos", "44.5 kg - 44.9 kg", "157.3 cm - 159.3 cm", "Genin", 1116, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "18-20 anos", "47.9 kg", "165 cm", "Jonin", 1116, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "35-36 anos", null, "170 cm", null, 1116, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "13-14 anos", "42.2 kg - 43.1 kg", "154.3 cm - 155.6 cm", "Genin", 1124, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "16-18 anos", "47.3 kg", "164 cm", "Chunin", 1124, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "33-34 anos", null, null, null, 1124, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "166 cm", null, 1124, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "43-44 anos", null, "170 cm", null, 1140, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "46-47 anos", null, "178 cm", null, 1140, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Kage", 1189, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Kage", 1189, 2);