INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "97.2 kg", "210.1 cm", null, 1, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "97.2 kg", "210.1 cm", null, 1, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "47 anos", "101.1 kg", "198.2 cm", null, 2, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "62-63 anos", null, null, null, 2, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "84.2 kg", "184.2 cm", null, 3, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "84.2 kg", "184.2 cm", null, 3, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "105.1 kg", "205 cm", null, 4, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "105.1 kg", "205 cm", null, 4, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "6 anos", null, null, null, 6, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "22 anos", null, null, "Chunin", 7, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "48 anos", null, null, null, 8, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "7 anos", null, null, null, 10, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "25 anos", null, null, null, 12, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "159.7 cm", null, 13, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "155.6 cm", "Chunin", 14, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 14, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "3-4 anos", "5.1 kg-5.3 kg", "28 cm-29.1 cm", null, 17, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "7-8 anos", "80.5 kg", "127.2 cm", null, 17, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "23-24 anos", null, null, null, 17, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "9 anos", null, null, null, 18, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "16 anos", null, null, null, 20, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "20 anos", "137 kg", "2.00 m", "Jonin", 21, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "35-36 anos", null, null, null, 21, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "15 anos", null, null, null, 31, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "162 cm", null, 34, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12 anos", null, null, null, 37, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "24-25 anos", "45.8 kg", "167 cm", "Tokubetsu Jonin", 42, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27-28 anos", null, null, "Tokubetsu Jonin", 42, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "43-44 anos", null, null, null, 42, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "46 anos", "70.9 kg", "182 cm", null, 43, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "30 anos", "66 kg", "178 cm", "Tokubetsu Jonin", 44, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "34 anos", null, null, "Tokubetsu Jonin", 44, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "1.82 cm", "Jonin", 46, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 50, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "67 anos", null, null, null, 55, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "128 cm", null, 56, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27-28 anos", "81.6 kg", "190.8 cm", null, 60, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "31 anos", "81.6 kg", "190.8 cm", null, 60, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "19 anos", "65.3 kg", "180 cm", null, 61, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "17-18 anos", "41 kg", null, null, 63, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "18 anos", "40 kg", "140.3 cm", null, 66, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "30-31 anos", "80 kg", "188.2 cm", null, 68, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "33-35 anos", null, null, null, 68, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "31 anos", null, null, null, 70, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "36 anos", null, null, null, 71, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "64 anos", null, null, null, 74, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "65 kg", "180 cm", null, 76, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "41 anos", null, null, "Chunin", 77, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "55 anos", null, null, "Jonin", 83, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "22 anos", null, null, null, 84, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "5 anos", null, "110 cm – 122 cm", null, 86, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "11-12 anos", null, "145 cm", "Genin", 86, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "13 anos", null, null, null, 88, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "38.2 kg", null, null, 89, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 92, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "71.3 kg", "180 cm", null, 93, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "78,9 kg", "172,2 cm", null, 94, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "26 anos", "55.8 kg", "172.2 cm", null, 95, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "198 cm", null, 97, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "11-12 anos", null, null, "Genin", 104, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "33", null, null, null, 105, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "19 anos", "49.5 kg", "163.6 cm", "Jonin", 106, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "34-35 anos", null, null, "Kage", 106, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12-13 anos", "62-69.3 kg", "150.6-156.3 cm", "Genin", 108, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "15-17 anos", null, "172.3 cm", "Chunin", 108, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33 anos", "87.5 kg", "178 cm", null, 108, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "86.5 kg", "186 cm", "Jonin", 110, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27 anos", null, null, "Chunin", 112, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "38-39 anos", "120.1 kg", "183 cm", "Jonin", 114, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "41-42 anos", "120.1 kg", "183 cm", "Jonin", 114, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "31 anos", "59.1 kg", "179 cm", null, 127, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "73 anos", "39.1 kg", "149.1 cm", null, 129, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "34 anos", null, null, null, 131, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 145, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "29 anos", null, null, null, 146, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "30 anos", null, null, "Jonin", 147, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "10 anos", null, null, "Estudante da Academia", 149, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "35 anos", null, null, "Chunin", 150, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "50 anos", null, null, null, 159, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "46 anos", "68 kg", "1.68 cm", null, 161, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "49 anos", "68 kg", null, null, 161, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27 anos", "67.1 kg", "180.2 cm", "Jonin", 164, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "55 kg", null, null, 165, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "26 anos", null, null, "Chunin", 166, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "71-73 anos", "52.7 kg", "170 cm", null, 167, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "16 anos", "48 kg", "171 cm", null, 168, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "26 anos", "68.5 kg", "176.5 cm", "Jonin", 169, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "41-42 anos", null, null, null, 169, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 170, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "19 anos", "50.8 kg", "166 cm", null, 172, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "33 anos", null, null, null, 174, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "11-12 anos", null, "138 cm", "Genin", 176, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "54 anos", "78.9 kg", "176.5 cm", "Jonin", 180, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 181, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "36 anos", null, "162 cm", null, 183, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "14 anos", "49 kg", "156 cm", "Genin", 186, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "28-29 anos", "67.5 kg", "181.4 cm", "Tokubetsu Jonin", 189, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "31-33 anos", null, null, "Tokubetsu Jonin", 189, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "71-72 anos", "45 kg", "158 cm", "Jonin", 190, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "25 anos", null, null, null, 192, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "17", null, null, null, 193, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 198, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "37", null, null, null, 200, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "47.4 kg", "160 cm", "Genin", 210, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "180 cm", null, 211, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "40 anos", "63.1 kg", "175.3 cm", "Jonin", 225, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "180 cm", null, 226, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "36", "156.7 kg", "249.1 cm", null, 227, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12", null, null, null, 229, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "18", null, null, null, 232, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "30", null, null, null, 236, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "35", null, null, null, 238, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "28", null, null, null, 239, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "9", null, null, null, 240, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "147 cm", "Chunin", 243, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 243, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "44", null, null, null, 244, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12-13 anos", "39 kg - 40.2 kg", "146.1 cm - 148.1 cm", "Genin", 245, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "15-20 anos", "50.9 kg", "166.1 cm", "Kage", 245, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33 anos", null, null, null, 245, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "172.5 cm", null, 245, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "192 cm", null, 246, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "31", null, null, null, 247, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "1700 cm", null, 249, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "1900 cm", null, 252, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "1900 cm", null, 253, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "1690 cm", null, 254, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "29", null, null, null, 264, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "55.5 kg", "173.6 cm", null, 267, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "16", "46,5 kg", "163,3 cm", null, 268, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "10", null, null, null, 269, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "48", "69 kg", "162.5 cm", null, 271, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "22", null, null, null, 275, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "17 anos", "57.3 kg", "172 cm", null, 278, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "75,4 kg", "186,6 cm", null, 282, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "90", null, null, null, 284, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "29-30", "71 kg", "181 cm", null, 285, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33", "71 kg", "181 cm", null, 285, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "22", null, null, null, 288, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "58", null, null, null, 291, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "61 Presumivel", null, null, null, 291, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "49", null, null, null, 294, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "23", null, null, null, 295, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "44", "78.5 kg", "177.9 cm", null, 296, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "180 cm", null, 297, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "42", null, null, null, 301, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "37", null, null, null, 303, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "25", "73.3 Kg", "178 cm", null, 306, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "168 cm", null, 314, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "25", null, null, null, 315, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 318, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "172 cm", null, 320, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "17", null, null, "Genin", 321, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "1.45 cm", "Genin", 324, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "18", null, null, null, 325, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "26", null, null, null, 326, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "69 kg", "186 cm", null, 329, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 336, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "15", "43.2 kg", "155.9 cm", null, 337, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "24", null, null, null, 340, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "33", null, null, null, 343, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "185 cm[3]", null, 344, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "114.7 kg", "228.3 cm", null, 345, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "18", "52.5kg", "170.3cm", null, 346, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "21-22", "52.5kg", "170.3cm", null, 346, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "7 anos", "28.9 kg", "132.4 cm", null, 347, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "10-11 anos", null, null, "Genin", 347, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "28 anos", null, "170 cm", "Jonin", 347, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Jonin", 348, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "58,6 kg", "177 cm", null, 350, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "8", null, null, null, 353, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "74 kg", "185.1 cm", null, 356, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "74 kg", "185.1 cm", null, 356, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "24", null, null, null, 359, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "23", "58 Kg", "175 cm", null, 360, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "37 anos", null, null, null, 364, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "41-42", "66.4 kg", "176.5 cm", "Jonin", 365, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "46", "59.6 kg", null, null, 365, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "48", null, null, null, 365, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "61", null, "165 cm", null, 365, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "9", null, null, null, 367, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "22-23", "56.8 kg", "177.1 cm", null, 368, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "25", null, null, null, 371, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "26 anos", null, null, null, 372, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "3 anos", null, "93 cm–102 cm", null, 375, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "138 cm", null, 375, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12-13 anos", "37.9 kg-38.2 kg", "147.3 cm-148.3 cm", "Genin", 380, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "16 anos", "45 kg", "160 cm", "Chunin", 380, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33 anos", null, null, null, 380, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "163 cm", null, 380, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "14 anos", null, null, "Anbu", 384, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "68-69 anos", "50.6 kg", "163.1 cm", "Kage", 387, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32", "66.3", "176.5", "Jonin", 391, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "58.5", null, null, 391, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 396, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "68-69", "55.2 kg", "166 cm", null, 397, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "71-73", null, null, null, 397, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "153 cm", null, 400, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Jonin", 401, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "21", null, null, null, 402, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "28", null, null, null, 406, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, null, 406, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27 anos", "88 kg", "193.5 cm", "Tokubetsu Jonin", 407, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "31 anos", null, null, "Tokubetsu Jonin", 407, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "22", null, null, null, 411, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 414, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "45", null, null, null, 417, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "25", null, null, null, 419, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "22", null, null, null, 420, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "8", "27.6 kg", "128.5 cm", null, 421, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12", "43.9 kg", "152.1 cm", null, 421, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12-13", "38.2-38.5", "149.3 - 151.2 cm", "Genin", 423, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "15-17", "46", "162.2 cm", "Chunin", 423, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "19-20", null, null, null, 423, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33", null, "164 cm", null, 423, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "38", "69.1 kg", "180.4 cm", null, 425, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "41-42", "69.1 kg", "180.4 cm", null, 425, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "11-12 anos", null, "1.47 cm", "Genin", 426, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "23", null, null, null, 427, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27 anos", null, null, null, 430, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "22-23", "66.2 kg", "178 cm", null, 431, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "25-27", "66.2 kg", "178 cm", null, 431, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "42-43", null, null, null, 431, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "38", null, null, "Jonin", 432, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "34", null, null, null, 435, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "46,3 kg", "145 cm", null, 437, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "17-18", "57.1 kg", "175.2 cm", "Anbu", 441, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "21", "58 kg", "178 cm", "Anbu", 441, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "16", null, null, null, 444, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "1.67 cm", null, 445, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32", null, null, "Chunin", 449, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "23-24", "61.5 kg", "173 cm", null, 450, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27-28", null, null, null, 450, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 453, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "24", "58 kg", "169 cm", null, 454, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "28", "58 kg", "169 cm", null, 454, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "24", "55,9 kg", "174,8 cm", null, 455, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "18-19 anos", "75.8 kg", "202.1 cm", null, 457, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "34-35 anos", null, null, null, 457, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "51", null, null, null, 458, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "31", null, null, null, 459, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "52", null, null, null, 463, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "185 cm", null, 467, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "16", null, null, null, 469, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 471, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "92.5 kg", "179 cm", null, 472, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "65,1 Kg", "172 cm", "Jonin", 473, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "14", "97.3 kg", "181.3 cm", null, 475, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "50-51 anos", "87.5 kg", "1.91 cm", "Jonin", 477, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "54 anos", null, null, null, 477, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "22", null, null, null, 480, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "36", null, null, null, 481, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "19-20 anos", "65 kg", "176.2 cm", "Genin", 482, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "22-24 anos", null, "177 cm", null, 482, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "46-47 anos", null, null, null, 482, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "25", null, "169cm", null, 485, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "17 anos", "54 kg", "168.8 cm", "Genin", 486, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Anbu", 487, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Chunin", 493, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "30", "75 kg", "183 cm", null, 497, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "39", null, null, null, 499, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "26-27 anos", "67.5 kg", "181 cm", "Jonin", 502, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "29-31 anos", null, null, "Jonin", 502, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "46-47 anos", null, null, "Kage", 502, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27", "68.3 kg", "180.3 cm", null, 504, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "38", null, null, null, 505, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "91", "63.2 kg", "185 cm", null, 506, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "16 anos", null, null, null, 507, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "14-15 anos", "60 kg-61.2 kg", "165 cm-167 cm", "Genin", 514, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "17-19 anos", "61.2 kg", "175 cm", "Jonin", 514, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "34-35 anos", null, null, null, 514, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27 anos", null, null, null, 519, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "62", null, null, null, 520, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "28", null, null, null, 521, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "22", null, null, null, 525, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "16-17", "45.8", "162.6 cm", "Genin", 526, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33", null, "166 cm", null, 526, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "17 anos", "47.9 kg", "1.66 cm", "Chunin", 527, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33 anos", null, null, null, 527, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, "50.7 Kg", "170.5 cm", null, 528, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "6", null, null, null, 530, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "25", null, null, null, 531, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12", null, null, null, 532, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "170 cm", "Tokubetsu Jonin", 533, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "183 cm", null, 537, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "7", null, null, null, 538, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "161 cm", null, 539, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "41", null, null, null, 542, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Genin", 543, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "174 cm", "Jonin", 547, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "36", null, null, null, 548, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "12-13 anos", "43.3-44.7 kg", "151.2-152.5cm", "Genin", 549, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "15-17 anos", "52.5 kg", "169.1 cm", "Chunin", 549, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32-33 anos", null, "173 cm", null, 549, 4);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Jonin[9]", 549, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "14", "58.2 kg", "159.2 cm", null, 551, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "18", null, null, null, 553, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "36 anos", "87.1 kg", "192 cm", null, 560, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "51-52 anos", null, null, null, 560, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "15", "49.8 kg", "166.1 cm", null, 561, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "14", "39kg", "150cm", null, 563, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "11", null, null, null, 564, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "44", "80.1 kg", "183.9 cm", null, 566, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "+1000 anos", null, "231 cm", null, 568, 5);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "29 anos", "83.1 kg", "195 cm", null, 575, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "32 anos", "83.1 kg", "195 cm", null, 575, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "27", null, null, null, 577, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "44", "120.5 kg", "217 cm", "Jonin", 579, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "30", null, null, null, 580, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "170.18 cm", null, 581, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, "184.4 cm", "Genin", 583, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "19", null, null, null, 585, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "45", null, null, null, 586, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "68-69", "46.3 kg", "153 cm", null, 587, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "71-73", "46.3 kg", "153", null, 587, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "24", null, null, null, 589, 2);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, null, null, null, "Anbu", 594, 1);
INSERT INTO `ninja_attr`(`id`, `age`, `height`, `weight`, `ninja_rank`, `ninjaId`, `seasonId`) VALUES (null, "16", null, null, null, 596, 1);