version: '3.8'
services:
  db:
    image: mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - naruto_data:/var/lib/mysql
    ports:
      - '3306:3306'
  app:
    build: .
    env_file: .env
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    links:
      - db
    depends_on:
      - db
volumes:
  naruto_data:
