INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Kumogakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Forcas Aliadas Shinobi");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Cla Kamizuru");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Sunagakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais das Ondas");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais dos Ancestrais");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Amegakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Hoshigakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Konohagakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Iwagakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais das Florestas");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Mar");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Otogakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Kara");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Fogo");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Kirigakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila dos Bambus");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Moyagakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Caverna Ryuchi");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Sora-ku");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Relâmpago");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Yugakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Uzushiogakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Ilha Benisu");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais da Água");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Templo do Fogo");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Kusagakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Castelo Hozuki");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Yumegakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Cha");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Takigakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila Tonika");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila Tsuchigumo");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais dos Pântanos");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Macarrao");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais das Fontes Termais");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais dos Passaros");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Isto");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Ferro");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Akatsuki");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais da Geada");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais da Terra");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Vento");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Raiz");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Fortaleza de Gato");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila Hacho");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Yukigakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Lua");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Ishigakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Roran");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila do Mormaco");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Continente de Temujin");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Monte Myoboku");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Som");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais da Pedra");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Empresa Gato");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais da Neve");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Ka");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Silêncio");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila Inaho");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila Kagero");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais dos Demônios");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vale das Nuvens e Relâmpago");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais dos Rios");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila Jomae");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Orfanato de Konoha");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais dos Vegetais");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais da Lua");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Monte Shumisen");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila Takumi");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Monte Verde");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila do Uivo do Lobo");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila da Árvore Caida");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Floresta Shikkotsu");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Mel");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Dimensao otsutsuki");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Castelo Kazahana");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais da Madeira");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Pescoco");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila Nadeshiko");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais dos Vales");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila de Shuku");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Céu");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Tsukigakure");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Corporacao Makibi");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila Daidai");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Cla Nara");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Enka Ninja");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Loja do Curry da Vida");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Cla Uzumaki");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Pais do Isso");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Caverna Oculta por Água");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila da Árvore Genjutsu");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Companhia Himeyuri");
INSERT INTO `affiliation`(`id`, `name`) VALUES ( null, "Vila Oculta da Lua");