INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Kedoin");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Inuzuka");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Ryu");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Hyuga");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Kamizuru");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Fuma");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Uzumaki");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla otsutsuki");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Sarutobi");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Uchiha");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Senju");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Tsuchigumo");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Chinoike");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Akimichi");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Nara");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Shimura");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Familia Kaminarimon");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Onikuma");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Tenro");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Familia Wagarashi");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Yamanaka");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Familia Kagetsu");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Kazekage");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Shirogane");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Hozuki");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Amagiri");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Iburi");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Yuki");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Familia Hoki");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Taketori");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Familia Wasabi Adotado");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Sendo");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Familia Wasabi");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla de Jugo");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Familia Karatachi");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Hatake");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla do Pais dos Vegetais");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Kaguya");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Kodon");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Hoshigaki");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Yotsuki");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Kubisaki");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Rinha");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Shiin");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Lee");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla da Prisão Celestial");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Kurama");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Aburame");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Watari Ninja");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Yoimura");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla de Ryuzetsu");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Casa dos Kakei");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla de Tenma");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla de Yomi");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Hirasaka");
INSERT INTO `clan`(`id`, `name`) VALUES ( null, "Cla Otenki");