INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Kage");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Invocacao");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Ninken");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Iryo-nin");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Ninja Médico");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Tipo Sensor");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Oinin");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Nukenin");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Monge Ninja");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Ninja Médica");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Jinchuriki");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Pseudo-Jinchuriki");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Chefe de Aldeia");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Daimyo");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Samurai");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Besta com Cauda");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Rank S");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Ninja Mercenario");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Criminoso");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Sabio");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Sensor");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Sennin");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Ninja Cozinheiro");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Ninjas Mercenarios");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Jonin");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Ninja Mercenaria");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Kekkei Genkai, Ninjutsu, Dojutsu");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Biju");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Marionete");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Bandido");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Ninja Chefe");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Sannin");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Técnica de Invocacao");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Desaparecido");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Nukenin Anterior");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Rei do Pais da Lua");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Ministro do Pais da Lua");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Lorde");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Ninja Monge");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Tokubetsu Jonin");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Sênior");
INSERT INTO `classification`(`id`, `name`) VALUES ( null, "Subordinado de Sasori");