INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Kekkei Genkai");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Senjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Ninjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Taijutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Bukijutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Fuinjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Hiden");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Kekkei Mora");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Genjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Juinjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Habilidade Geral");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Nintaijutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Kenjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Konbijutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Kyuinjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Ninjutsu Espaco-Tempo");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Shurikenjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Ninjutsu Médico");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Saiseijutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Kinjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Armadilha");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Bunshinjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Fluxo de Chakra");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Dojutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Pseudo-Kekkei Tota");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Formação"); 
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Yugojutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Konbijutu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Iryo Ninjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Estilo de Luta");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Kekkaijutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Kusarigamajutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Tessenjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Kayakujutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Acao Suicida");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Bojutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Rank S");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Tipo Sensor");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Juinjutsu‏‎");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Kinkojutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Tonjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Kekkei Tota");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Ninjutsu de Medicina Negra");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Kyūinjutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Ninjutsu de Reencarnacao");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Kyujutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Ofensivo");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Fukuwajutsu");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Ninjutsu Espaço-Tempo");
INSERT INTO `classification_jutsu`(`id`, `name`) VALUES ( null, "Fórmula de Selamento");