INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Raikage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider Supremo das Forcas Aliadas Shinobi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe do Cla Kedoin");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Prisioneiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Subordinada de Tenji");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Assistente pessoal de Kaguya otsutsuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Hoshikage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Carpinteiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-costas do Tsuchikage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Assistente da Tsuchikage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Cientista");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Assistente de Katasuke Tono");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Interno da Kara");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Aprendiz de Médico");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Cla Hyuga Anterior");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Examinadora do Exame Chunin");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Professora da Academia");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-costas da Quinta Mizukage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao da Divisão de Sensor das Forcas Aliadas Shinobi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Apicultor");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Atriz");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Cla Uzumaki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Assistente do Escultor de Pedra");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Astrônoma");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Assistente da Hokage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Garconete");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider de Bandidos");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Sênior");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Anbu");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Monge Chefe");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-chefe do Castelo Hozuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Aprendiz de jardineiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Sacerdote");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Mizukage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao do Esquadrão Assassino de Suna");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider dos Hipopótamos");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe da Vila Tonika");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe de Aldeia");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe da Vila Tsuchigumo");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Monge Lider");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Assistente do Conselheiro-Chefe do Daimyo");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Conselheira Aposentada");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Jogador");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Cla Akimichi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe da Anbu");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Professor da Academia");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Daimyo");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider da Raiz");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Conselho de Konoha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Candidato à Sexto Hokage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-costas do Quarto Raikage Antigamente");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Comandante da Primeira Divisao das Forcas Aliadas Shinobi Antigamente");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Terrorista de Bombardeio");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Fornecedor");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe da Vila Hacho");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Ex-Diretor de Milicia");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider dos Coalas");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Doutor");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Treinador Particular");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Conselho de Suna");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Anfitria");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Viajante");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Colecionador de Kekkei Genkai");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Conselheiro do Cla Nara");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider de Yumegakure");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Presidente da Companhia Kaminarimon");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Escultor de Pedra");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Terrorista");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Princesa");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Cla Uchiha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao da Policia Militar de Konoha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Sapo Anciao");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Bandido");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Herborista");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Enfermeira");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Ladrao Anterior");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Seguidor do Ninshu");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lutador de En Oyashiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Grupo do Relâmpago");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Vendedor de Ervas Medicinais");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Kazekage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Comandante Regimental das Forcas Aliadas Shinobi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Comandante da Quarta Divisao");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Agricultor");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao do Corpo de Explosão");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider da Alianca Armamentista Ryuha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Externo");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Pirata");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Cacador de Recompensas");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Empresario");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Criminoso");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Campo de treinamento");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Ministro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider dos Iluminados");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Anciao da Vila");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-costas de elite");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Fotógrafo");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Trabalhador de Contrucao");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Banqueiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Ator");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guia turistico da Cidade Tanzaku");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Ladrao");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-Costas");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guardiao de Kinshiki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Subordinado de Zabuza");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Minerador");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Monge");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Programador");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider das forcas utópicas");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda do Castelo Hozuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chef de cozinha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider da Família Hoki Anteriormente");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do ramo secundario do Cla otsutsuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Veterinaria");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Herdeira do cla Hyuga");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Espia");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Cla Fuma");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider de Amegakure");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Cla Senju");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Hokage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Examinador");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Cla Hyuga");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao de Navio");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Principe do País da Lua");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Coletora de Cogumelos");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Mercenario");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Herdeira do cla Hyuga Anteriormente");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Dona de Casa Atualmente");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Marinheiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda Marinha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Conselheiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Iryo-nin");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Dona de Casa");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe da Forca de Tortura e Interrogaçao de Konoha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guardia da Caverna Ryuchi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Corredor");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Fazendeiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Aprendiz de Carpinteiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Botânica");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Time de Barreira de Konoha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Cla Yamanaka");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Proprietario da Loja de Flores Yamanaka");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Time de Analise");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao da Divisão de Inteligência das Forcas Aliadas Shinobi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Diretor da Academia[4]");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Tsuchikage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider da Kara");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao da Anbu Anterior");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Inspetor de Exame");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Examinador do Exame Chunin");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda do Portao da Vila");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Assistente da Quinta Hokage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Inventor de armas ninja");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe de Aldeia Novela");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Escritor");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Cla Sendo");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe da Familia Wasabi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Braco direito e espiao de Orochimaru");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Espiao de Sasori");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Cuidador do Orfanato de Konoha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Assistente do Sexto Mizukage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Cla otsutsuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Mestre do Castelo Hozuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Pescador");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Comandante da Terceira Divisao das Forcas Aliadas Shinobi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Rei do Pais da Lua");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Tesoureiro da Akatsuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe da Gangue Kanabun");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Presidente da Corporacao Kaneki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-costas do Kazekage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao da Divisão de Ataque Surpresa das Forcas Aliadas Shinobi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider da Divisao Contra Terrorismo");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Carpinteiro Chefe");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Zelador");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Assistente Chefe");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Soldado da Familia Kurosuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Protetora dos esconderijos de Orochimaru[3]");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Grupo do Trovao Negro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Time Científico de Armas Ninja de Konoha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Interno");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Vendedor de Balões");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Zeladora");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Modelo Comercial [6]");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Treinador de Ninken Anime e Novela[7]");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Investigador da Policia de Konoha [8]");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda Costa do Daimyo");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guardiao de Kumogakure");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Servo de Momoshiki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Monte Verde");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Comandante da Segunda Divisao da Alianca Shinobi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Assistente de loja de sushi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Conselheira");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Contador dos Bandidos Mujina anterior");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe da Agência de Correios");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao Militar do Pais da Lua");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Examinador dos Exame Chunin");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Joalheiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Vendedor de mascaras");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Contador");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-Costas de Hinata");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Estrategista do Pais dos Passaros");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Sapo Mensageiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao da Policia de Konoha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Cantora");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guardiao da Ilha Tartaruga");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider da Vila Jomae");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Assistente do Raikage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Co-fundador de Konohagakure");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do cla Uchiha Anterior");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Vendedora de Ervas Medicinais");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Diretor de Filme");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe da Aldeia");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Espiao");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Garcom");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao da Anbu");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda Pessoal");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "General");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Comandante da Quinta Divisao das Forcas Aliadas Shinobi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Desenvolvedora de projetos");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Ministro Antigo");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Sacerdotisa");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Espiao de Otogakure");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-Costas do Mizukage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe do Esquadrao de Criptograma");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Instrutor da Academia");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guia");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Mestre do Castelo Hozuki e Guardiao da Caixa da Felicidade Suprema");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Comandante do Castelo Hozuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Espiao da Akatsuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Subordinado de Sasori");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Cla Kurama");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Agricultora");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider da Vila Nadeshiko");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Médico");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider da Akatsuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Empregada");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lojista");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe do Ninneko");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao do Pais do Céu");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Cuidadora do Orfanato de Konoha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capita da Corpo Médico de Konoha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Antiga Anbu Raiz");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider Secreto de Kirigakure");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-costas do Raikage");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Fundador e Lider de Otogakure");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Ladrao-nobre");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider da Vila");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do cla Kaguya");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Assassino");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe da Familia Kurosuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Aprendiz de Cozinheiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do cla Kazekage[2]");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Empregado de pousada");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Examinador dos Exames Chunin");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Investigador da Policia de Konoha");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Cantor de Enka");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Pretendente a Daimyo");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Comerciante");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Instrutor dos Exames Chunin");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Diretor da Anbu");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Fundadora e Diretora da Clinica Infantil de Assistência Médica Mental do Hospital de Konoha[11]");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Assistente pessoal de Koyuki Kazahana");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Cuteleiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Corretor de Empréstimos");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider de Takigakure");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Decodificadora");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Chefe do Cla Nara");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Herdeiro de Veados");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Jonin Comandante");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Estrategista Chefe das Forcas Aliadas Shinobi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Representante da Quarta Divisao das Forcas Aliadas Shinobi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Conselheiro do Sétimo Hokage[8]");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Planejador para a Uniao Shinobi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Cla Nara");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Sapa Ancia");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Jardineiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Fabricante de Panelas");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Instrutor da Academia[6]");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider do Grupo de Magaki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Oficial Militar");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Secretaria particular da Hokage[4]");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capita da Divisão de Suporte Médico e Logistico das Forcas Aliadas Shinobi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider dos Bandidos Mujina");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Aprendiz de Io");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Treinador de Shibuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Protetor dos esconderijos de Orochimaru[3]");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Professora da Academia Ninja");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Rainha de Roran");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda da Patrulha da Fronteira");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-Costas de Shion");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-costas");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Carteiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Embaixadora");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Instrutora dos Exames Chunin");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Imperador do Pais dos Ancestrais");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Proprietaria de uma Loja de Ferramentas Ninjas");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Politico");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Ajudante do Pais da Água");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Cozinheiro");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Dono de um estabelecimento");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guardia de Shizuka");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guardiao do Monte Katsuragi");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Ornitólogo");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Dona de casa");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider da Oinin");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Capitao da Policia");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Ninken");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-costas de Gato Mercenario");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Fundador e lider da Akatsuki");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Herdeira do Cla Kurama");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Mordomo do daimyo");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Lider dos lutadores de Sumô");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Guarda-Costas do Daimyo");
INSERT INTO `occupation`(`id`, `name`) VALUES ( null, "Mestre de Troca de Recompensas");