INSERT INTO "Clan" ("id", "name") VALUES
(1, E'Cla Kedoin'),
(2, E'Cla Inuzuka'),
(3, E'Cla Ryu'),
(4, E'Cla Hyuga'),
(5, E'Cla Kamizuru'),
(6, E'Cla Fuma'),
(7, E'Cla Uzumaki'),
(8, E'Cla otsutsuki'),
(9, E'Cla Sarutobi'),
(10, E'Cla Uchiha'),
(11, E'Cla Senju'),
(12, E'Cla Tsuchigumo'),
(13, E'Cla Chinoike'),
(14, E'Cla Akimichi'),
(15, E'Cla Nara'),
(16, E'Cla Shimura'),
(17, E'Familia Kaminarimon'),
(18, E'Cla Onikuma'),
(19, E'Cla Tenro'),
(20, E'Familia Wagarashi'),
(21, E'Cla Yamanaka'),
(22, E'Familia Kagetsu'),
(23, E'Cla Kazekage'),
(24, E'Cla Shirogane'),
(25, E'Cla Hozuki'),
(26, E'Cla Amagiri'),
(27, E'Cla Iburi'),
(28, E'Cla Yuki'),
(29, E'Familia Hoki'),
(30, E'Cla Taketori'),
(31, E'Familia Wasabi Adotado'),
(32, E'Cla Sendo'),
(33, E'Familia Wasabi'),
(34, E'Cla de Jugo'),
(35, E'Familia Karatachi'),
(36, E'Cla Hatake'),
(37, E'Cla do Pais dos Vegetais'),
(38, E'Cla Kaguya'),
(39, E'Cla Kodon'),
(40, E'Cla Hoshigaki'),
(41, E'Cla Yotsuki'),
(42, E'Cla Kubisaki'),
(43, E'Cla Rinha'),
(44, E'Cla Shiin'),
(45, E'Cla Lee'),
(46, E'Cla da Prisão Celestial'),
(47, E'Cla Kurama'),
(48, E'Cla Aburame'),
(49, E'Watari Ninja'),
(50, E'Cla Yoimura'),
(51, E'Cla de Ryuzetsu'),
(52, E'Casa dos Kakei'),
(53, E'Cla de Tenma'),
(54, E'Cla de Yomi'),
(55, E'Cla Hirasaka'),
(56, E'Cla Otenki');

