INSERT INTO "Occupation" ("id", "name") VALUES
(1, E'Raikage'),
(2, E'Lider Supremo das Forcas Aliadas Shinobi'),
(3, E'Chefe do Cla Kedoin'),
(4, E'Prisioneiro'),
(5, E'Subordinada de Tenji'),
(6, E'Assistente pessoal de Kaguya otsutsuki'),
(7, E'Hoshikage'),
(8, E'Carpinteiro'),
(9, E'Guarda-costas do Tsuchikage'),
(10, E'Assistente da Tsuchikage'),
(11, E'Cientista'),
(12, E'Assistente de Katasuke Tono'),
(13, E'Interno da Kara'),
(14, E'Aprendiz de Médico'),
(15, E'Lider do Cla Hyuga Anterior'),
(16, E'Examinadora do Exame Chunin'),
(17, E'Professora da Academia'),
(18, E'Guarda-costas da Quinta Mizukage'),
(19, E'Capitao da Divisão de Sensor das Forcas Aliadas Shinobi'),
(20, E'Apicultor'),
(21, E'Atriz'),
(22, E'Lider do Cla Uzumaki'),
(23, E'Assistente do Escultor de Pedra'),
(24, E'Astrônoma'),
(25, E'Assistente da Hokage'),
(26, E'Garconete'),
(27, E'Lider de Bandidos'),
(28, E'Sênior'),
(29, E'Anbu'),
(30, E'Monge Chefe'),
(31, E'Guarda-chefe do Castelo Hozuki'),
(32, E'Aprendiz de jardineiro'),
(33, E'Sacerdote'),
(34, E'Mizukage'),
(35, E'Capitao do Esquadrão Assassino de Suna'),
(36, E'Capitao'),
(37, E'Lider dos Hipopótamos'),
(38, E'Chefe da Vila Tonika'),
(39, E'Chefe de Aldeia'),
(40, E'Chefe da Vila Tsuchigumo'),
(41, E'Monge Lider'),
(42, E'Assistente do Conselheiro-Chefe do Daimyo'),
(43, E'Conselheira Aposentada'),
(44, E'Jogador'),
(45, E'Lider do Cla Akimichi'),
(46, E'Chefe da Anbu'),
(47, E'Professor da Academia'),
(48, E'Daimyo'),
(49, E'Lider da Raiz'),
(50, E'Conselho de Konoha'),
(51, E'Candidato à Sexto Hokage'),
(52, E'Guarda-costas do Quarto Raikage Antigamente'),
(53, E'Comandante da Primeira Divisao das Forcas Aliadas Shinobi Antigamente'),
(54, E'Terrorista de Bombardeio'),
(55, E'Fornecedor'),
(56, E'Chefe da Vila Hacho'),
(57, E'Ex-Diretor de Milicia'),
(58, E'Lider dos Coalas'),
(59, E'Doutor'),
(60, E'Treinador Particular'),
(61, E'Lider do Conselho de Suna'),
(62, E'Anfitria'),
(63, E'Viajante'),
(64, E'Colecionador de Kekkei Genkai'),
(65, E'Conselheiro do Cla Nara'),
(66, E'Lider de Yumegakure'),
(67, E'Presidente da Companhia Kaminarimon'),
(68, E'Escultor de Pedra'),
(69, E'Terrorista'),
(70, E'Princesa'),
(71, E'Lider do Cla Uchiha'),
(72, E'Capitao da Policia Militar de Konoha'),
(73, E'Sapo Anciao'),
(74, E'Bandido'),
(75, E'Guarda'),
(76, E'Herborista'),
(77, E'Enfermeira'),
(78, E'Ladrao Anterior'),
(79, E'Seguidor do Ninshu'),
(80, E'Lutador de En Oyashiro'),
(81, E'Lider do Grupo do Relâmpago'),
(82, E'Vendedor de Ervas Medicinais'),
(83, E'Kazekage'),
(84, E'Comandante Regimental das Forcas Aliadas Shinobi'),
(85, E'Comandante da Quarta Divisao'),
(86, E'Agricultor'),
(87, E'Capitao do Corpo de Explosão'),
(88, E'Lider da Alianca Armamentista Ryuha'),
(89, E'Externo'),
(90, E'Pirata'),
(91, E'Cacador de Recompensas'),
(92, E'Empresario'),
(93, E'Criminoso'),
(94, E'Campo de treinamento'),
(95, E'Ministro'),
(96, E'Lider dos Iluminados'),
(97, E'Anciao da Vila'),
(98, E'Guarda-costas de elite'),
(99, E'Fotógrafo'),
(100, E'Trabalhador de Contrucao'),
(101, E'Banqueiro'),
(102, E'Ator'),
(103, E'Guia turistico da Cidade Tanzaku'),
(104, E'Ladrao'),
(105, E'Guarda-Costas'),
(106, E'Guardiao de Kinshiki'),
(107, E'Subordinado de Zabuza'),
(108, E'Minerador'),
(109, E'Monge'),
(110, E'Programador'),
(111, E'Lider das forcas utópicas'),
(112, E'Guarda do Castelo Hozuki'),
(113, E'Chef de cozinha'),
(114, E'Lider da Família Hoki Anteriormente'),
(115, E'Lider do ramo secundario do Cla otsutsuki'),
(116, E'Veterinaria'),
(117, E'Herdeira do cla Hyuga'),
(118, E'Espia'),
(119, E'Lider do Cla Fuma'),
(120, E'Lider de Amegakure'),
(121, E'Lider do Cla Senju'),
(122, E'Hokage'),
(123, E'Examinador'),
(124, E'Lider do Cla Hyuga'),
(125, E'Capitao de Navio'),
(126, E'Principe do País da Lua'),
(127, E'Coletora de Cogumelos'),
(128, E'Mercenario'),
(129, E'Herdeira do cla Hyuga Anteriormente'),
(130, E'Dona de Casa Atualmente'),
(131, E'Marinheiro'),
(132, E'Guarda Marinha'),
(133, E'Conselheiro'),
(134, E'Iryo-nin'),
(135, E'Dona de Casa'),
(136, E'Chefe da Forca de Tortura e Interrogaçao de Konoha'),
(137, E'Guardia da Caverna Ryuchi'),
(138, E'Corredor'),
(139, E'Fazendeiro'),
(140, E'Aprendiz de Carpinteiro'),
(141, E'Botânica'),
(142, E'Lider do Time de Barreira de Konoha'),
(143, E'Lider do Cla Yamanaka'),
(144, E'Proprietario da Loja de Flores Yamanaka'),
(145, E'Lider do Time de Analise'),
(146, E'Capitao da Divisão de Inteligência das Forcas Aliadas Shinobi'),
(147, E'Diretor da Academia[4]'),
(148, E'Tsuchikage'),
(149, E'Lider da Kara'),
(150, E'Capitao da Anbu Anterior'),
(151, E'Inspetor de Exame'),
(152, E'Examinador do Exame Chunin'),
(153, E'Guarda do Portao da Vila'),
(154, E'Assistente da Quinta Hokage'),
(155, E'Inventor de armas ninja'),
(156, E'Chefe de Aldeia Novela'),
(157, E'Escritor'),
(158, E'Lider do Cla Sendo'),
(159, E'Chefe da Familia Wasabi'),
(160, E'Braco direito e espiao de Orochimaru'),
(161, E'Espiao de Sasori'),
(162, E'Cuidador do Orfanato de Konoha'),
(163, E'Assistente do Sexto Mizukage'),
(164, E'Lider do Cla otsutsuki'),
(165, E'Mestre do Castelo Hozuki'),
(166, E'Pescador'),
(167, E'Comandante da Terceira Divisao das Forcas Aliadas Shinobi'),
(168, E'Rei do Pais da Lua'),
(169, E'Tesoureiro da Akatsuki'),
(170, E'Chefe da Gangue Kanabun'),
(171, E'Presidente da Corporacao Kaneki'),
(172, E'Guarda-costas do Kazekage'),
(173, E'Capitao da Divisão de Ataque Surpresa das Forcas Aliadas Shinobi'),
(174, E'Lider da Divisao Contra Terrorismo'),
(175, E'Carpinteiro Chefe'),
(176, E'Zelador'),
(177, E'Assistente Chefe'),
(178, E'Soldado da Familia Kurosuki'),
(179, E'Protetora dos esconderijos de Orochimaru[3]'),
(180, E'Lider do Grupo do Trovao Negro'),
(181, E'Lider do Time Científico de Armas Ninja de Konoha'),
(182, E'Interno'),
(183, E'Vendedor de Balões'),
(184, E'Zeladora'),
(185, E'Modelo Comercial [6]'),
(186, E'Treinador de Ninken Anime e Novela[7]'),
(187, E'Investigador da Policia de Konoha [8]'),
(188, E'Guarda Costa do Daimyo'),
(189, E'Guardiao de Kumogakure'),
(190, E'Servo de Momoshiki'),
(191, E'Lider do Monte Verde'),
(192, E'Comandante da Segunda Divisao da Alianca Shinobi'),
(193, E'Assistente de loja de sushi'),
(194, E'Conselheira'),
(195, E'Contador dos Bandidos Mujina anterior'),
(196, E'Chefe da Agência de Correios'),
(197, E'Capitao Militar do Pais da Lua'),
(198, E'Examinador dos Exame Chunin'),
(199, E'Joalheiro'),
(200, E'Vendedor de mascaras'),
(201, E'Contador'),
(202, E'Guarda-Costas de Hinata'),
(203, E'Estrategista do Pais dos Passaros'),
(204, E'Sapo Mensageiro'),
(205, E'Capitao da Policia de Konoha'),
(206, E'Cantora'),
(207, E'Guardiao da Ilha Tartaruga'),
(208, E'Lider da Vila Jomae'),
(209, E'Assistente do Raikage'),
(210, E'Co-fundador de Konohagakure'),
(211, E'Lider do cla Uchiha Anterior'),
(212, E'Vendedora de Ervas Medicinais'),
(213, E'Diretor de Filme'),
(214, E'Chefe da Aldeia'),
(215, E'Espiao'),
(216, E'Garcom'),
(217, E'Capitao da Anbu'),
(218, E'Guarda Pessoal'),
(219, E'General'),
(220, E'Comandante da Quinta Divisao das Forcas Aliadas Shinobi'),
(221, E'Desenvolvedora de projetos'),
(222, E'Ministro Antigo'),
(223, E'Sacerdotisa'),
(224, E'Espiao de Otogakure'),
(225, E'Guarda-Costas do Mizukage'),
(226, E'Chefe do Esquadrao de Criptograma'),
(227, E'Instrutor da Academia'),
(228, E'Guia'),
(229, E'Mestre do Castelo Hozuki e Guardiao da Caixa da Felicidade Suprema'),
(230, E'Comandante do Castelo Hozuki'),
(231, E'Espiao da Akatsuki'),
(232, E'Subordinado de Sasori'),
(233, E'Lider do Cla Kurama'),
(234, E'Agricultora'),
(235, E'Lider da Vila Nadeshiko'),
(236, E'Médico'),
(237, E'Lider da Akatsuki'),
(238, E'Empregada'),
(239, E'Lojista'),
(240, E'Chefe do Ninneko'),
(241, E'Capitao do Pais do Céu'),
(242, E'Cuidadora do Orfanato de Konoha'),
(243, E'Capita da Corpo Médico de Konoha'),
(244, E'Antiga Anbu Raiz'),
(245, E'Lider Secreto de Kirigakure'),
(246, E'Guarda-costas do Raikage'),
(247, E'Fundador e Lider de Otogakure'),
(248, E'Ladrao-nobre'),
(249, E'Lider da Vila'),
(250, E'Lider do cla Kaguya'),
(251, E'Assassino'),
(252, E'Chefe da Familia Kurosuki'),
(253, E'Aprendiz de Cozinheiro'),
(254, E'Lider do cla Kazekage[2]'),
(255, E'Empregado de pousada'),
(256, E'Examinador dos Exames Chunin'),
(257, E'Investigador da Policia de Konoha'),
(258, E'Cantor de Enka'),
(259, E'Pretendente a Daimyo'),
(260, E'Comerciante'),
(261, E'Instrutor dos Exames Chunin'),
(262, E'Diretor da Anbu'),
(263, E'Fundadora e Diretora da Clinica Infantil de Assistência Médica Mental do Hospital de Konoha[11]'),
(264, E'Assistente pessoal de Koyuki Kazahana'),
(265, E'Chefe'),
(266, E'Cuteleiro'),
(267, E'Corretor de Empréstimos'),
(268, E'Lider de Takigakure'),
(269, E'Decodificadora'),
(270, E'Chefe do Cla Nara'),
(271, E'Herdeiro de Veados'),
(272, E'Jonin Comandante'),
(273, E'Estrategista Chefe das Forcas Aliadas Shinobi'),
(274, E'Representante da Quarta Divisao das Forcas Aliadas Shinobi'),
(275, E'Conselheiro do Sétimo Hokage[8]'),
(276, E'Planejador para a Uniao Shinobi'),
(277, E'Lider do Cla Nara'),
(278, E'Sapa Ancia'),
(279, E'Jardineiro'),
(280, E'Fabricante de Panelas'),
(281, E'Instrutor da Academia[6]'),
(282, E'Lider do Grupo de Magaki'),
(283, E'Oficial Militar'),
(284, E'Secretaria particular da Hokage[4]'),
(285, E'Capita da Divisão de Suporte Médico e Logistico das Forcas Aliadas Shinobi'),
(286, E'Lider dos Bandidos Mujina'),
(287, E'Aprendiz de Io'),
(288, E'Treinador de Shibuki'),
(289, E'Protetor dos esconderijos de Orochimaru[3]'),
(290, E'Professora da Academia Ninja'),
(291, E'Rainha de Roran'),
(292, E'Guarda da Patrulha da Fronteira'),
(293, E'Guarda-Costas de Shion'),
(294, E'Guarda-costas'),
(295, E'Carteiro'),
(296, E'Embaixadora'),
(297, E'Instrutora dos Exames Chunin'),
(298, E'Imperador do Pais dos Ancestrais'),
(299, E'Proprietaria de uma Loja de Ferramentas Ninjas'),
(300, E'Politico'),
(301, E'Ajudante do Pais da Água'),
(302, E'Cozinheiro'),
(303, E'Dono de um estabelecimento'),
(304, E'Guardia de Shizuka'),
(305, E'Guardiao do Monte Katsuragi'),
(306, E'Ornitólogo'),
(307, E'Dona de casa'),
(308, E'Lider da Oinin'),
(309, E'Capitao da Policia'),
(310, E'Ninken'),
(311, E'Guarda-costas de Gato Mercenario'),
(312, E'Fundador e lider da Akatsuki'),
(313, E'Herdeira do Cla Kurama'),
(314, E'Mordomo do daimyo'),
(315, E'Lider dos lutadores de Sumô'),
(316, E'Guarda-Costas do Daimyo'),
(317, E'Mestre de Troca de Recompensas');

