INSERT INTO `Ninja` (`id`, `name`, `birthdate`, `specie`, `status`, `sex`, `bloodType`, `ninjaRegistration`, `academyGradAge`, `chuninPromAge`) VALUES
(623, 'Koyuki Kazahana', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(624, 'Kozuchi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(625, 'Kuchiyose Final', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(626, 'Kujaku', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(627, 'Kumade Toriichi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(628, 'Kumadori', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(629, 'Kunihisa', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(630, 'Kunijirō', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(631, 'Kunoichi de Iwa', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(632, 'Kunugi Mokume', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(633, 'Kurama', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(634, 'Kurenai Yūhi', '11 de junho', 'Humano', NULL, 'Feminino', 'AB', '010881', '9', '13'),
(635, 'Kurobachi', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(636, 'Kuroma Tatsushiro', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(637, 'Kuromaru', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(638, 'Kurotsuchi', '6 de setembro', 'Humano', NULL, 'Feminino', 'O', 'IW-09011', NULL, NULL),
(639, 'Kurozuka', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(640, 'Kusabi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(641, 'Kushimaru Kuriarare', '18 de Novembro', 'Humano', 'Morto', 'Masculino', 'AB', NULL, NULL, NULL),
(642, 'Kushina Uzumaki', '10 de julho', 'Humano', 'Morta', 'Feminino', 'B', NULL, NULL, NULL),
(643, 'Kussaku', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(644, 'Kusuma', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(645, 'Kusuna', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(646, 'Kusune', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(647, 'Kusushi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(648, 'Kyūroku Wagarashi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(649, 'Kyūsuke', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(650, 'Kyōya', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(651, 'Kyodaigumo', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(652, 'Kyohō Fuefuki', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(653, 'Lagarto Mensageiro', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(654, 'Lando', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(655, 'Leo', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(656, 'Leão-Tartaruga', NULL, 'Humano', 'Presumivelmente Morto', NULL, NULL, NULL, NULL, NULL),
(657, 'Leão do Pavor', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(658, 'Lily Himeno', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(659, 'Log', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(660, 'Lula Gigante', NULL, 'Humano', 'Morta', NULL, NULL, NULL, NULL, NULL),
(661, 'Lâmina das Trevas', NULL, 'Humano', NULL, 'Masculino', 'AB', NULL, NULL, NULL),
(662, 'Líder da Vila Jōmae', NULL, 'Humano', 'Desconhecido', 'Masculino', NULL, NULL, NULL, NULL),
(663, 'Mū', '6 de Junho', 'Humano', 'Morto', 'Masculino', 'O', NULL, NULL, NULL),
(664, 'Mōryō', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(665, 'Mabui', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(666, 'Madame Shijimi', '24 de dezembro', 'Humano', 'Viva', 'Feminino', 'O', NULL, NULL, NULL),
(667, 'Madara Uchiha', '24 de Dezembro', 'Humano', 'Morto', 'Masculino', 'O', NULL, NULL, NULL),
(668, 'Maen Nara', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(669, 'Magire', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(670, 'Magire Kakuremino', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(671, 'Mahiru', '18 de Junho', 'Humano', 'Morto', 'Masculino', 'AB', 'IW-06531', NULL, NULL),
(672, 'Mai Kagetsu', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(673, 'Makaro Akimichi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(674, 'Maki', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(675, 'Makinami Senka', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(676, 'Makino', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(677, 'Malice', NULL, 'Humano', 'Falecida', 'Feminino', NULL, NULL, NULL, NULL),
(678, 'Mamushi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(679, 'Manabu Akado', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(680, 'Manda', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(681, 'Manda II', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(682, 'Mangetsu Hōzuki', '15 de Fevereiro', 'Humano', 'Morto', 'Masculino', 'AB', NULL, NULL, NULL),
(683, 'Mari', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(684, 'Marionete Mestre', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(685, 'Marisco Gigante', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(686, 'Maroi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(687, 'Maruten Akimichi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(688, 'Masako', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(689, 'Matatabi', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(690, 'Matsu', '16 de Maio', 'Humano', NULL, 'Masculino', 'B', NULL, NULL, NULL),
(691, 'Matsuba', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(692, 'Matsuri', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(693, 'Matsuri (Konoha)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(694, 'Mawashi Dokuraku', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(695, 'Mebuki Haruno', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(696, 'Mecha-Kurama', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(697, 'Mecha-Naruto', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(698, 'Mei Terumī', '21 de Maio', 'Humano', NULL, 'Feminino', 'AB', NULL, NULL, NULL),
(699, 'Meizu', '6 de Junho', 'Humano', NULL, 'Masculino', 'B', NULL, '12', '18'),
(700, 'Membro Anbu Mascarado de Javali', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(701, 'Membro Anbu Mascarado de Pássaro', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(702, 'Membro Anbu Mascarado de Raposa', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(703, 'Membro Anbu Mascarado de Tigre', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(704, 'Membro Anbu Mascarado de Águia', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(705, 'Menō', NULL, 'Humano', 'Falecida', 'Feminino', NULL, NULL, NULL, NULL),
(706, 'Menma (anime)', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(707, 'Menma Namikaze', '10 de Outubro', 'Humano', NULL, 'Masculino', 'B', '012607', '12 anos', NULL),
(708, 'Menma Uzumaki', 'Outubro 10', 'Humano', NULL, 'Masculino', 'B', NULL, NULL, NULL),
(709, 'Metal Lee', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(710, 'Metoro Konjiki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(711, 'Mezu', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(712, 'Mibuna', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(713, 'Michiru Tsuki', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(714, 'Michizō Manaka', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(715, 'Michy', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(716, 'Midare', '7 de Maio', 'Humano', NULL, 'Masculino', 'A', 'R4-059', NULL, NULL),
(717, 'Midori', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(718, 'Mifune', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(719, 'Migaki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(720, 'Might Duy', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(721, 'Might Guy', '1 de Janeiro', 'Humano', NULL, 'Masculino', 'B', '010252', '7 anos', '11 anos'),
(722, 'Miina', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(723, 'Mijin', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(724, 'Mikazuki', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(725, 'Mikazuki Amaashi', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(726, 'Mikoshi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(727, 'Mikoto Uchiha', '1 de Junho', 'Humano', 'Morta', 'Feminino', 'A', '005348', NULL, NULL),
(728, 'Minato Namikaze', '25 de janeiro', 'Humano', 'Morto', 'Masculino', 'B', NULL, '10', NULL),
(729, 'Ministro Mal do Daimyō do País do Chá', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(730, 'Minoichi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(731, 'Minoji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(732, 'Mirai Sarutobi', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(733, 'Miroku', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(734, 'Miru', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(735, 'Misumi Tsurugi', '30 de Novembro', 'Humano', NULL, 'Masculino', 'A', '011981', NULL, NULL),
(736, 'Misuno', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(737, 'Mitate', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(738, 'Mito Uzumaki', '3 de Maio', 'Humano', 'Morta', 'Feminino', 'O', NULL, NULL, NULL),
(739, 'Mitoku', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(740, 'Mitsuki', '25 de Julho', 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(741, 'Mitsuo', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(742, 'Mizore Fuyukuma', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(743, 'Mizuki', NULL, 'Humano', 'Incapacitado', 'Masculino', 'AB', '011141', NULL, NULL),
(744, 'Mizunoe', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(745, 'Mizunoto', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(746, 'Mizura', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(747, 'Mo', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(748, 'Moegi Kazamatsuri', '8 de junho', 'Humano', NULL, 'Feminino', 'A', NULL, '12', NULL),
(749, 'Moguranmaru', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(750, 'Mogusa', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(751, 'Momiji (País dos Vegetais)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(752, 'Momiji (Tanzaku)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(753, 'Momo', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(754, 'Momo (ninneko)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(755, 'Momoshiki Ōtsutsuki', NULL, 'Humano', 'Incapacitado', 'Masculino', NULL, NULL, NULL, NULL),
(756, 'Mondai', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(757, 'Monga', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(758, 'Monju', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(759, 'Monte Verde', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(760, 'Monzaemon Chikamatsu', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(761, 'Morio', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(762, 'Moroi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(763, 'Motoi', '16 de Outubro', 'Humano', NULL, 'Masculino', 'B', 'CL4803', NULL, NULL),
(764, 'Mozuku', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(765, 'Mozuku (Criminoso)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(766, 'Mubi', '15 de Novembro', 'Humano', NULL, 'Masculino', 'AB', 'R1-128', NULL, NULL),
(767, 'Mugino', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(768, 'Mui', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(769, 'Mujō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(770, 'Mujin', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(771, 'Mukade', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(772, 'Mukade (filme)', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(773, 'Mukai Kohinata', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(774, 'Muku', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(775, 'Murakumo Kurama', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(776, 'Murasame', NULL, 'Humano', 'Incapacitado', 'Masculino', NULL, NULL, NULL, NULL),
(777, 'Musai', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(778, 'Muta Aburame', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(779, 'Muyami', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(780, 'Mãe de Chōji', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(781, 'Mãe de Haku', NULL, 'Humano', 'Falecida', 'Feminino', NULL, NULL, NULL, NULL),
(782, 'Mãe de Hinata e Hanabi', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(783, 'Mãe de Ino', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(784, 'Mãe de Karin', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(785, 'Mãe de Ryōgi', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(786, 'Mãe de Sasori', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(787, 'Mãe de Shizuka', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(788, 'Mãe de Yūkimaru', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(789, 'Médico de Fukai', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(790, 'Nadare Rōga', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(791, 'Nae', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(792, 'Nagare', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(793, 'Nagato', '19 de setembro', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(794, 'Naho', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(795, 'Naka Uchiha', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(796, 'Namida Suzumeno', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(797, 'Nan', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(798, 'Nanafushi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(799, 'Nangō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(800, 'Naori Uchiha', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(801, 'Naruto Musasabi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(802, 'Naruto Uzumaki', '10 de outubro', 'Humano', 'Incapacitado Boruto', 'Masculino', 'B', '012607', '12', NULL),
(803, 'Natori', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(804, 'Natsu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(805, 'Natsu Hyūga', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(806, 'Natsuhi', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(807, 'Nauma', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(808, 'Nawaki', '09 de Agosto', 'Humano', 'Morto', 'Masculino', 'O', '005350', NULL, NULL),
(809, 'Neji Hyūga', '3 de julho', 'Humano', 'Morto', 'Masculino', 'O', '012587', '12', '15'),
(810, 'Nejiri', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(811, 'Nekobaa', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(812, 'Nekomata', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(813, 'Nemui', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(814, 'Nerugui', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(815, 'Neta do Chefe de Aldeia', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(816, 'Ni', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(817, 'Nigai', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(818, 'Ninja Capitão do Céu', NULL, 'Humano', 'Desconhecido', 'Masculino', NULL, NULL, NULL, NULL),
(819, 'Ninja Chefe de Kumogakure', '2 de Abril', 'Humano', NULL, 'Masculino', 'O', NULL, NULL, NULL),
(820, 'Ninkame', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(821, 'Nishi', '11 de Agosto', 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(822, 'Nitora Take', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(823, 'Nobori', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(824, 'Nonō Yakushi', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(825, 'Nonota', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(826, 'Nue', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(827, 'Nurari', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(828, 'Nurui', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(829, 'Obito Uchiha', '10 de fevereiro', 'Humano', 'Morto', 'Masculino', 'O', '010886', '9', '11'),
(830, 'Oboro', '20 de Dezembro', 'Humano', NULL, 'Masculino', 'A', 'R1-127', NULL, NULL),
(831, 'Okami', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(832, 'Okisuke', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(833, 'Oko', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(834, 'Okyō', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(835, 'Olho das Chamas', NULL, 'Humano', NULL, 'Masculino', 'AB', NULL, NULL, NULL),
(836, 'Omoi', '26 de Dezembro', 'Humano', NULL, 'Masculino', 'AB', 'CL6305', NULL, NULL),
(837, 'Onbu', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(838, 'Orochimaru', '27 de outubro', 'Humano', NULL, 'Desconhecido', 'B', '002300', '6 anos', NULL),
(839, 'Osoi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(840, 'Otoha', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(841, 'Otokaze', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(842, 'Oyone', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(843, 'Pac Lee', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(844, 'Pai de Akane', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(845, 'Pai de Haku', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(846, 'Pai de Ryōgi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(847, 'Pai de Sasori', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(848, 'Pai de Shibuki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(849, 'Pai de Tsukino', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(850, 'Pai de Yūsuke', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(851, 'Pais de Konohamaru', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(852, 'Pakkun', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(853, 'Pakura', '9 de Abril', 'Humano', 'Morta', 'Feminino', 'A', NULL, NULL, NULL),
(854, 'Panda Gigante', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(855, 'Parceiro de Sekiei', NULL, 'Humano', 'Desabilitado', 'Masculino', NULL, NULL, NULL, NULL),
(856, 'Patriarca do Clã Ōtsutsuki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(857, 'Patriarca do Clã Kaguya', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(858, 'País da Geleia de Feijão', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(859, 'País do Céu', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(860, 'País do Mel', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(861, 'Personagens (Filler)', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(862, 'Personagens (Filme)', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(863, 'Personagens (Game)', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(864, 'Pochi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(865, 'Ponta', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(866, 'Portador da Hiramekarei', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(867, 'Potcha', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(868, 'Primeiro Caminho Animal (personagem)', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(869, 'Primeiro Hoshikage', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(870, 'Punho de Pedra', NULL, 'Humano', NULL, 'Masculino', 'B', NULL, NULL, NULL),
(871, 'Pássaro Ahō', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(872, 'Pássaro Bico-de-Broca Gigante', NULL, 'Humano', 'Presumivelmente morto', NULL, NULL, NULL, NULL, NULL),
(873, 'Pássaro de San', NULL, 'Humano', 'Presumido Falecido', NULL, NULL, NULL, NULL, NULL),
(874, 'Quimera Gigante', NULL, 'Humano', 'Morto Provavelmente', NULL, NULL, NULL, NULL, NULL),
(875, 'Rō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(876, 'Rōen', NULL, 'Humano', 'Incapacitado', NULL, NULL, NULL, NULL, NULL),
(877, 'Rōshi', '4 de Junho', 'Humano', 'Morto', 'Masculino', 'B', NULL, NULL, NULL),
(878, 'Rahyō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(879, 'Rai Uchiha', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(880, 'Raidō Namiashi', '28 de Agosto', 'Humano', NULL, 'Masculino', 'AB', '009717', NULL, NULL),
(881, 'Raiga Kurosuki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(882, 'Raijin', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(883, 'Raimei', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(884, 'Raiz', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(885, 'Ran', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(886, 'Ran (kunoichi)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(887, 'Ranka', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(888, 'Ranke', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(889, 'Ranmaru', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(890, 'Rasa', '29 de Marco', 'Humano', 'Morto', 'Masculino', 'A', '28-115', NULL, NULL),
(891, 'Rashii', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(892, 'Rei Concha', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(893, 'Rei Macaco: Enma', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(894, 'Rei do Inferno', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(895, 'Reishi Kodon', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(896, 'Reki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(897, 'Remon Yoimura', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(898, 'Renga', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(899, 'Renga Kokubō', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(900, 'Renge Momoashi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(901, 'Reto', '27 de Junho', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(902, 'Riichi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(903, 'Riichi (ninja)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(904, 'Rikumaru', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(905, 'Rin Nohara', '15 de Novembro', 'Humano', 'Morta', 'Feminino', 'A', '010885', '9', '11'),
(906, 'Rinji', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(907, 'Rinoceronte Gigante', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(908, 'Rock Lee', '27 de novembro', 'Humano', NULL, 'Masculino', 'A', '012561', '12', '15'),
(909, 'Rock Lee (Mundo Genjutsu)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(910, 'Rokkaku Ryūdōin', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(911, 'Rokusuke', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(912, 'Ruiga', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(913, 'Ruka', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(914, 'Ryūase', NULL, 'Humano', 'Desconhecido', NULL, NULL, NULL, NULL, NULL),
(915, 'Ryūgan', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(916, 'Ryōgi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(917, 'Ryōkan', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(918, 'Ryūki', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(919, 'Ryūsa', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(920, 'Ryōshu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(921, 'Ryūsui', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(922, 'Ryūzetsu', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(923, 'Ryuka Tenrō', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(924, 'Sāra', NULL, 'Humano', 'Desconhecido', 'Feminino', NULL, NULL, NULL, NULL),
(925, 'Sēramu', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(926, 'Sōsetsu Kazahana', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(927, 'Sōta', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(928, 'Sōzu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(929, 'Saō', NULL, 'Humano', 'Incapacitado', 'Masculino', NULL, NULL, NULL, NULL),
(930, 'Sabiru', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(931, 'Sabu', '4 de Outubro', 'Humano', NULL, 'Masculino', 'O', NULL, NULL, NULL),
(932, 'Sada', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(933, 'Sadai', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(934, 'Sadoru', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(935, 'Sagan', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(936, 'Sagi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(937, 'Sagiri', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(938, 'Sai', '25 de movembro', 'Humano', NULL, 'Masculino', 'A', '012420', '9', '10'),
(939, 'Saiken', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(940, 'Saisu Kamano', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(941, 'Sajō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(942, 'Sajin', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(943, 'Sajin (Genin)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(944, 'Sakon e Ukon', '20 de Junho', 'Humano', 'Mortos', 'Masculino', NULL, NULL, NULL, NULL),
(945, 'Sakumo Hatake', '3 de Setembro', 'Humano', 'Morto', 'Masculino', 'O', NULL, NULL, NULL),
(946, 'Sakura Haruno', '28 de marco', 'Humano', NULL, 'Feminino', 'O', '012601', '12', '14'),
(947, 'Samidare', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(948, 'Samidare Amaashi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(949, 'Samo', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(950, 'Samui', '7 de Janeiro', 'Humano', NULL, 'Feminino', 'A', 'CL5570', NULL, NULL),
(951, 'San', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(952, 'Sana', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(953, 'Sandayū Asama', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(954, 'Sangorō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(955, 'Sanshō', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(956, 'Santa Yamanaka', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(957, 'Sarada Uchiha', '31 de Marco', 'Humano', NULL, 'Feminino', NULL, NULL, '11 anos', NULL),
(958, 'Sarai', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(959, 'Sari', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(960, 'Sasame Fūma', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(961, 'Sasami', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(962, 'Sasori', '8 de novembro', 'Humano', 'Morto', 'Masculino', 'AB', '33-001', '7', '8'),
(963, 'Sasuke Sarutobi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(964, 'Sasuke Uchiha', '23 de julho', 'Humano', NULL, 'Masculino', 'AB', '012606', '12', NULL),
(965, 'Sasuke Uchiha (Mundo Genjutsu)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(966, 'Satō', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(967, 'Satchi', NULL, 'Humano', 'Possivelmente Morto', NULL, NULL, NULL, NULL, NULL),
(968, 'Satetsu (Personagem)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(969, 'Satori', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(970, 'Saya', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(971, 'Sazanami', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(972, 'Sazanami Senka', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(973, 'Segunda Divisão', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(974, 'Segurança de Fronteira', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(975, 'Seimei', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(976, 'Seito', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(977, 'Sekiei', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(978, 'Sekiei (espectador)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(979, 'Sekka', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(980, 'Sekki', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(981, 'Sen', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(982, 'Sensei de Kabuto', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(983, 'Sensei de Kumo', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(984, 'Sensei de Suna', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(985, 'Senta', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(986, 'Sentoki', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(987, 'Setsuna', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(988, 'Setsuna Uchiha', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(989, 'Shū', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(990, 'Shū (lorde)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(991, 'Shōseki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(992, 'Shabadaba', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(993, 'Shamon', '12 de Marco', 'Humano', 'Morto', 'Masculino', 'O', NULL, NULL, NULL),
(994, 'Shiba', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(995, 'Shiba (Kusagakure)', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(996, 'Shibi Aburame', '07 de Setembro', 'Humano', NULL, 'Masculino', 'A', '005480', NULL, NULL),
(997, 'Shibire', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(998, 'Shibito Azuma', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(999, 'Shibuki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1000, 'Shigezane', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1001, 'Shigure', '11 de Fevereiro', 'Humano', NULL, 'Masculino', 'B', 'R1-115', NULL, NULL),
(1002, 'Shiho', '18 de Junho', 'Humano', NULL, 'Feminino', 'AB', NULL, NULL, NULL),
(1003, 'Shiin', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1004, 'Shijima', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1005, 'Shikadai Nara', '23 de Setembro', 'Humano', NULL, 'Masculino', NULL, NULL, '11 anos', '12 anos'),
(1006, 'Shikaku Nara', '15 de julho', 'Humano', 'Morto', 'Masculino', 'B', '005491', NULL, NULL),
(1007, 'Shikamaru Nara', '22 de Setembro', 'Humano', NULL, 'Masculino', 'AB', '012611', '12', '12'),
(1008, 'Shikazo', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1009, 'Shikuro Aburame', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1010, 'Shima', '26 de Agosto', 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(1011, 'Shimeji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1012, 'Shimo', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1013, 'Shimon Hijiri', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1014, 'Shin\'emon', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1015, 'Shin', '6 de Setembro', 'Humano', 'Morto', 'Masculino', 'B', NULL, NULL, NULL),
(1016, 'Shin Uchiha', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1017, 'Shinayakana', NULL, 'Humano', 'Presumivelmente Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1018, 'Shinga', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1019, 'Shinigami', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1020, 'Shinki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1021, 'Shinko Inari', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1022, 'Shinku Yūhi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1023, 'Shinnō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1024, 'Shino Aburame', '23 de janeiro', 'Humano', NULL, 'Masculino', 'AB', '012618', '12', '14'),
(1025, 'Shino Aburame (Mundo Genjutsu)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1026, 'Shinobu Mibu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1027, 'Shinta', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1028, 'Shio', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(1029, 'Shion', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(1030, 'Shiore', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1031, 'Shira', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1032, 'Shiranami', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1033, 'Shiro', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(1034, 'Shiro (Livro de Jiraiya)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1035, 'Shiromari', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1036, 'Shisō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1037, 'Shiseru', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1038, 'Shishio', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1039, 'Shisui Uchiha', '19 de outubro', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(1040, 'Shitō Akimichi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1041, 'Shizuka', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1042, 'Shizuku', NULL, 'Humano', 'Falecida', 'Feminino', NULL, NULL, NULL, NULL),
(1043, 'Shizuma Hoshigaki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1044, 'Shizune', '18 de Novembro', 'Humano', NULL, 'Feminino', 'A', '010800', '9', '13'),
(1045, 'Shojoji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1046, 'Shukaku', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1047, 'Shun', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1048, 'Shura', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1049, 'Son Gokū', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1050, 'Sora', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1051, 'Sora (órfã)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1052, 'Suguro', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1053, 'Suien', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1054, 'Suigetsu Hōzuki', '18 de Fevereiro', 'Humano', NULL, 'Masculino', 'B', NULL, NULL, NULL),
(1055, 'Suika', NULL, 'Humano', 'Morto Presumivelmente', 'Masculino', NULL, NULL, NULL, NULL),
(1056, 'Suika Kannonji', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(1057, 'Suiko', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1058, 'Suiren', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1059, 'Suiren (Kiri)', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(1060, 'Suiu', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1061, 'Sukeza', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1062, 'Sukima', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1063, 'Sukui', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1064, 'Sukune', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(1065, 'Sumaru', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1066, 'Sumashi', NULL, 'Humano', 'Morto Provavelmente', 'Masculino', NULL, NULL, NULL, NULL),
(1067, 'Sumire', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1068, 'Sumire Kakei', '12 de junho', 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1069, 'Suname', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1070, 'Susuki', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(1071, 'Suzaku (ministro)', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1072, 'Suzaku Nara', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1073, 'Suzu', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1074, 'Suzume', '19 de outubro', 'Humano', NULL, 'Feminino', NULL, '009902', NULL, NULL),
(1075, 'Suzumebachi', NULL, 'Humano', 'Presumivelmente Morta', 'Feminino', NULL, NULL, NULL, NULL),
(1076, 'Suzuran', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1077, 'Tadaichi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1078, 'Tagitsuhime', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(1079, 'Tagorihime', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(1080, 'Taiga', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1081, 'Taiko Uchiha', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1082, 'Taisa Amagiri', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1083, 'Taiseki', '10 de Marco', 'Humano', 'Morto', 'Masculino', 'O', 'IW-06225', NULL, NULL),
(1084, 'Taizō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1085, 'Taji', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(1086, 'Tajiki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1087, 'Tajima Uchiha', '28 de Marco', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(1088, 'Taka', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1089, 'Takamaru', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1090, 'Takanami Senka', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1091, 'Takemaru', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1092, 'Takishi', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(1093, 'Taku', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1094, 'Tamae', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1095, 'Tamaki', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1096, 'Tamanduá Gigante', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1097, 'Tamao', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1098, 'Tami', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1099, 'Tango', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1100, 'Tanishi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1101, 'Tanuki Shigaraki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1102, 'Tanzō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1103, 'Tarō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1104, 'Taruho', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1105, 'Tarui', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1106, 'Tatewaki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1107, 'Tatsuji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1108, 'Tatsuma Aburame', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1109, 'Tatsumi', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1110, 'Tayori Kuroyagi', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1111, 'Tayuya', '15 de Fevereiro', 'Humano', 'Morta', 'Feminino', 'A', NULL, NULL, NULL),
(1112, 'Tazuna', '5 de Abril', 'Humano', NULL, 'Masculino', 'A', NULL, NULL, NULL),
(1113, 'Teguse', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1114, 'Tekka Uchiha', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(1115, 'Tekuno Kanden', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1116, 'Temari', '23 de agosto', 'Humano', NULL, 'Feminino', 'O', '53-004', '12 Anos', '17 anos'),
(1117, 'Temui', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1118, 'Temujin', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1119, 'Tenga', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1120, 'Tenji', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1121, 'Tenma Izumo', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1122, 'Tenma Kodon', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1123, 'Tentō Madoka', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1124, 'Tenten', '9 de marco', 'Humano', NULL, 'Feminino', 'B', '012573', '12', '15'),
(1125, 'Tenzō (Clã Iburi)', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1126, 'Tenzen', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1127, 'Tenzen Daikoku', NULL, 'Humano', 'Presumivelmente Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1128, 'Tera', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1129, 'Terai', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1130, 'Terceira Divisão', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1131, 'Terceiro Hoshikage', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1132, 'Terceiro Kazekage', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1133, 'Terceiro Mizukage', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1134, 'Terubō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1135, 'Tessa', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(1136, 'Tessen Togeito', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1137, 'Tetsu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1138, 'Tetsu Hyūga', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1139, 'Tetsuru', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1140, 'Teuchi', '10 de agosto', 'Humano', NULL, 'Masculino', 'O', NULL, NULL, NULL),
(1141, 'Teyaki Uchiha', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1142, 'Tezuna', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1143, 'Time 15', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1144, 'Time 2', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1145, 'Time 25', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1146, 'Time 40', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1147, 'Time 5', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1148, 'Time Asuma', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1149, 'Time Bandō', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1150, 'Time Dosu', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1151, 'Time Ebisu', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1152, 'Time Ganryū', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1153, 'Time Guren', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1154, 'Time Guy', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1155, 'Time Hiruko', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1156, 'Time Jiraiya', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1157, 'Time Kakashi', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1158, 'Time Karin', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1159, 'Time Komugi', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1160, 'Time Kurenai', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1161, 'Time Minato', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1162, 'Time Moegi', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1163, 'Time Ro', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1164, 'Time Samui', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1165, 'Time Shū', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1166, 'Time Shibire', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1167, 'Time Shigure', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1168, 'Time Shinki', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1169, 'Time Shira', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1170, 'Time Shisui', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1171, 'Time Suien', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1172, 'Time Tobirama', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1173, 'Time Yurui', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1174, 'Time de Análise', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1175, 'Time de Barreira de Konoha', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1176, 'Time de Captura do Hachibi', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1177, 'Time de Comunicações', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1178, 'Time de Genin de Kabuto', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1179, 'Time de Infiltração e Reconhecimento', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1180, 'Time de Liberação de Vento', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1181, 'Time de Patrulha da Fronteira do Norte', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1182, 'Time de Procura a Orochimaru', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1183, 'Time de Resgate de Sasuke', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1184, 'Time de Selamento', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1185, 'Time de Três Homens de Dotō', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1186, 'Tobi (Zetsu)', NULL, 'Humano', 'Morto', 'Masculino', 'B', NULL, NULL, NULL),
(1187, 'Tobimaru', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1188, 'Tobio', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1189, 'Tobirama Senju', '19 de fevereiro', 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1190, 'Todoroki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1191, 'Tofu', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1192, 'Tokara', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1193, 'Toki', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1194, 'Toki (Shinobazu)', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1195, 'Tokiwa', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1196, 'Ūhei', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1197, 'Ōkei', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1198, 'Ōnoki', '8 de outubro', 'Humano', 'Morto', 'Masculino', 'O', NULL, NULL, NULL),
(1199, 'Ōtora', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1200, 'Ōwashi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1201, 'Tōbei Kagetsu', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1202, 'Tōfu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1203, 'Tōjūrō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1204, 'Tōka Senju', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(1205, 'Tōu', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(1206, 'Tokuma Hyūga', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1207, 'Tomari', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1208, 'Tomaru', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1209, 'Tomaru Minakura', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1210, 'Tonbee', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1211, 'Tonbo Tobitake', '4 de Abril', 'Humano', NULL, 'Masculino', 'A', '010997', NULL, NULL),
(1212, 'Toneri Ōtsutsuki', NULL, 'Humano', 'Incapacitado', 'Masculino', NULL, NULL, NULL, NULL),
(1213, 'Tonton', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1214, 'Tora (Anbu)', NULL, 'Humano', 'Presumivelmente Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1215, 'Tora (gato)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1216, 'Torifu Akimichi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1217, 'Toroi', '6 de Outubro', 'Humano', 'Morto', 'Masculino', 'O', NULL, NULL, NULL),
(1218, 'Toroi (Genin)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1219, 'Torune Aburame', NULL, 'Humano', 'Morto', 'Masculino', 'O', '012360', NULL, NULL),
(1220, 'Tosaka', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1221, 'Touro Gigante', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(1222, 'Toyosa', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(1223, 'Três Cobras Gigantes', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1224, 'Três Irmãos', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1225, 'Três Irmãos Haimaru', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1226, 'Três Irmãos da Areia', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1227, 'Tsubaki (anime)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1228, 'Tsubaki (mãe)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1229, 'Tsubaki Kurogane', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1230, 'Tsubusa', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1231, 'Tsuchino', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1232, 'Tsuchinoe', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1233, 'Tsuchinoto', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1234, 'Tsukado', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1235, 'Tsukiko Kagetsu', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1236, 'Tsukino', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1237, 'Tsukiyo', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1238, 'Tsukune', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1239, 'Tsukushi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1240, 'Tsume Inuzuka', '12 de Agosto', 'Humano', NULL, 'Feminino', 'B', NULL, NULL, NULL),
(1241, 'Tsunade', '2 de Agosto', 'Humano', NULL, 'Feminino', 'B', '002302', '6 anos', NULL),
(1242, 'Tsunami', '4 de Maio', 'Humano', NULL, 'Feminino', 'A', NULL, NULL, NULL),
(1243, 'Tsuru Itoi', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1244, 'Tsurugi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL);
