INSERT INTO "Ninja" ("id", "name", "birthdate", "specie", "status", "sex", "bloodType", "ninjaRegistration", "academyGradAge", "chuninPromAge") VALUES
(623, E'Koyuki Kazahana', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(624, E'Kozuchi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(625, E'Kuchiyose Final', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(626, E'Kujaku', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(627, E'Kumade Toriichi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(628, E'Kumadori', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(629, E'Kunihisa', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(630, E'Kunijirō', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(631, E'Kunoichi de Iwa', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(632, E'Kunugi Mokume', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(633, E'Kurama', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(634, E'Kurenai Yūhi', E'11 de junho', E'Humano', NULL, E'Feminino', E'AB', E'010881', E'9', E'13'),
(635, E'Kurobachi', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(636, E'Kuroma Tatsushiro', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(637, E'Kuromaru', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(638, E'Kurotsuchi', E'6 de setembro', E'Humano', NULL, E'Feminino', E'O', E'IW-09011', NULL, NULL),
(639, E'Kurozuka', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(640, E'Kusabi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(641, E'Kushimaru Kuriarare', E'18 de Novembro', E'Humano', E'Morto', E'Masculino', E'AB', NULL, NULL, NULL),
(642, E'Kushina Uzumaki', E'10 de julho', E'Humano', E'Morta', E'Feminino', E'B', NULL, NULL, NULL),
(643, E'Kussaku', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(644, E'Kusuma', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(645, E'Kusuna', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(646, E'Kusune', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(647, E'Kusushi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(648, E'Kyūroku Wagarashi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(649, E'Kyūsuke', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(650, E'Kyōya', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(651, E'Kyodaigumo', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(652, E'Kyohō Fuefuki', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(653, E'Lagarto Mensageiro', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(654, E'Lando', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(655, E'Leo', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(656, E'Leão-Tartaruga', NULL, E'Humano', E'Presumivelmente Morto', NULL, NULL, NULL, NULL, NULL),
(657, E'Leão do Pavor', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(658, E'Lily Himeno', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(659, E'Log', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(660, E'Lula Gigante', NULL, E'Humano', E'Morta', NULL, NULL, NULL, NULL, NULL),
(661, E'Lâmina das Trevas', NULL, E'Humano', NULL, E'Masculino', E'AB', NULL, NULL, NULL),
(662, E'Líder da Vila Jōmae', NULL, E'Humano', E'Desconhecido', E'Masculino', NULL, NULL, NULL, NULL),
(663, E'Mū', E'6 de Junho', E'Humano', E'Morto', E'Masculino', E'O', NULL, NULL, NULL),
(664, E'Mōryō', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(665, E'Mabui', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(666, E'Madame Shijimi', E'24 de dezembro', E'Humano', E'Viva', E'Feminino', E'O', NULL, NULL, NULL),
(667, E'Madara Uchiha', E'24 de Dezembro', E'Humano', E'Morto', E'Masculino', E'O', NULL, NULL, NULL),
(668, E'Maen Nara', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(669, E'Magire', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(670, E'Magire Kakuremino', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(671, E'Mahiru', E'18 de Junho', E'Humano', E'Morto', E'Masculino', E'AB', E'IW-06531', NULL, NULL),
(672, E'Mai Kagetsu', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(673, E'Makaro Akimichi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(674, E'Maki', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(675, E'Makinami Senka', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(676, E'Makino', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(677, E'Malice', NULL, E'Humano', E'Falecida', E'Feminino', NULL, NULL, NULL, NULL),
(678, E'Mamushi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(679, E'Manabu Akado', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(680, E'Manda', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(681, E'Manda II', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(682, E'Mangetsu Hōzuki', E'15 de Fevereiro', E'Humano', E'Morto', E'Masculino', E'AB', NULL, NULL, NULL),
(683, E'Mari', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(684, E'Marionete Mestre', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(685, E'Marisco Gigante', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(686, E'Maroi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(687, E'Maruten Akimichi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(688, E'Masako', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(689, E'Matatabi', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(690, E'Matsu', E'16 de Maio', E'Humano', NULL, E'Masculino', E'B', NULL, NULL, NULL),
(691, E'Matsuba', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(692, E'Matsuri', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(693, E'Matsuri (Konoha)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(694, E'Mawashi Dokuraku', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(695, E'Mebuki Haruno', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(696, E'Mecha-Kurama', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(697, E'Mecha-Naruto', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(698, E'Mei Terumī', E'21 de Maio', E'Humano', NULL, E'Feminino', E'AB', NULL, NULL, NULL),
(699, E'Meizu', E'6 de Junho', E'Humano', NULL, E'Masculino', E'B', NULL, E'12', E'18'),
(700, E'Membro Anbu Mascarado de Javali', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(701, E'Membro Anbu Mascarado de Pássaro', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(702, E'Membro Anbu Mascarado de Raposa', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(703, E'Membro Anbu Mascarado de Tigre', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(704, E'Membro Anbu Mascarado de Águia', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(705, E'Menō', NULL, E'Humano', E'Falecida', E'Feminino', NULL, NULL, NULL, NULL),
(706, E'Menma (anime)', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(707, E'Menma Namikaze', E'10 de Outubro', E'Humano', NULL, E'Masculino', E'B', E'012607', E'12 anos', NULL),
(708, E'Menma Uzumaki', E'Outubro 10', E'Humano', NULL, E'Masculino', E'B', NULL, NULL, NULL),
(709, E'Metal Lee', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(710, E'Metoro Konjiki', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(711, E'Mezu', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(712, E'Mibuna', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(713, E'Michiru Tsuki', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(714, E'Michizō Manaka', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(715, E'Michy', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(716, E'Midare', E'7 de Maio', E'Humano', NULL, E'Masculino', E'A', E'R4-059', NULL, NULL),
(717, E'Midori', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(718, E'Mifune', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(719, E'Migaki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(720, E'Might Duy', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(721, E'Might Guy', E'1 de Janeiro', E'Humano', NULL, E'Masculino', E'B', E'010252', E'7 anos', E'11 anos'),
(722, E'Miina', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(723, E'Mijin', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(724, E'Mikazuki', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(725, E'Mikazuki Amaashi', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(726, E'Mikoshi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(727, E'Mikoto Uchiha', E'1 de Junho', E'Humano', E'Morta', E'Feminino', E'A', E'005348', NULL, NULL),
(728, E'Minato Namikaze', E'25 de janeiro', E'Humano', E'Morto', E'Masculino', E'B', NULL, E'10', NULL),
(729, E'Ministro Mal do Daimyō do País do Chá', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(730, E'Minoichi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(731, E'Minoji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(732, E'Mirai Sarutobi', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(733, E'Miroku', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(734, E'Miru', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(735, E'Misumi Tsurugi', E'30 de Novembro', E'Humano', NULL, E'Masculino', E'A', E'011981', NULL, NULL),
(736, E'Misuno', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(737, E'Mitate', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(738, E'Mito Uzumaki', E'3 de Maio', E'Humano', E'Morta', E'Feminino', E'O', NULL, NULL, NULL),
(739, E'Mitoku', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(740, E'Mitsuki', E'25 de Julho', E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(741, E'Mitsuo', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(742, E'Mizore Fuyukuma', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(743, E'Mizuki', NULL, E'Humano', E'Incapacitado', E'Masculino', E'AB', E'011141', NULL, NULL),
(744, E'Mizunoe', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(745, E'Mizunoto', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(746, E'Mizura', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(747, E'Mo', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(748, E'Moegi Kazamatsuri', E'8 de junho', E'Humano', NULL, E'Feminino', E'A', NULL, E'12', NULL),
(749, E'Moguranmaru', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(750, E'Mogusa', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(751, E'Momiji (País dos Vegetais)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(752, E'Momiji (Tanzaku)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(753, E'Momo', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(754, E'Momo (ninneko)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(755, E'Momoshiki Ōtsutsuki', NULL, E'Humano', E'Incapacitado', E'Masculino', NULL, NULL, NULL, NULL),
(756, E'Mondai', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(757, E'Monga', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(758, E'Monju', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(759, E'Monte Verde', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(760, E'Monzaemon Chikamatsu', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(761, E'Morio', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(762, E'Moroi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(763, E'Motoi', E'16 de Outubro', E'Humano', NULL, E'Masculino', E'B', E'CL4803', NULL, NULL),
(764, E'Mozuku', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(765, E'Mozuku (Criminoso)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(766, E'Mubi', E'15 de Novembro', E'Humano', NULL, E'Masculino', E'AB', E'R1-128', NULL, NULL),
(767, E'Mugino', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(768, E'Mui', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(769, E'Mujō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(770, E'Mujin', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(771, E'Mukade', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(772, E'Mukade (filme)', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(773, E'Mukai Kohinata', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(774, E'Muku', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(775, E'Murakumo Kurama', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(776, E'Murasame', NULL, E'Humano', E'Incapacitado', E'Masculino', NULL, NULL, NULL, NULL),
(777, E'Musai', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(778, E'Muta Aburame', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(779, E'Muyami', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(780, E'Mãe de Chōji', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(781, E'Mãe de Haku', NULL, E'Humano', E'Falecida', E'Feminino', NULL, NULL, NULL, NULL),
(782, E'Mãe de Hinata e Hanabi', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(783, E'Mãe de Ino', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(784, E'Mãe de Karin', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(785, E'Mãe de Ryōgi', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(786, E'Mãe de Sasori', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(787, E'Mãe de Shizuka', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(788, E'Mãe de Yūkimaru', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(789, E'Médico de Fukai', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(790, E'Nadare Rōga', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(791, E'Nae', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(792, E'Nagare', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(793, E'Nagato', E'19 de setembro', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(794, E'Naho', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(795, E'Naka Uchiha', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(796, E'Namida Suzumeno', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(797, E'Nan', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(798, E'Nanafushi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(799, E'Nangō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(800, E'Naori Uchiha', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(801, E'Naruto Musasabi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(802, E'Naruto Uzumaki', E'10 de outubro', E'Humano', E'Incapacitado Boruto', E'Masculino', E'B', E'012607', E'12', NULL),
(803, E'Natori', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(804, E'Natsu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(805, E'Natsu Hyūga', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(806, E'Natsuhi', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(807, E'Nauma', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(808, E'Nawaki', E'09 de Agosto', E'Humano', E'Morto', E'Masculino', E'O', E'005350', NULL, NULL),
(809, E'Neji Hyūga', E'3 de julho', E'Humano', E'Morto', E'Masculino', E'O', E'012587', E'12', E'15'),
(810, E'Nejiri', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(811, E'Nekobaa', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(812, E'Nekomata', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(813, E'Nemui', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(814, E'Nerugui', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(815, E'Neta do Chefe de Aldeia', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(816, E'Ni', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(817, E'Nigai', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(818, E'Ninja Capitão do Céu', NULL, E'Humano', E'Desconhecido', E'Masculino', NULL, NULL, NULL, NULL),
(819, E'Ninja Chefe de Kumogakure', E'2 de Abril', E'Humano', NULL, E'Masculino', E'O', NULL, NULL, NULL),
(820, E'Ninkame', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(821, E'Nishi', E'11 de Agosto', E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(822, E'Nitora Take', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(823, E'Nobori', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(824, E'Nonō Yakushi', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(825, E'Nonota', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(826, E'Nue', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(827, E'Nurari', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(828, E'Nurui', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(829, E'Obito Uchiha', E'10 de fevereiro', E'Humano', E'Morto', E'Masculino', E'O', E'010886', E'9', E'11'),
(830, E'Oboro', E'20 de Dezembro', E'Humano', NULL, E'Masculino', E'A', E'R1-127', NULL, NULL),
(831, E'Okami', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(832, E'Okisuke', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(833, E'Oko', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(834, E'Okyō', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(835, E'Olho das Chamas', NULL, E'Humano', NULL, E'Masculino', E'AB', NULL, NULL, NULL),
(836, E'Omoi', E'26 de Dezembro', E'Humano', NULL, E'Masculino', E'AB', E'CL6305', NULL, NULL),
(837, E'Onbu', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(838, E'Orochimaru', E'27 de outubro', E'Humano', NULL, E'Desconhecido', E'B', E'002300', E'6 anos', NULL),
(839, E'Osoi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(840, E'Otoha', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(841, E'Otokaze', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(842, E'Oyone', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(843, E'Pac Lee', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(844, E'Pai de Akane', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(845, E'Pai de Haku', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(846, E'Pai de Ryōgi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(847, E'Pai de Sasori', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(848, E'Pai de Shibuki', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(849, E'Pai de Tsukino', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(850, E'Pai de Yūsuke', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(851, E'Pais de Konohamaru', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(852, E'Pakkun', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(853, E'Pakura', E'9 de Abril', E'Humano', E'Morta', E'Feminino', E'A', NULL, NULL, NULL),
(854, E'Panda Gigante', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(855, E'Parceiro de Sekiei', NULL, E'Humano', E'Desabilitado', E'Masculino', NULL, NULL, NULL, NULL),
(856, E'Patriarca do Clã Ōtsutsuki', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(857, E'Patriarca do Clã Kaguya', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(858, E'País da Geleia de Feijão', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(859, E'País do Céu', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(860, E'País do Mel', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(861, E'Personagens (Filler)', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(862, E'Personagens (Filme)', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(863, E'Personagens (Game)', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(864, E'Pochi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(865, E'Ponta', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(866, E'Portador da Hiramekarei', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(867, E'Potcha', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(868, E'Primeiro Caminho Animal (personagem)', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(869, E'Primeiro Hoshikage', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(870, E'Punho de Pedra', NULL, E'Humano', NULL, E'Masculino', E'B', NULL, NULL, NULL),
(871, E'Pássaro Ahō', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(872, E'Pássaro Bico-de-Broca Gigante', NULL, E'Humano', E'Presumivelmente morto', NULL, NULL, NULL, NULL, NULL),
(873, E'Pássaro de San', NULL, E'Humano', E'Presumido Falecido', NULL, NULL, NULL, NULL, NULL),
(874, E'Quimera Gigante', NULL, E'Humano', E'Morto Provavelmente', NULL, NULL, NULL, NULL, NULL),
(875, E'Rō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(876, E'Rōen', NULL, E'Humano', E'Incapacitado', NULL, NULL, NULL, NULL, NULL),
(877, E'Rōshi', E'4 de Junho', E'Humano', E'Morto', E'Masculino', E'B', NULL, NULL, NULL),
(878, E'Rahyō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(879, E'Rai Uchiha', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(880, E'Raidō Namiashi', E'28 de Agosto', E'Humano', NULL, E'Masculino', E'AB', E'009717', NULL, NULL),
(881, E'Raiga Kurosuki', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(882, E'Raijin', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(883, E'Raimei', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(884, E'Raiz', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(885, E'Ran', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(886, E'Ran (kunoichi)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(887, E'Ranka', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(888, E'Ranke', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(889, E'Ranmaru', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(890, E'Rasa', E'29 de Marco', E'Humano', E'Morto', E'Masculino', E'A', E'28-115', NULL, NULL),
(891, E'Rashii', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(892, E'Rei Concha', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(893, E'Rei Macaco: Enma', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(894, E'Rei do Inferno', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(895, E'Reishi Kodon', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(896, E'Reki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(897, E'Remon Yoimura', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(898, E'Renga', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(899, E'Renga Kokubō', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(900, E'Renge Momoashi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(901, E'Reto', E'27 de Junho', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(902, E'Riichi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(903, E'Riichi (ninja)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(904, E'Rikumaru', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(905, E'Rin Nohara', E'15 de Novembro', E'Humano', E'Morta', E'Feminino', E'A', E'010885', E'9', E'11'),
(906, E'Rinji', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(907, E'Rinoceronte Gigante', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(908, E'Rock Lee', E'27 de novembro', E'Humano', NULL, E'Masculino', E'A', E'012561', E'12', E'15'),
(909, E'Rock Lee (Mundo Genjutsu)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(910, E'Rokkaku Ryūdōin', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(911, E'Rokusuke', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(912, E'Ruiga', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(913, E'Ruka', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(914, E'Ryūase', NULL, E'Humano', E'Desconhecido', NULL, NULL, NULL, NULL, NULL),
(915, E'Ryūgan', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(916, E'Ryōgi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(917, E'Ryōkan', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(918, E'Ryūki', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(919, E'Ryūsa', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(920, E'Ryōshu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(921, E'Ryūsui', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(922, E'Ryūzetsu', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(923, E'Ryuka Tenrō', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(924, E'Sāra', NULL, E'Humano', E'Desconhecido', E'Feminino', NULL, NULL, NULL, NULL),
(925, E'Sēramu', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(926, E'Sōsetsu Kazahana', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(927, E'Sōta', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(928, E'Sōzu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(929, E'Saō', NULL, E'Humano', E'Incapacitado', E'Masculino', NULL, NULL, NULL, NULL),
(930, E'Sabiru', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(931, E'Sabu', E'4 de Outubro', E'Humano', NULL, E'Masculino', E'O', NULL, NULL, NULL),
(932, E'Sada', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(933, E'Sadai', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(934, E'Sadoru', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(935, E'Sagan', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(936, E'Sagi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(937, E'Sagiri', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(938, E'Sai', E'25 de movembro', E'Humano', NULL, E'Masculino', E'A', E'012420', E'9', E'10'),
(939, E'Saiken', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(940, E'Saisu Kamano', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(941, E'Sajō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(942, E'Sajin', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(943, E'Sajin (Genin)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(944, E'Sakon e Ukon', E'20 de Junho', E'Humano', E'Mortos', E'Masculino', NULL, NULL, NULL, NULL),
(945, E'Sakumo Hatake', E'3 de Setembro', E'Humano', E'Morto', E'Masculino', E'O', NULL, NULL, NULL),
(946, E'Sakura Haruno', E'28 de marco', E'Humano', NULL, E'Feminino', E'O', E'012601', E'12', E'14'),
(947, E'Samidare', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(948, E'Samidare Amaashi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(949, E'Samo', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(950, E'Samui', E'7 de Janeiro', E'Humano', NULL, E'Feminino', E'A', E'CL5570', NULL, NULL),
(951, E'San', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(952, E'Sana', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(953, E'Sandayū Asama', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(954, E'Sangorō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(955, E'Sanshō', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(956, E'Santa Yamanaka', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(957, E'Sarada Uchiha', E'31 de Marco', E'Humano', NULL, E'Feminino', NULL, NULL, E'11 anos', NULL),
(958, E'Sarai', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(959, E'Sari', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(960, E'Sasame Fūma', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(961, E'Sasami', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(962, E'Sasori', E'8 de novembro', E'Humano', E'Morto', E'Masculino', E'AB', E'33-001', E'7', E'8'),
(963, E'Sasuke Sarutobi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(964, E'Sasuke Uchiha', E'23 de julho', E'Humano', NULL, E'Masculino', E'AB', E'012606', E'12', NULL),
(965, E'Sasuke Uchiha (Mundo Genjutsu)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(966, E'Satō', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(967, E'Satchi', NULL, E'Humano', E'Possivelmente Morto', NULL, NULL, NULL, NULL, NULL),
(968, E'Satetsu (Personagem)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(969, E'Satori', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(970, E'Saya', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(971, E'Sazanami', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(972, E'Sazanami Senka', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(973, E'Segunda Divisão', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(974, E'Segurança de Fronteira', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(975, E'Seimei', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(976, E'Seito', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(977, E'Sekiei', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(978, E'Sekiei (espectador)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(979, E'Sekka', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(980, E'Sekki', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(981, E'Sen', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(982, E'Sensei de Kabuto', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(983, E'Sensei de Kumo', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(984, E'Sensei de Suna', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(985, E'Senta', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(986, E'Sentoki', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(987, E'Setsuna', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(988, E'Setsuna Uchiha', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(989, E'Shū', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(990, E'Shū (lorde)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(991, E'Shōseki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(992, E'Shabadaba', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(993, E'Shamon', E'12 de Marco', E'Humano', E'Morto', E'Masculino', E'O', NULL, NULL, NULL),
(994, E'Shiba', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(995, E'Shiba (Kusagakure)', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(996, E'Shibi Aburame', E'07 de Setembro', E'Humano', NULL, E'Masculino', E'A', E'005480', NULL, NULL),
(997, E'Shibire', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(998, E'Shibito Azuma', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(999, E'Shibuki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1000, E'Shigezane', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1001, E'Shigure', E'11 de Fevereiro', E'Humano', NULL, E'Masculino', E'B', E'R1-115', NULL, NULL),
(1002, E'Shiho', E'18 de Junho', E'Humano', NULL, E'Feminino', E'AB', NULL, NULL, NULL),
(1003, E'Shiin', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1004, E'Shijima', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1005, E'Shikadai Nara', E'23 de Setembro', E'Humano', NULL, E'Masculino', NULL, NULL, E'11 anos', E'12 anos'),
(1006, E'Shikaku Nara', E'15 de julho', E'Humano', E'Morto', E'Masculino', E'B', E'005491', NULL, NULL),
(1007, E'Shikamaru Nara', E'22 de Setembro', E'Humano', NULL, E'Masculino', E'AB', E'012611', E'12', E'12'),
(1008, E'Shikazo', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1009, E'Shikuro Aburame', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1010, E'Shima', E'26 de Agosto', E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(1011, E'Shimeji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1012, E'Shimo', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1013, E'Shimon Hijiri', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1014, E'Shinemon', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1015, E'Shin', E'6 de Setembro', E'Humano', E'Morto', E'Masculino', E'B', NULL, NULL, NULL),
(1016, E'Shin Uchiha', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1017, E'Shinayakana', NULL, E'Humano', E'Presumivelmente Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1018, E'Shinga', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1019, E'Shinigami', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1020, E'Shinki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1021, E'Shinko Inari', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1022, E'Shinku Yūhi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1023, E'Shinnō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1024, E'Shino Aburame', E'23 de janeiro', E'Humano', NULL, E'Masculino', E'AB', E'012618', E'12', E'14'),
(1025, E'Shino Aburame (Mundo Genjutsu)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1026, E'Shinobu Mibu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1027, E'Shinta', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1028, E'Shio', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(1029, E'Shion', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(1030, E'Shiore', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1031, E'Shira', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1032, E'Shiranami', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1033, E'Shiro', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(1034, E'Shiro (Livro de Jiraiya)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1035, E'Shiromari', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1036, E'Shisō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1037, E'Shiseru', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1038, E'Shishio', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1039, E'Shisui Uchiha', E'19 de outubro', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(1040, E'Shitō Akimichi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1041, E'Shizuka', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1042, E'Shizuku', NULL, E'Humano', E'Falecida', E'Feminino', NULL, NULL, NULL, NULL),
(1043, E'Shizuma Hoshigaki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1044, E'Shizune', E'18 de Novembro', E'Humano', NULL, E'Feminino', E'A', E'010800', E'9', E'13'),
(1045, E'Shojoji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1046, E'Shukaku', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1047, E'Shun', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1048, E'Shura', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1049, E'Son Gokū', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1050, E'Sora', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1051, E'Sora (órfã)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1052, E'Suguro', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1053, E'Suien', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1054, E'Suigetsu Hōzuki', E'18 de Fevereiro', E'Humano', NULL, E'Masculino', E'B', NULL, NULL, NULL),
(1055, E'Suika', NULL, E'Humano', E'Morto Presumivelmente', E'Masculino', NULL, NULL, NULL, NULL),
(1056, E'Suika Kannonji', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(1057, E'Suiko', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1058, E'Suiren', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1059, E'Suiren (Kiri)', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(1060, E'Suiu', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1061, E'Sukeza', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1062, E'Sukima', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1063, E'Sukui', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1064, E'Sukune', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(1065, E'Sumaru', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1066, E'Sumashi', NULL, E'Humano', E'Morto Provavelmente', E'Masculino', NULL, NULL, NULL, NULL),
(1067, E'Sumire', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1068, E'Sumire Kakei', E'12 de junho', E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1069, E'Suname', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1070, E'Susuki', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(1071, E'Suzaku (ministro)', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1072, E'Suzaku Nara', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1073, E'Suzu', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1074, E'Suzume', E'19 de outubro', E'Humano', NULL, E'Feminino', NULL, E'009902', NULL, NULL),
(1075, E'Suzumebachi', NULL, E'Humano', E'Presumivelmente Morta', E'Feminino', NULL, NULL, NULL, NULL),
(1076, E'Suzuran', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1077, E'Tadaichi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1078, E'Tagitsuhime', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(1079, E'Tagorihime', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(1080, E'Taiga', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1081, E'Taiko Uchiha', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1082, E'Taisa Amagiri', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1083, E'Taiseki', E'10 de Marco', E'Humano', E'Morto', E'Masculino', E'O', E'IW-06225', NULL, NULL),
(1084, E'Taizō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1085, E'Taji', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(1086, E'Tajiki', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1087, E'Tajima Uchiha', E'28 de Marco', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(1088, E'Taka', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1089, E'Takamaru', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1090, E'Takanami Senka', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1091, E'Takemaru', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1092, E'Takishi', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(1093, E'Taku', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1094, E'Tamae', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1095, E'Tamaki', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1096, E'Tamanduá Gigante', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1097, E'Tamao', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1098, E'Tami', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1099, E'Tango', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1100, E'Tanishi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1101, E'Tanuki Shigaraki', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1102, E'Tanzō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1103, E'Tarō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1104, E'Taruho', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1105, E'Tarui', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1106, E'Tatewaki', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1107, E'Tatsuji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1108, E'Tatsuma Aburame', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1109, E'Tatsumi', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1110, E'Tayori Kuroyagi', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1111, E'Tayuya', E'15 de Fevereiro', E'Humano', E'Morta', E'Feminino', E'A', NULL, NULL, NULL),
(1112, E'Tazuna', E'5 de Abril', E'Humano', NULL, E'Masculino', E'A', NULL, NULL, NULL),
(1113, E'Teguse', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1114, E'Tekka Uchiha', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(1115, E'Tekuno Kanden', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1116, E'Temari', E'23 de agosto', E'Humano', NULL, E'Feminino', E'O', E'53-004', E'12 Anos', E'17 anos'),
(1117, E'Temui', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1118, E'Temujin', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1119, E'Tenga', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1120, E'Tenji', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1121, E'Tenma Izumo', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1122, E'Tenma Kodon', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1123, E'Tentō Madoka', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1124, E'Tenten', E'9 de marco', E'Humano', NULL, E'Feminino', E'B', E'012573', E'12', E'15'),
(1125, E'Tenzō (Clã Iburi)', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1126, E'Tenzen', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1127, E'Tenzen Daikoku', NULL, E'Humano', E'Presumivelmente Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1128, E'Tera', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1129, E'Terai', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1130, E'Terceira Divisão', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1131, E'Terceiro Hoshikage', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1132, E'Terceiro Kazekage', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1133, E'Terceiro Mizukage', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1134, E'Terubō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1135, E'Tessa', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(1136, E'Tessen Togeito', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1137, E'Tetsu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1138, E'Tetsu Hyūga', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1139, E'Tetsuru', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1140, E'Teuchi', E'10 de agosto', E'Humano', NULL, E'Masculino', E'O', NULL, NULL, NULL),
(1141, E'Teyaki Uchiha', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1142, E'Tezuna', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1143, E'Time 15', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1144, E'Time 2', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1145, E'Time 25', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1146, E'Time 40', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1147, E'Time 5', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1148, E'Time Asuma', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1149, E'Time Bandō', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1150, E'Time Dosu', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1151, E'Time Ebisu', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1152, E'Time Ganryū', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1153, E'Time Guren', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1154, E'Time Guy', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1155, E'Time Hiruko', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1156, E'Time Jiraiya', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1157, E'Time Kakashi', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1158, E'Time Karin', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1159, E'Time Komugi', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1160, E'Time Kurenai', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1161, E'Time Minato', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1162, E'Time Moegi', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1163, E'Time Ro', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1164, E'Time Samui', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1165, E'Time Shū', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1166, E'Time Shibire', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1167, E'Time Shigure', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1168, E'Time Shinki', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1169, E'Time Shira', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1170, E'Time Shisui', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1171, E'Time Suien', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1172, E'Time Tobirama', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1173, E'Time Yurui', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1174, E'Time de Análise', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1175, E'Time de Barreira de Konoha', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1176, E'Time de Captura do Hachibi', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1177, E'Time de Comunicações', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1178, E'Time de Genin de Kabuto', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1179, E'Time de Infiltração e Reconhecimento', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1180, E'Time de Liberação de Vento', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1181, E'Time de Patrulha da Fronteira do Norte', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1182, E'Time de Procura a Orochimaru', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1183, E'Time de Resgate de Sasuke', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1184, E'Time de Selamento', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1185, E'Time de Três Homens de Dotō', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1186, E'Tobi (Zetsu)', NULL, E'Humano', E'Morto', E'Masculino', E'B', NULL, NULL, NULL),
(1187, E'Tobimaru', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1188, E'Tobio', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1189, E'Tobirama Senju', E'19 de fevereiro', E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1190, E'Todoroki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1191, E'Tofu', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1192, E'Tokara', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1193, E'Toki', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1194, E'Toki (Shinobazu)', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1195, E'Tokiwa', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1196, E'Ūhei', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1197, E'Ōkei', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1198, E'Ōnoki', E'8 de outubro', E'Humano', E'Morto', E'Masculino', E'O', NULL, NULL, NULL),
(1199, E'Ōtora', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1200, E'Ōwashi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1201, E'Tōbei Kagetsu', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1202, E'Tōfu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1203, E'Tōjūrō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1204, E'Tōka Senju', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(1205, E'Tōu', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(1206, E'Tokuma Hyūga', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1207, E'Tomari', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1208, E'Tomaru', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1209, E'Tomaru Minakura', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1210, E'Tonbee', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1211, E'Tonbo Tobitake', E'4 de Abril', E'Humano', NULL, E'Masculino', E'A', E'010997', NULL, NULL),
(1212, E'Toneri Ōtsutsuki', NULL, E'Humano', E'Incapacitado', E'Masculino', NULL, NULL, NULL, NULL),
(1213, E'Tonton', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1214, E'Tora (Anbu)', NULL, E'Humano', E'Presumivelmente Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1215, E'Tora (gato)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1216, E'Torifu Akimichi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1217, E'Toroi', E'6 de Outubro', E'Humano', E'Morto', E'Masculino', E'O', NULL, NULL, NULL),
(1218, E'Toroi (Genin)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1219, E'Torune Aburame', NULL, E'Humano', E'Morto', E'Masculino', E'O', E'012360', NULL, NULL),
(1220, E'Tosaka', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1221, E'Touro Gigante', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(1222, E'Toyosa', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(1223, E'Três Cobras Gigantes', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1224, E'Três Irmãos', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1225, E'Três Irmãos Haimaru', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1226, E'Três Irmãos da Areia', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1227, E'Tsubaki (anime)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1228, E'Tsubaki (mãe)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1229, E'Tsubaki Kurogane', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1230, E'Tsubusa', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1231, E'Tsuchino', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1232, E'Tsuchinoe', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1233, E'Tsuchinoto', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1234, E'Tsukado', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1235, E'Tsukiko Kagetsu', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1236, E'Tsukino', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1237, E'Tsukiyo', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(1238, E'Tsukune', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(1239, E'Tsukushi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(1240, E'Tsume Inuzuka', E'12 de Agosto', E'Humano', NULL, E'Feminino', E'B', NULL, NULL, NULL),
(1241, E'Tsunade', E'2 de Agosto', E'Humano', NULL, E'Feminino', E'B', E'002302', E'6 anos', NULL),
(1242, E'Tsunami', E'4 de Maio', E'Humano', NULL, E'Feminino', E'A', NULL, NULL, NULL),
(1243, E'Tsuru Itoi', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(1244, E'Tsurugi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL);
