INSERT INTO `Ninja` (`id`, `name`, `birthdate`, `specie`, `status`, `sex`, `bloodType`, `ninjaRegistration`, `academyGradAge`, `chuninPromAge`) VALUES
(1, 'A (Primeiro Raikage)', '1 de Dezembro', 'Humano', 'Morto', 'Masculino', 'O', NULL, NULL, NULL),
(2, 'A (Quarto Raikage)', '1 de Junho', 'Humano', NULL, 'Masculino', 'A', 'CL2211', NULL, NULL),
(3, 'A (Segundo Raikage)', '1 de Marco', 'Humano', NULL, 'Masculino', 'O', NULL, NULL, NULL),
(4, 'A (Terceiro Raikage)', '01 de agosto', 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(5, 'Abelha Gigante', NULL, 'Humano', 'Morta', NULL, NULL, NULL, NULL, NULL),
(6, 'Abiru', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(7, 'Agara', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(8, 'Agari', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(9, 'Agari Kaisen', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(10, 'Ageha', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(11, 'Agira Ryūdōin', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(12, 'Ahiko', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(13, 'Aino', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(14, 'Ajisai', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(15, 'Akaboshi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(16, 'Akahoshi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(17, 'Akamaru', '7 de Julho', 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(18, 'Akane', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(19, 'Akane (kunoichi)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(20, 'Akari Tatsushiro', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(21, 'Akatsuchi', '11 de Janeiro', 'Humano', NULL, 'Masculino', 'B', 'IW-08718', NULL, NULL),
(22, 'Akemaru', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(23, 'Akino', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(24, 'Akio', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(25, 'Akita Inuzuka', '20 de Abril', 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(26, 'Akkun', NULL, 'Humano', 'Morto', 'Hermafrodita', NULL, NULL, NULL, NULL),
(27, 'Amachi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(28, 'Amado', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(29, 'Amagi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, '13'),
(30, 'Amai', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(31, 'Amaru', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(32, 'Amayo', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(33, 'Ame', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(34, 'Ameno', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(35, 'Ameyuki', NULL, 'Humano', 'Falecida', 'Feminino', NULL, NULL, NULL, NULL),
(36, 'Ameyuri Ringo', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(37, 'Ami', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(38, 'Amino', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(39, 'Ancião Hyūga', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(40, 'Aniki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(41, 'Animais', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(42, 'Anko Mitarashi', '24 de Outubro', 'Humano', NULL, 'Feminino', 'A', '011226', '10', '12'),
(43, 'Ao', '01 de Agosto', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(44, 'Aoba Yamashiro', '03 de Setembro', 'Humano', NULL, 'Masculino', 'O', '009744', NULL, NULL),
(45, 'Aoda', '1 de Outubro', 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(46, 'Aoi Rokushō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(47, 'Apicultor', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(48, 'Arai', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(49, 'Arashi Fūma', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(50, 'Araya', '13 de Marco', 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(51, 'Armadiko', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(52, 'Asami', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(53, 'Ashimaru', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(54, 'Ashina', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(55, 'Ashina Uzumaki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(56, 'Ashitaba', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(57, 'Ashura Ōtsutsuki', '8 de Junho', 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(58, 'Assistente do Escultor de Pedra', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(59, 'Astrônoma de Konoha', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(60, 'Asuma Sarutobi', '18 de Outubro', 'Humano', 'Morto', 'Masculino', 'O', '010829', '9', '12'),
(61, 'Atsui', '2 de Agosto', 'Humano', NULL, 'Masculino', 'O', 'CL6265', NULL, NULL),
(62, 'Avó de Obito', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(63, 'Ayame', '14 de Fevereiro', 'Humano', NULL, 'Feminino', 'O', NULL, NULL, NULL),
(64, 'Ayato', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(65, 'Azami', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(66, 'Baiu', '30 de Maio', 'Humano', 'Morto', 'Masculino', 'A', 'R2-039', NULL, NULL),
(67, 'Baji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(68, 'Baki', '4 de Julho', 'Humano', NULL, 'Masculino', 'A', '38-212', '8', '12'),
(69, 'Baku', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(70, 'Baku (Anbu)', NULL, 'Humano', 'Morto Presumivelmente', 'Masculino', NULL, NULL, NULL, NULL),
(71, 'Bakuto', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(72, 'Bandō', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(73, 'Banna', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(74, 'Bansai', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(75, 'Baraki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(76, 'Baru Uchiha', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(77, 'Bekkō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(78, 'Benga', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(79, 'Benten', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(80, 'Besta Espiritual', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(81, 'Besta Guardiã de Três Cabeças', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(82, 'Bisuke', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(83, 'Biwako Sarutobi', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(84, 'Blue B', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(85, 'Boro', NULL, 'Humano', 'Presumivelmente morto', 'Masculino', NULL, NULL, NULL, NULL),
(86, 'Boruto Uzumaki', '27 de Marco', 'Humano', NULL, 'Masculino', NULL, NULL, '11', NULL),
(87, 'Bull', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(88, 'Buna', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(89, 'Bunpuku', '9 de Fevereiro', 'Humano', 'Morto', 'Masculino', 'O', NULL, NULL, NULL),
(90, 'Buntan Kurosuki', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(91, 'Bunzō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(92, 'Burami', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(93, 'Butsuma Senju', '16 de Janeiro', 'Humano', 'Morto', 'Masculino', 'AB', NULL, NULL, NULL),
(94, 'Byakuren', '20 de Janeiro', 'Humano', 'Morto', 'Masculino', 'B', NULL, NULL, NULL),
(95, 'C', '3 de Abril', 'Humano', NULL, 'Masculino', 'A', 'CL5517', NULL, NULL),
(96, 'Camaleão Gigante', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(97, 'Caminho Humano', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(98, 'Cangurus Boxeadores', NULL, 'Humano', 'Vivos', 'Feminino', NULL, NULL, NULL, NULL),
(99, 'Capitão Assassino de Suna', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(100, 'Capitão do Navio Fantasma', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(101, 'Caranguejo Cadáver Gigante', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(102, 'Centopeia Gigante', NULL, 'Humano', 'Morta', NULL, NULL, NULL, NULL, NULL),
(103, 'Chōbee Akimichi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(104, 'Chōchō Akimichi', '8 de Agosto', 'Humano', NULL, 'Feminino', NULL, NULL, '11', NULL),
(105, 'Chōhan', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(106, 'Chōjūrō', '1 de Novembro', 'Humano', NULL, 'Masculino', 'B', NULL, NULL, NULL),
(107, 'Chūji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(108, 'Chōji Akimichi', '1 de Maio', 'Humano', 'Vivo', 'Masculino', 'B', '012625', '12', '14'),
(109, 'Chūkaku', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(110, 'Chūkichi', '2 de Julho', 'Humano', 'Morto', 'Masculino', 'AB', NULL, NULL, NULL),
(111, 'Chōmei', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(112, 'Chōseki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(113, 'Chūshin', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(114, 'Chōza Akimichi', '22 de Abril', 'Humano', NULL, 'Masculino', 'B', '005490', NULL, NULL),
(115, 'Chamū', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(116, 'Chamaru', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(117, 'Chefe Hippo', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(118, 'Chefe da Vila Tonika', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(119, 'Chefe de Aldeia (personagem)', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(120, 'Chefe de Tsuchigumo', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(121, 'Chen', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(122, 'Chen (estudante)', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(123, 'Chibi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(124, 'Chichiatsu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(125, 'Chikara', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(126, 'Chino', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(127, 'Chiriku', '1 de Julho', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(128, 'Chishima', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(129, 'Chiyo', '15 de Outubro', 'Humano', 'Morta', 'Feminino', 'B', '01-002', NULL, NULL),
(130, 'Chiyo (princesa)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(131, 'Chiyomatsu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(132, 'Choco', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(133, 'Clone do Nove-Caudas', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(134, 'Clã Sendō', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(135, 'Code', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(136, 'Comandante da Anbu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(137, 'Companheiro de Kakuzu', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(138, 'Condor', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(139, 'Corvo de Itachi', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(140, 'Criatura Espiã com Sharingan', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(141, 'Crustáceo Gigante', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(142, 'Cães de Ni', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(143, 'Cão de Guarda', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(144, 'Dōshin', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(145, 'Dōshu Goetsu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(146, 'Dōtō Akimichi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(147, 'Daen Nara', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(148, 'Daibutsu', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(149, 'Daichi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(150, 'Daikoku Funeno', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(151, 'Daimaru', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(152, 'Daimyō Desconhecido', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(153, 'Daimyō do Isto', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(154, 'Daimyō do País da Geada', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(155, 'Daimyō do País da Terra', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(156, 'Daimyō do País da Água', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(157, 'Daimyō do País das Fontes Termais', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(158, 'Daimyō do País do Chá', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(159, 'Daimyō do País do Fogo', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(160, 'Daimyō do País do Relâmpago', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(161, 'Daimyō do Vento (Parte I)', '5 de Novembro', 'Humano', NULL, 'Masculino', 'B', NULL, NULL, NULL),
(162, 'Daimyō do Vento (Parte II)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(163, 'Dajimu', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(164, 'Dan Katō', '4 de Dezembro', 'Humano', 'Morto', 'Masculino', 'A', '002973', NULL, NULL),
(165, 'Dangō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(166, 'Dango Mitsuki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(167, 'Danzō Shimura', '6 de Janeiro', 'Humano', NULL, 'Masculino', 'AB', '000272', NULL, NULL),
(168, 'Dançarina dos Ventos', NULL, 'Humano', NULL, 'Feminino', 'O', NULL, NULL, NULL),
(169, 'Darui', '6 de Janeiro', 'Humano', NULL, 'Masculino', 'O', 'CL5596', NULL, NULL),
(170, 'Datsuji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(171, 'Deepa', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(172, 'Deidara', '5 de Maio', 'Humano', NULL, 'Masculino', 'AB', 'IW-08721', NULL, NULL),
(173, 'Delta', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(174, 'Dengaku', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(175, 'Denka', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(176, 'Denki Kaminarimon', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(177, 'Dez-Caudas', NULL, 'Humano', 'Incapacitado', NULL, NULL, NULL, NULL, NULL),
(178, 'Dez-Caudas de Isshiki', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(179, 'Disonasu', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(180, 'Dodai', '23 de Outubro', 'Humano', 'Vivo', 'Masculino', 'O', 'CL1532', NULL, NULL),
(181, 'Dokan', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(182, 'Doki', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(183, 'Dokku', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(184, 'Don', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(185, 'Doragu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(186, 'Dosu Kinuta', '12 de Junho', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(187, 'Dotō Kazahana', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(188, 'Doutor de Iwa', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(189, 'Ebisu', '8 de Marco', 'Humano', 'Vivo', 'Masculino', 'A', '010777', NULL, NULL),
(190, 'Ebizō', '6 de Janeiro', 'Humano', NULL, 'Masculino', 'B', '02-002', NULL, NULL),
(191, 'Ehō Norimaki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(192, 'Emi', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(193, 'Emiru', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(194, 'En', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(195, 'En Oyashiro', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(196, 'En no Gyōja', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(197, 'Enchū Nara', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(198, 'Enko Onikuma', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(199, 'Enra', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(200, 'Ensui Nara', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(201, 'Enzo Tenrō', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(202, 'Ereki Kaminarimon', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(203, 'Escultor de Pedra', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(204, 'Espadachim', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(205, 'Esposa de Kisuke', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(206, 'Estátua Demoníaca do Caminho Exterior', NULL, 'Humano', 'Incapacitado', NULL, NULL, NULL, NULL, NULL),
(207, 'Estátua do Clã Ōtsutsuki', NULL, 'Humano', 'Presumivelmente Falecido', NULL, NULL, NULL, NULL, NULL),
(208, 'Etoro Konjiki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(209, 'F', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(210, 'Fū', '8 de Agosto', 'Humano', 'Morta', 'Feminino', 'B', NULL, NULL, NULL),
(211, 'Fū Yamanaka', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(212, 'Fūjin', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(213, 'Fūka', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(214, 'Fūshin', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(215, 'Fūta Kagetsu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(216, 'Faz', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(217, 'Feiticeiro', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(218, 'Filha de Sāra', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(219, 'Filho de Gennō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(220, 'Forças Aliadas Shinobi', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(221, 'Fubuki Kakuyoku', NULL, 'Humano', 'Falecida', 'Feminino', NULL, NULL, NULL, NULL),
(222, 'Fudō', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(223, 'Fuen', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(224, 'Fugai', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(225, 'Fugaku Uchiha', '16 de Agosto', 'Humano', 'Morto', 'Masculino', 'AB', '004086', NULL, NULL),
(226, 'Fugi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(227, 'Fuguki Suikazan', '22 de Fevereiro', 'Humano', 'Morto', 'Masculino', 'O', NULL, NULL, NULL),
(228, 'Fukasaku', '9 de Maio', 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(229, 'Fuki', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(230, 'Fuki (País do Som)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(231, 'Fuku', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(232, 'Fukuemon', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(233, 'Fukurokumaru', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(234, 'Fukusuke Hikyakuya', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(235, 'Fukuyokana', NULL, 'Humano', 'Presumivelmente Morto', 'Masculino', NULL, NULL, NULL, NULL),
(236, 'Funari', NULL, 'Humano', 'Morto Presumido', 'Masculino', NULL, NULL, NULL, NULL),
(237, 'Furofuki', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(238, 'Furui', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(239, 'Fusō', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(240, 'Futaba', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(241, 'Futami', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(242, 'Futsu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(243, 'Fuyō', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(244, 'Gōza', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(245, 'Gaara', '19 de Janeiro', 'Humano', NULL, 'Masculino', 'AB', '56-001', '12', '14'),
(246, 'Gakidō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(247, 'Gaku Inuzuka', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(248, 'Gama', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(249, 'Gamabunta', '3 de Janeiro', 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(250, 'Gamaden', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(251, 'Gamagorō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(252, 'Gamahiro', '9 de Julho', 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(253, 'Gamaken', '11 de Outubro', 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(254, 'Gamakichi', '1 de Abril', 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(255, 'Gamamaru', '8 de Marco', 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(256, 'Gamariki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(257, 'Gamatama', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(258, 'Gamatatsu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(259, 'Gameru', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(260, 'Gandō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(261, 'Gangue Byakuya', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(262, 'Ganryū', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(263, 'Gantetsu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(264, 'Gantetsu (Iwagakure)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(265, 'Garō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(266, 'Garaga', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(267, 'Gari', '8 de Agosto', 'Humano', 'Morto', 'Masculino', 'AB', NULL, NULL, NULL),
(268, 'Garra das Águas', NULL, 'Humano', NULL, 'Feminino', 'A', NULL, NULL, NULL),
(269, 'Garuda', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(270, 'Garyō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(271, 'Gatō', '30 de Abril', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(272, 'Gatai', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(273, 'Gataro', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(274, 'Gatsu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(275, 'Gazeru', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(276, 'Gekkō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(277, 'Gekomatsu', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(278, 'Gen\'yūmaru', '27 de Julho', 'Humano', 'Morto', 'Masculino', 'B', NULL, NULL, NULL),
(279, 'Genba', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(280, 'Genbu', NULL, 'Humano', 'Viva', NULL, NULL, NULL, NULL, NULL),
(281, 'Genbu (ministro)', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(282, 'Gengetsu Hōzuki', '26 de Outubro', 'Humano', NULL, 'Masculino', 'AB', NULL, NULL, NULL),
(283, 'Gengo', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(284, 'Genji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(285, 'Genma Shiranui', '17 de Julho', 'Humano', NULL, 'Masculino', 'A', '010203', '10', '13'),
(286, 'Genmai', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(287, 'Gennō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(288, 'Gennai', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(289, 'Genshō Ryūdōin', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(290, 'Gensui Amagiri', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(291, 'Genzō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(292, 'Gerotora', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(293, 'Gigante Marlin', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(294, 'Giichi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(295, 'Ginji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(296, 'Ginkaku', '9 de Abril', 'Humano', 'Morto', 'Masculino', 'AB', NULL, NULL, NULL),
(297, 'Gitai', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(298, 'Gojō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(299, 'Goji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(300, 'Golem de Prisão de Terra', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(301, 'Gonbee', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(302, 'Gongorō Kamakura', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(303, 'Goshiki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(304, 'Gosunkugi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(305, 'Gotta', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(306, 'Gōzu', '6 de Junho', 'Humano', NULL, 'Masculino', 'B', NULL, '12', '18'),
(307, 'Gozu (Raiz)', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(308, 'Grupo Prajñā', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(309, 'Grupo do Trovão Negro', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(310, 'Guarda-costas de Tenzen', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(311, 'Guardião de Kinshiki', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(312, 'Guardião do Portão', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(313, 'Guerreiro Amaldiçoado', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(314, 'Guren', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(315, 'Guren (prisioneiro)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(316, 'Guruko', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(317, 'Gyūki', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(318, 'Gyokurō Chabashira', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(319, 'Gênio', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(320, 'Hōichi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(321, 'Hōki (Takigakure)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(322, 'Hōki (Takumi)', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(323, 'Hōki (Watari)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(324, 'Hōki Taketori', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(325, 'Hōsei', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(326, 'Hōshō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(327, 'Hāto', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(328, 'Hachidai', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(329, 'Hagoromo Ōtsutsuki', '6 de Agosto', 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(330, 'Haguruma', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(331, 'Haido', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(332, 'Haie', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(333, 'Hajiki', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(334, 'Hajiri', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(335, 'Hakkaku', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(336, 'Hako Kuroi', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(337, 'Haku', '9 de Janeiro', 'Humano', 'Morto', 'Masculino', 'O', NULL, NULL, NULL),
(338, 'Hakuhyō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(339, 'Hakui', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(340, 'Hakui (Médico)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(341, 'Hakuja Sennin', '6 de Abril', 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(342, 'Hakuto', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(343, 'Hamaki Mimura', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(344, 'Hamura Ōtsutsuki', '6 de Agosto', 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(345, 'Han', '10 de Maio', 'Humano', 'Morto', 'Masculino', 'B', NULL, NULL, NULL),
(346, 'Hana Inuzuka', '13 de Abril', 'Humano', NULL, 'Feminino', 'O', '012368', NULL, NULL),
(347, 'Hanabi Hyūga', '27 de Marco', 'Humano', NULL, 'Feminino', 'A', NULL, NULL, NULL),
(348, 'Hanare', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(349, 'Hanuma', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(350, 'Hanzō', '12 de Fevereiro', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(351, 'Hanzaki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(352, 'Haori', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(353, 'Harine', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(354, 'Haruna', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(355, 'Harusame', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(356, 'Hashirama Senju', '23 de Outubro', 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(357, 'Hassaku Onomichi', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(358, 'Hayama Shirakumo', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(359, 'Hayase', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(360, 'Hayate Gekkō', '2 de Novembro', 'Humano', 'Morto', 'Masculino', 'AB', '011671', '12', '13'),
(361, 'Hazuki Uchiha', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(362, 'Hebiichigo', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(363, 'Heiji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(364, 'Heki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(365, 'Hiashi Hyūga', '8 de Janeiro', 'Humano', NULL, 'Masculino', 'B', '05159', NULL, NULL),
(366, 'Hibachi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(367, 'Hibari', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(368, 'Hidan', '2 de Abril', 'Humano', 'Desconhecido', 'Masculino', 'B', NULL, NULL, NULL),
(369, 'Hidari', NULL, 'Humano', 'Provavelmente Morto', 'Masculino', NULL, NULL, NULL, NULL),
(370, 'Hidero', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(371, 'Hikaku Uchiha', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(372, 'Hikaru', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(373, 'Hikaru Tsuki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(374, 'Himatsu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(375, 'Himawari Uzumaki', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(376, 'Himeno', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(377, 'Himuka Suzukaze', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(378, 'Himushi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(379, 'Hina', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(380, 'Hinata Hyūga', '27 de Dezembro', 'Humano', NULL, 'Feminino', 'A', '012612', '12 Anos', '14 anos'),
(381, 'Hinata Hyūga (Mundo Genjutsu)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(382, 'Hino', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(383, 'Hinoe', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(384, 'Hinoko', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(385, 'Hinoto', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(386, 'Hiruko (nukenin)', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(387, 'Hiruzen Sarutobi', '8 de Fevereiro', 'Humano', 'Morto', 'Masculino', 'A', '000261', NULL, NULL),
(388, 'Hisame', NULL, 'Humano', 'Incapacitada', 'Feminino', NULL, NULL, NULL, NULL),
(389, 'Hishaku', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(390, 'Hitode', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(391, 'Hizashi Hyūga', '8 de Janeiro', 'Humano', 'Morto', 'Masculino', 'B', '005160', NULL, NULL),
(392, 'Hizashi Hyūga (Livro de Jiraiya)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(393, 'Hoheto Hyūga', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(394, 'Hohozuki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(395, 'Hokushin', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(396, 'Hokuto', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(397, 'Homura Mitokado', '8 de Maio', 'Humano', 'Vivo', 'Masculino', 'A', '000293', NULL, NULL),
(398, 'Honoka', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(399, 'Hotaru (estudante)', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(400, 'Hotaru Katsuragi', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(401, 'Hotarubi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(402, 'Hyō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(403, 'Iō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(404, 'Iō (Ninja Médico)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(405, 'Iō (Vila dos Bambus)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(406, 'Ibara', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(407, 'Ibiki Morino', '20 de Marco', 'Humano', 'Vivo', 'Masculino', 'A', '010913', '10 anos', '15 anos'),
(408, 'Ibuse', NULL, 'Humano', 'Morto Provavelmente', NULL, NULL, NULL, NULL, NULL),
(409, 'Ibushi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(410, 'Ichi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(411, 'Ichigen', NULL, 'Humano', 'Morto Presumivelmente', 'Masculino', NULL, NULL, NULL, NULL),
(412, 'Ichikishimahime', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(413, 'Ichirōta Oniyuzu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(414, 'Idate Morino', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(415, 'Iggy', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(416, 'Ikanago', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(417, 'Ikkaku Umino', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(418, 'Ikkyū Madoka', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(419, 'Inabi Uchiha', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(420, 'Inaho', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(421, 'Inari', '25 de Dezembro', 'Humano', NULL, 'Masculino', 'A', NULL, NULL, NULL),
(422, 'Indra Ōtsutsuki', '4 de Janeiro', 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(423, 'Ino Yamanaka', '23 de Setembro', 'Humano', NULL, 'Feminino', 'B', '012604', '12 anos', '14 anos'),
(424, 'Ino Yamanaka (Mundo Genjutsu)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(425, 'Inoichi Yamanaka', '24 de Janeiro', 'Humano', 'Morto', 'Masculino', 'AB', '005492', NULL, NULL),
(426, 'Inojin Yamanaka', '5 de dezembro', 'Humano', NULL, 'Masculino', NULL, NULL, '11', NULL),
(427, 'Inomatsu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(428, 'Inseto Gigante', NULL, 'Humano', 'Vivo', NULL, NULL, NULL, NULL, NULL),
(429, 'Iori', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(430, 'Iroha Hyūga', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(431, 'Iruka Umino', '26 de Maio', 'Humano', NULL, 'Masculino', 'O', '011850', '11 anos', '16 anos'),
(432, 'Isago', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(433, 'Isago (Filha de Gojō)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(434, 'Isaribi', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(435, 'Ise', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(436, 'Ishidate', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(437, 'Ishikawa', '6 de Maio', 'Humano', 'Morto', 'Masculino', 'O', NULL, NULL, NULL),
(438, 'Isobu', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(439, 'Isono', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(440, 'Isshiki Ōtsutsuki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(441, 'Itachi Uchiha', '09 de Junho', 'Humano', 'Morto', 'Masculino', 'AB', '012110', '7 anos', '10 anos'),
(442, 'Itama Senju', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(443, 'Ittan', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(444, 'Ittetsu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(445, 'Iwabee Yuino', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(446, 'Iwaji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(447, 'Iwakyō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(448, 'Iwana', NULL, 'Humano', 'Presumivelmente Morto', 'Masculino', NULL, NULL, NULL, NULL),
(449, 'Iwana Akame', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(450, 'Iwashi Tatami', '2 de Janeiro', 'Humano', NULL, 'Masculino', 'O', '012021', NULL, NULL),
(451, 'Iwazo', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(452, 'Iyashi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(453, 'Izumi Uchiha', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, '11', NULL),
(454, 'Izumo Kamizuki', '25 de Novembro', 'Humano', NULL, 'Masculino', 'A', '012049', NULL, NULL),
(455, 'Izuna Uchiha', '10 de Fevereiro', 'Humano', 'Morto', 'Masculino', 'O', NULL, NULL, NULL),
(456, 'J', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(457, 'Jūgo', '1 de Outubro', 'Humano', NULL, 'Masculino', 'AB', NULL, NULL, NULL),
(458, 'Jōseki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(459, 'Jūzō Biwa', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(460, 'JJ', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(461, 'Jakō Ryūdōin', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(462, 'Jako', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(463, 'Jantō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(464, 'Jibachi', NULL, 'Humano', 'Presumidamente Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(465, 'Jiga', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(466, 'Jigen', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(467, 'Jigokudō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(468, 'Jigumo', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(469, 'Jimei', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(470, 'Jin', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(471, 'Jin Kaminari', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(472, 'Jinin Akebino', '25 de Setembro', 'Humano', NULL, 'Masculino', 'O', NULL, NULL, NULL),
(473, 'Jinpachi Munashi', '4 de Julho', 'Humano', 'Morto', 'Masculino', 'AB', NULL, NULL, NULL),
(474, 'Jirō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(475, 'Jirōbō', '26 de Junho', 'Humano', 'Morto', 'Masculino', 'B', NULL, NULL, NULL),
(476, 'Jirōchō Wasabi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(477, 'Jiraiya', '11 de novembro', 'Humano', 'Morto', 'Masculino', 'B', '002301', '6', NULL),
(478, 'Jiryū Sendō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(479, 'Junsai', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(480, 'K', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(481, 'Kabure Tokisuki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(482, 'Kabuto Yakushi', '29 de fevereiro', 'Humano', NULL, 'Masculino', 'AB', '012140', '10', NULL),
(483, 'Kaede', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(484, 'Kaede Yoshino', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(485, 'Kagami Uchiha', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(486, 'Kagari', '16 de novembro', 'Humano', 'Vivo', 'Masculino', 'O', 'R1-126', NULL, NULL),
(487, 'Kage (Anbu)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(488, 'Kagebōshi', NULL, 'Humano', 'Incapacitado', 'Masculino', NULL, NULL, NULL, NULL),
(489, 'Kageki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(490, 'Kagen Uchiha', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(491, 'Kagerō', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(492, 'Kagura (game)', NULL, 'Humano', 'Falecido', 'Feminino', NULL, NULL, NULL, NULL),
(493, 'Kagura Karatachi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(494, 'Kaguya Ōtsutsuki', NULL, 'Humano', 'Incapacitada', 'Feminino', NULL, NULL, NULL, NULL),
(495, 'Kahiko', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(496, 'Kahyō', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(497, 'Kaiza', '21 de Agosto', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(498, 'Kajūra', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(499, 'Kaji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(500, 'Kajika', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(501, 'Kakō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(502, 'Kakashi Hatake', '15 de setembro', 'Humano', NULL, 'Masculino', 'O', '009720', '5', '6'),
(503, 'Kakeru Tsuki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(504, 'Kakkō', '5 de Julho', 'Humano', 'Morto', 'Masculino', 'B', 'IW-06219', NULL, NULL),
(505, 'Kakoi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(506, 'Kakuzu', '15 de Agosto', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(507, 'Kamata', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(508, 'Kamatari', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(509, 'Kamikiri', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(510, 'Kamira', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(511, 'Kanabun', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(512, 'Kandachi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(513, 'Kaneki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(514, 'Kankurō', '15 de maio', 'Humano', NULL, 'Masculino', 'B', '54-002', '12', '16'),
(515, 'Kanna', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(516, 'Kanna (Carpinteiro)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(517, 'Kanoe', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(518, 'Kanoto', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(519, 'Kanpō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(520, 'Kanpu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(521, 'Kaori', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(522, 'Kara', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(523, 'Karai', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(524, 'Karashi', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(525, 'Karenbana', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(526, 'Karin', '20 de Junho', 'Humano', NULL, 'Feminino', 'AB', NULL, NULL, NULL),
(527, 'Karui', '14 de fevereiro', 'Humano', NULL, 'Feminino', 'A', 'CL6306', NULL, NULL),
(528, 'Karura', '11 de Novembro', 'Humano', 'Morta', 'Feminino', 'B', NULL, NULL, NULL),
(529, 'Karyū', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(530, 'Kashike', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(531, 'Kasuga Nara', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(532, 'Kasumi', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(533, 'Katasuke Tōno', '3 de marco', 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(534, 'Katazu', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(535, 'Katsura', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(536, 'Katsuyu', '9 de Maio', 'Humano', NULL, 'Hermafrodita', NULL, NULL, NULL, NULL),
(537, 'Kawaki', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(538, 'Kawarama Senju', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(539, 'Kaya', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(540, 'Kayo', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(541, 'Kayui', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(542, 'Kazabune', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(543, 'Kazami', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(544, 'Kazan', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(545, 'Kazuma', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(546, 'Kedama', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(547, 'Kegon', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(548, 'Keiri', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(549, 'Kiba Inuzuka', '7 de Julho', 'Humano', NULL, 'Masculino', 'B', NULL, '12', '14'),
(550, 'Kiba Inuzuka (Mundo Genjutsu)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(551, 'Kidōmaru', '16 de Dezembro', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(552, 'Kido Tsumiki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(553, 'Kie', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(554, 'Kigiri', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(555, 'Kihō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(556, 'Kiji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(557, 'Kiki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(558, 'Kiku', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(559, 'Kikunojō', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(560, 'Killer B', '15 de Maio', 'Humano', 'Vivo', 'Masculino', 'B', 'CL3288', NULL, NULL),
(561, 'Kimimaro', '15 de Junho', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(562, 'Kin (ator)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(563, 'Kin Tsuchi', '6 de Julho', 'Humano', 'Morta', 'Feminino', 'O', NULL, NULL, NULL),
(564, 'Kina Kodon', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(565, 'King', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(566, 'Kinkaku', '7 de Marco', 'Humano', 'Morto', 'Masculino', 'A', NULL, NULL, NULL),
(567, 'Kinoto', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(568, 'Kinshiki Ōtsutsuki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(569, 'Kintoki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(570, 'Kirara', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(571, 'Kiri', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(572, 'Kiri (Monte Verde)', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(573, 'Kirisame', NULL, 'Humano', 'Incapacitado', 'Masculino', NULL, NULL, NULL, NULL),
(574, 'Kiruru', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(575, 'Kisame Hoshigaki', '18 de Marco', 'Humano', 'Morto', 'Masculino', 'AB', '012625', '10 Anos', NULL),
(576, 'Kisuke Maboroshi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(577, 'Kitō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(578, 'Kitane', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(579, 'Kitsuchi', '22 de Marco', 'Humano', NULL, 'Masculino', 'O', 'IW-06112', NULL, NULL),
(580, 'Kiyoi Yotsuki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(581, 'Kiyomu Fukuda', NULL, 'Humano', NULL, NULL, 'A', NULL, NULL, NULL),
(582, 'Kiyoyasu Kagetsu', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(583, 'Kizashi Haruno', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(584, 'Kogane', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(585, 'Kohada', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(586, 'Kohari Umino', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(587, 'Koharu Utatane', '1 de Setembro', 'Humano', 'Viva', 'Feminino', 'A', '000256', NULL, NULL),
(588, 'Koji Kashin', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(589, 'Kokage Yanagikage', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(590, 'Kokuō', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(591, 'Kokuri', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(592, 'Kokuyō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(593, 'Kokuyō (marionetista)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(594, 'Komachi', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(595, 'Komame', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(596, 'Komaza', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(597, 'Shuradō', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(598, 'Kū', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(599, 'Kō (Anbu)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(600, 'Kō Hyūga', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(601, 'Kōji (Suna)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(602, 'Kōji (estudante)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(603, 'Kōmei', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(604, 'Kōsuke (Cientista)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(605, 'Kōta', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(606, 'Kōtarō Fūma', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(607, 'Kōza Kubisaki', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(608, 'Komejūcha', NULL, 'Humano', 'Desconhecido', NULL, NULL, NULL, NULL, NULL),
(609, 'Komichi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(610, 'Komugi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(611, 'Komushi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(612, 'Konan', '20 de Fevereiro', 'Humano', 'Morta', 'Feminino', 'O', NULL, NULL, NULL),
(613, 'Kongō', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(614, 'Konohamaru Sarutobi', '30 de Dezembro', 'Humano', NULL, 'Masculino', 'B', '012707', '12', NULL),
(615, 'Kontsuchi', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(616, 'Korega', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(617, 'Korobi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(618, 'Koshō', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(619, 'Kōsuke', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(620, 'Kosuke Maruboshi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(621, 'Kotetsu Hagane', '21 de Julho', 'Humano', NULL, 'Masculino', 'B', '012050', NULL, NULL),
(622, 'Kotohime', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL);
