INSERT INTO "Ninja" ("id", "name", "birthdate", "specie", "status", "sex", "bloodType", "ninjaRegistration", "academyGradAge", "chuninPromAge") VALUES
(1, E'A (Primeiro Raikage)', E'1 de Dezembro', E'Humano', E'Morto', E'Masculino', E'O', NULL, NULL, NULL),
(2, E'A (Quarto Raikage)', E'1 de Junho', E'Humano', NULL, E'Masculino', E'A', E'CL2211', NULL, NULL),
(3, E'A (Segundo Raikage)', E'1 de Marco', E'Humano', NULL, E'Masculino', E'O', NULL, NULL, NULL),
(4, E'A (Terceiro Raikage)', E'01 de agosto', E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(5, E'Abelha Gigante', NULL, E'Humano', E'Morta', NULL, NULL, NULL, NULL, NULL),
(6, E'Abiru', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(7, E'Agara', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(8, E'Agari', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(9, E'Agari Kaisen', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(10, E'Ageha', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(11, E'Agira Ryūdōin', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(12, E'Ahiko', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(13, E'Aino', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(14, E'Ajisai', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(15, E'Akaboshi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(16, E'Akahoshi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(17, E'Akamaru', E'7 de Julho', E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(18, E'Akane', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(19, E'Akane (kunoichi)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(20, E'Akari Tatsushiro', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(21, E'Akatsuchi', E'11 de Janeiro', E'Humano', NULL, E'Masculino', E'B', E'IW-08718', NULL, NULL),
(22, E'Akemaru', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(23, E'Akino', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(24, E'Akio', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(25, E'Akita Inuzuka', E'20 de Abril', E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(26, E'Akkun', NULL, E'Humano', E'Morto', E'Hermafrodita', NULL, NULL, NULL, NULL),
(27, E'Amachi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(28, E'Amado', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(29, E'Amagi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, E'13'),
(30, E'Amai', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(31, E'Amaru', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(32, E'Amayo', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(33, E'Ame', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(34, E'Ameno', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(35, E'Ameyuki', NULL, E'Humano', E'Falecida', E'Feminino', NULL, NULL, NULL, NULL),
(36, E'Ameyuri Ringo', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(37, E'Ami', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(38, E'Amino', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(39, E'Ancião Hyūga', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(40, E'Aniki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(41, E'Animais', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(42, E'Anko Mitarashi', E'24 de Outubro', E'Humano', NULL, E'Feminino', E'A', E'011226', E'10', E'12'),
(43, E'Ao', E'01 de Agosto', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(44, E'Aoba Yamashiro', E'03 de Setembro', E'Humano', NULL, E'Masculino', E'O', E'009744', NULL, NULL),
(45, E'Aoda', E'1 de Outubro', E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(46, E'Aoi Rokushō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(47, E'Apicultor', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(48, E'Arai', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(49, E'Arashi Fūma', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(50, E'Araya', E'13 de Marco', E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(51, E'Armadiko', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(52, E'Asami', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(53, E'Ashimaru', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(54, E'Ashina', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(55, E'Ashina Uzumaki', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(56, E'Ashitaba', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(57, E'Ashura Ōtsutsuki', E'8 de Junho', E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(58, E'Assistente do Escultor de Pedra', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(59, E'Astrônoma de Konoha', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(60, E'Asuma Sarutobi', E'18 de Outubro', E'Humano', E'Morto', E'Masculino', E'O', E'010829', E'9', E'12'),
(61, E'Atsui', E'2 de Agosto', E'Humano', NULL, E'Masculino', E'O', E'CL6265', NULL, NULL),
(62, E'Avó de Obito', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(63, E'Ayame', E'14 de Fevereiro', E'Humano', NULL, E'Feminino', E'O', NULL, NULL, NULL),
(64, E'Ayato', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(65, E'Azami', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(66, E'Baiu', E'30 de Maio', E'Humano', E'Morto', E'Masculino', E'A', E'R2-039', NULL, NULL),
(67, E'Baji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(68, E'Baki', E'4 de Julho', E'Humano', NULL, E'Masculino', E'A', E'38-212', E'8', E'12'),
(69, E'Baku', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(70, E'Baku (Anbu)', NULL, E'Humano', E'Morto Presumivelmente', E'Masculino', NULL, NULL, NULL, NULL),
(71, E'Bakuto', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(72, E'Bandō', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(73, E'Banna', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(74, E'Bansai', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(75, E'Baraki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(76, E'Baru Uchiha', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(77, E'Bekkō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(78, E'Benga', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(79, E'Benten', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(80, E'Besta Espiritual', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(81, E'Besta Guardiã de Três Cabeças', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(82, E'Bisuke', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(83, E'Biwako Sarutobi', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(84, E'Blue B', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(85, E'Boro', NULL, E'Humano', E'Presumivelmente morto', E'Masculino', NULL, NULL, NULL, NULL),
(86, E'Boruto Uzumaki', E'27 de Marco', E'Humano', NULL, E'Masculino', NULL, NULL, E'11', NULL),
(87, E'Bull', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(88, E'Buna', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(89, E'Bunpuku', E'9 de Fevereiro', E'Humano', E'Morto', E'Masculino', E'O', NULL, NULL, NULL),
(90, E'Buntan Kurosuki', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(91, E'Bunzō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(92, E'Burami', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(93, E'Butsuma Senju', E'16 de Janeiro', E'Humano', E'Morto', E'Masculino', E'AB', NULL, NULL, NULL),
(94, E'Byakuren', E'20 de Janeiro', E'Humano', E'Morto', E'Masculino', E'B', NULL, NULL, NULL),
(95, E'C', E'3 de Abril', E'Humano', NULL, E'Masculino', E'A', E'CL5517', NULL, NULL),
(96, E'Camaleão Gigante', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(97, E'Caminho Humano', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(98, E'Cangurus Boxeadores', NULL, E'Humano', E'Vivos', E'Feminino', NULL, NULL, NULL, NULL),
(99, E'Capitão Assassino de Suna', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(100, E'Capitão do Navio Fantasma', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(101, E'Caranguejo Cadáver Gigante', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(102, E'Centopeia Gigante', NULL, E'Humano', E'Morta', NULL, NULL, NULL, NULL, NULL),
(103, E'Chōbee Akimichi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(104, E'Chōchō Akimichi', E'8 de Agosto', E'Humano', NULL, E'Feminino', NULL, NULL, E'11', NULL),
(105, E'Chōhan', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(106, E'Chōjūrō', E'1 de Novembro', E'Humano', NULL, E'Masculino', E'B', NULL, NULL, NULL),
(107, E'Chūji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(108, E'Chōji Akimichi', E'1 de Maio', E'Humano', E'Vivo', E'Masculino', E'B', E'012625', E'12', E'14'),
(109, E'Chūkaku', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(110, E'Chūkichi', E'2 de Julho', E'Humano', E'Morto', E'Masculino', E'AB', NULL, NULL, NULL),
(111, E'Chōmei', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(112, E'Chōseki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(113, E'Chūshin', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(114, E'Chōza Akimichi', E'22 de Abril', E'Humano', NULL, E'Masculino', E'B', E'005490', NULL, NULL),
(115, E'Chamū', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(116, E'Chamaru', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(117, E'Chefe Hippo', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(118, E'Chefe da Vila Tonika', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(119, E'Chefe de Aldeia (personagem)', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(120, E'Chefe de Tsuchigumo', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(121, E'Chen', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(122, E'Chen (estudante)', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(123, E'Chibi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(124, E'Chichiatsu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(125, E'Chikara', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(126, E'Chino', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(127, E'Chiriku', E'1 de Julho', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(128, E'Chishima', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(129, E'Chiyo', E'15 de Outubro', E'Humano', E'Morta', E'Feminino', E'B', E'01-002', NULL, NULL),
(130, E'Chiyo (princesa)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(131, E'Chiyomatsu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(132, E'Choco', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(133, E'Clone do Nove-Caudas', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(134, E'Clã Sendō', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(135, E'Code', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(136, E'Comandante da Anbu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(137, E'Companheiro de Kakuzu', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(138, E'Condor', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(139, E'Corvo de Itachi', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(140, E'Criatura Espiã com Sharingan', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(141, E'Crustáceo Gigante', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(142, E'Cães de Ni', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(143, E'Cão de Guarda', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(144, E'Dōshin', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(145, E'Dōshu Goetsu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(146, E'Dōtō Akimichi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(147, E'Daen Nara', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(148, E'Daibutsu', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(149, E'Daichi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(150, E'Daikoku Funeno', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(151, E'Daimaru', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(152, E'Daimyō Desconhecido', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(153, E'Daimyō do Isto', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(154, E'Daimyō do País da Geada', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(155, E'Daimyō do País da Terra', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(156, E'Daimyō do País da Água', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(157, E'Daimyō do País das Fontes Termais', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(158, E'Daimyō do País do Chá', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(159, E'Daimyō do País do Fogo', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(160, E'Daimyō do País do Relâmpago', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(161, E'Daimyō do Vento (Parte I)', E'5 de Novembro', E'Humano', NULL, E'Masculino', E'B', NULL, NULL, NULL),
(162, E'Daimyō do Vento (Parte II)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(163, E'Dajimu', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(164, E'Dan Katō', E'4 de Dezembro', E'Humano', E'Morto', E'Masculino', E'A', E'002973', NULL, NULL),
(165, E'Dangō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(166, E'Dango Mitsuki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(167, E'Danzō Shimura', E'6 de Janeiro', E'Humano', NULL, E'Masculino', E'AB', E'000272', NULL, NULL),
(168, E'Dançarina dos Ventos', NULL, E'Humano', NULL, E'Feminino', E'O', NULL, NULL, NULL),
(169, E'Darui', E'6 de Janeiro', E'Humano', NULL, E'Masculino', E'O', E'CL5596', NULL, NULL),
(170, E'Datsuji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(171, E'Deepa', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(172, E'Deidara', E'5 de Maio', E'Humano', NULL, E'Masculino', E'AB', E'IW-08721', NULL, NULL),
(173, E'Delta', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(174, E'Dengaku', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(175, E'Denka', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(176, E'Denki Kaminarimon', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(177, E'Dez-Caudas', NULL, E'Humano', E'Incapacitado', NULL, NULL, NULL, NULL, NULL),
(178, E'Dez-Caudas de Isshiki', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(179, E'Disonasu', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(180, E'Dodai', E'23 de Outubro', E'Humano', E'Vivo', E'Masculino', E'O', E'CL1532', NULL, NULL),
(181, E'Dokan', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(182, E'Doki', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(183, E'Dokku', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(184, E'Don', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(185, E'Doragu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(186, E'Dosu Kinuta', E'12 de Junho', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(187, E'Dotō Kazahana', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(188, E'Doutor de Iwa', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(189, E'Ebisu', E'8 de Marco', E'Humano', E'Vivo', E'Masculino', E'A', E'010777', NULL, NULL),
(190, E'Ebizō', E'6 de Janeiro', E'Humano', NULL, E'Masculino', E'B', E'02-002', NULL, NULL),
(191, E'Ehō Norimaki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(192, E'Emi', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(193, E'Emiru', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(194, E'En', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(195, E'En Oyashiro', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(196, E'En no Gyōja', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(197, E'Enchū Nara', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(198, E'Enko Onikuma', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(199, E'Enra', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(200, E'Ensui Nara', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(201, E'Enzo Tenrō', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(202, E'Ereki Kaminarimon', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(203, E'Escultor de Pedra', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(204, E'Espadachim', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(205, E'Esposa de Kisuke', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(206, E'Estátua Demoníaca do Caminho Exterior', NULL, E'Humano', E'Incapacitado', NULL, NULL, NULL, NULL, NULL),
(207, E'Estátua do Clã Ōtsutsuki', NULL, E'Humano', E'Presumivelmente Falecido', NULL, NULL, NULL, NULL, NULL),
(208, E'Etoro Konjiki', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(209, E'F', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(210, E'Fū', E'8 de Agosto', E'Humano', E'Morta', E'Feminino', E'B', NULL, NULL, NULL),
(211, E'Fū Yamanaka', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(212, E'Fūjin', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(213, E'Fūka', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(214, E'Fūshin', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(215, E'Fūta Kagetsu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(216, E'Faz', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(217, E'Feiticeiro', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(218, E'Filha de Sāra', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(219, E'Filho de Gennō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(220, E'Forças Aliadas Shinobi', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(221, E'Fubuki Kakuyoku', NULL, E'Humano', E'Falecida', E'Feminino', NULL, NULL, NULL, NULL),
(222, E'Fudō', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(223, E'Fuen', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(224, E'Fugai', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(225, E'Fugaku Uchiha', E'16 de Agosto', E'Humano', E'Morto', E'Masculino', E'AB', E'004086', NULL, NULL),
(226, E'Fugi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(227, E'Fuguki Suikazan', E'22 de Fevereiro', E'Humano', E'Morto', E'Masculino', E'O', NULL, NULL, NULL),
(228, E'Fukasaku', E'9 de Maio', E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(229, E'Fuki', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(230, E'Fuki (País do Som)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(231, E'Fuku', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(232, E'Fukuemon', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(233, E'Fukurokumaru', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(234, E'Fukusuke Hikyakuya', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(235, E'Fukuyokana', NULL, E'Humano', E'Presumivelmente Morto', E'Masculino', NULL, NULL, NULL, NULL),
(236, E'Funari', NULL, E'Humano', E'Morto Presumido', E'Masculino', NULL, NULL, NULL, NULL),
(237, E'Furofuki', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(238, E'Furui', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(239, E'Fusō', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(240, E'Futaba', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(241, E'Futami', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(242, E'Futsu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(243, E'Fuyō', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(244, E'Gōza', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(245, E'Gaara', E'19 de Janeiro', E'Humano', NULL, E'Masculino', E'AB', E'56-001', E'12', E'14'),
(246, E'Gakidō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(247, E'Gaku Inuzuka', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(248, E'Gama', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(249, E'Gamabunta', E'3 de Janeiro', E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(250, E'Gamaden', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(251, E'Gamagorō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(252, E'Gamahiro', E'9 de Julho', E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(253, E'Gamaken', E'11 de Outubro', E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(254, E'Gamakichi', E'1 de Abril', E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(255, E'Gamamaru', E'8 de Marco', E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(256, E'Gamariki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(257, E'Gamatama', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(258, E'Gamatatsu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(259, E'Gameru', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(260, E'Gandō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(261, E'Gangue Byakuya', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(262, E'Ganryū', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(263, E'Gantetsu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(264, E'Gantetsu (Iwagakure)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(265, E'Garō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(266, E'Garaga', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(267, E'Gari', E'8 de Agosto', E'Humano', E'Morto', E'Masculino', E'AB', NULL, NULL, NULL),
(268, E'Garra das Águas', NULL, E'Humano', NULL, E'Feminino', E'A', NULL, NULL, NULL),
(269, E'Garuda', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(270, E'Garyō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(271, E'Gatō', E'30 de Abril', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(272, E'Gatai', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(273, E'Gataro', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(274, E'Gatsu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(275, E'Gazeru', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(276, E'Gekkō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(277, E'Gekomatsu', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(278, E'Genyūmaru', E'27 de Julho', E'Humano', E'Morto', E'Masculino', E'B', NULL, NULL, NULL),
(279, E'Genba', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(280, E'Genbu', NULL, E'Humano', E'Viva', NULL, NULL, NULL, NULL, NULL),
(281, E'Genbu (ministro)', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(282, E'Gengetsu Hōzuki', E'26 de Outubro', E'Humano', NULL, E'Masculino', E'AB', NULL, NULL, NULL),
(283, E'Gengo', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(284, E'Genji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(285, E'Genma Shiranui', E'17 de Julho', E'Humano', NULL, E'Masculino', E'A', E'010203', E'10', E'13'),
(286, E'Genmai', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(287, E'Gennō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(288, E'Gennai', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(289, E'Genshō Ryūdōin', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(290, E'Gensui Amagiri', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(291, E'Genzō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(292, E'Gerotora', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(293, E'Gigante Marlin', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(294, E'Giichi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(295, E'Ginji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(296, E'Ginkaku', E'9 de Abril', E'Humano', E'Morto', E'Masculino', E'AB', NULL, NULL, NULL),
(297, E'Gitai', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(298, E'Gojō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(299, E'Goji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(300, E'Golem de Prisão de Terra', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(301, E'Gonbee', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(302, E'Gongorō Kamakura', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(303, E'Goshiki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(304, E'Gosunkugi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(305, E'Gotta', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(306, E'Gōzu', E'6 de Junho', E'Humano', NULL, E'Masculino', E'B', NULL, E'12', E'18'),
(307, E'Gozu (Raiz)', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(308, E'Grupo Prajñā', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(309, E'Grupo do Trovão Negro', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(310, E'Guarda-costas de Tenzen', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(311, E'Guardião de Kinshiki', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(312, E'Guardião do Portão', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(313, E'Guerreiro Amaldiçoado', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(314, E'Guren', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(315, E'Guren (prisioneiro)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(316, E'Guruko', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(317, E'Gyūki', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(318, E'Gyokurō Chabashira', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(319, E'Gênio', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(320, E'Hōichi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(321, E'Hōki (Takigakure)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(322, E'Hōki (Takumi)', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(323, E'Hōki (Watari)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(324, E'Hōki Taketori', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(325, E'Hōsei', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(326, E'Hōshō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(327, E'Hāto', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(328, E'Hachidai', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(329, E'Hagoromo Ōtsutsuki', E'6 de Agosto', E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(330, E'Haguruma', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(331, E'Haido', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(332, E'Haie', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(333, E'Hajiki', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(334, E'Hajiri', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(335, E'Hakkaku', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(336, E'Hako Kuroi', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(337, E'Haku', E'9 de Janeiro', E'Humano', E'Morto', E'Masculino', E'O', NULL, NULL, NULL),
(338, E'Hakuhyō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(339, E'Hakui', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(340, E'Hakui (Médico)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(341, E'Hakuja Sennin', E'6 de Abril', E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(342, E'Hakuto', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(343, E'Hamaki Mimura', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(344, E'Hamura Ōtsutsuki', E'6 de Agosto', E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(345, E'Han', E'10 de Maio', E'Humano', E'Morto', E'Masculino', E'B', NULL, NULL, NULL),
(346, E'Hana Inuzuka', E'13 de Abril', E'Humano', NULL, E'Feminino', E'O', E'012368', NULL, NULL),
(347, E'Hanabi Hyūga', E'27 de Marco', E'Humano', NULL, E'Feminino', E'A', NULL, NULL, NULL),
(348, E'Hanare', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(349, E'Hanuma', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(350, E'Hanzō', E'12 de Fevereiro', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(351, E'Hanzaki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(352, E'Haori', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(353, E'Harine', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(354, E'Haruna', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(355, E'Harusame', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(356, E'Hashirama Senju', E'23 de Outubro', E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(357, E'Hassaku Onomichi', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(358, E'Hayama Shirakumo', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(359, E'Hayase', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(360, E'Hayate Gekkō', E'2 de Novembro', E'Humano', E'Morto', E'Masculino', E'AB', E'011671', E'12', E'13'),
(361, E'Hazuki Uchiha', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(362, E'Hebiichigo', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(363, E'Heiji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(364, E'Heki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(365, E'Hiashi Hyūga', E'8 de Janeiro', E'Humano', NULL, E'Masculino', E'B', E'05159', NULL, NULL),
(366, E'Hibachi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(367, E'Hibari', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(368, E'Hidan', E'2 de Abril', E'Humano', E'Desconhecido', E'Masculino', E'B', NULL, NULL, NULL),
(369, E'Hidari', NULL, E'Humano', E'Provavelmente Morto', E'Masculino', NULL, NULL, NULL, NULL),
(370, E'Hidero', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(371, E'Hikaku Uchiha', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(372, E'Hikaru', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(373, E'Hikaru Tsuki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(374, E'Himatsu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(375, E'Himawari Uzumaki', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(376, E'Himeno', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(377, E'Himuka Suzukaze', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(378, E'Himushi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(379, E'Hina', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(380, E'Hinata Hyūga', E'27 de Dezembro', E'Humano', NULL, E'Feminino', E'A', E'012612', E'12 Anos', E'14 anos'),
(381, E'Hinata Hyūga (Mundo Genjutsu)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(382, E'Hino', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(383, E'Hinoe', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(384, E'Hinoko', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(385, E'Hinoto', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(386, E'Hiruko (nukenin)', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(387, E'Hiruzen Sarutobi', E'8 de Fevereiro', E'Humano', E'Morto', E'Masculino', E'A', E'000261', NULL, NULL),
(388, E'Hisame', NULL, E'Humano', E'Incapacitada', E'Feminino', NULL, NULL, NULL, NULL),
(389, E'Hishaku', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(390, E'Hitode', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(391, E'Hizashi Hyūga', E'8 de Janeiro', E'Humano', E'Morto', E'Masculino', E'B', E'005160', NULL, NULL),
(392, E'Hizashi Hyūga (Livro de Jiraiya)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(393, E'Hoheto Hyūga', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(394, E'Hohozuki', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(395, E'Hokushin', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(396, E'Hokuto', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(397, E'Homura Mitokado', E'8 de Maio', E'Humano', E'Vivo', E'Masculino', E'A', E'000293', NULL, NULL),
(398, E'Honoka', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(399, E'Hotaru (estudante)', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(400, E'Hotaru Katsuragi', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(401, E'Hotarubi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(402, E'Hyō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(403, E'Iō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(404, E'Iō (Ninja Médico)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(405, E'Iō (Vila dos Bambus)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(406, E'Ibara', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(407, E'Ibiki Morino', E'20 de Marco', E'Humano', E'Vivo', E'Masculino', E'A', E'010913', E'10 anos', E'15 anos'),
(408, E'Ibuse', NULL, E'Humano', E'Morto Provavelmente', NULL, NULL, NULL, NULL, NULL),
(409, E'Ibushi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(410, E'Ichi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(411, E'Ichigen', NULL, E'Humano', E'Morto Presumivelmente', E'Masculino', NULL, NULL, NULL, NULL),
(412, E'Ichikishimahime', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(413, E'Ichirōta Oniyuzu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(414, E'Idate Morino', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(415, E'Iggy', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(416, E'Ikanago', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(417, E'Ikkaku Umino', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(418, E'Ikkyū Madoka', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(419, E'Inabi Uchiha', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(420, E'Inaho', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(421, E'Inari', E'25 de Dezembro', E'Humano', NULL, E'Masculino', E'A', NULL, NULL, NULL),
(422, E'Indra Ōtsutsuki', E'4 de Janeiro', E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(423, E'Ino Yamanaka', E'23 de Setembro', E'Humano', NULL, E'Feminino', E'B', E'012604', E'12 anos', E'14 anos'),
(424, E'Ino Yamanaka (Mundo Genjutsu)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(425, E'Inoichi Yamanaka', E'24 de Janeiro', E'Humano', E'Morto', E'Masculino', E'AB', E'005492', NULL, NULL),
(426, E'Inojin Yamanaka', E'5 de dezembro', E'Humano', NULL, E'Masculino', NULL, NULL, E'11', NULL),
(427, E'Inomatsu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(428, E'Inseto Gigante', NULL, E'Humano', E'Vivo', NULL, NULL, NULL, NULL, NULL),
(429, E'Iori', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(430, E'Iroha Hyūga', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(431, E'Iruka Umino', E'26 de Maio', E'Humano', NULL, E'Masculino', E'O', E'011850', E'11 anos', E'16 anos'),
(432, E'Isago', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(433, E'Isago (Filha de Gojō)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(434, E'Isaribi', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(435, E'Ise', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(436, E'Ishidate', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(437, E'Ishikawa', E'6 de Maio', E'Humano', E'Morto', E'Masculino', E'O', NULL, NULL, NULL),
(438, E'Isobu', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(439, E'Isono', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(440, E'Isshiki Ōtsutsuki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(441, E'Itachi Uchiha', E'09 de Junho', E'Humano', E'Morto', E'Masculino', E'AB', E'012110', E'7 anos', E'10 anos'),
(442, E'Itama Senju', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(443, E'Ittan', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(444, E'Ittetsu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(445, E'Iwabee Yuino', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(446, E'Iwaji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(447, E'Iwakyō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(448, E'Iwana', NULL, E'Humano', E'Presumivelmente Morto', E'Masculino', NULL, NULL, NULL, NULL),
(449, E'Iwana Akame', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(450, E'Iwashi Tatami', E'2 de Janeiro', E'Humano', NULL, E'Masculino', E'O', E'012021', NULL, NULL),
(451, E'Iwazo', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(452, E'Iyashi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(453, E'Izumi Uchiha', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, E'11', NULL),
(454, E'Izumo Kamizuki', E'25 de Novembro', E'Humano', NULL, E'Masculino', E'A', E'012049', NULL, NULL),
(455, E'Izuna Uchiha', E'10 de Fevereiro', E'Humano', E'Morto', E'Masculino', E'O', NULL, NULL, NULL),
(456, E'J', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(457, E'Jūgo', E'1 de Outubro', E'Humano', NULL, E'Masculino', E'AB', NULL, NULL, NULL),
(458, E'Jōseki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(459, E'Jūzō Biwa', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(460, E'JJ', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(461, E'Jakō Ryūdōin', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(462, E'Jako', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(463, E'Jantō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(464, E'Jibachi', NULL, E'Humano', E'Presumidamente Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(465, E'Jiga', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(466, E'Jigen', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(467, E'Jigokudō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(468, E'Jigumo', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(469, E'Jimei', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(470, E'Jin', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(471, E'Jin Kaminari', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(472, E'Jinin Akebino', E'25 de Setembro', E'Humano', NULL, E'Masculino', E'O', NULL, NULL, NULL),
(473, E'Jinpachi Munashi', E'4 de Julho', E'Humano', E'Morto', E'Masculino', E'AB', NULL, NULL, NULL),
(474, E'Jirō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(475, E'Jirōbō', E'26 de Junho', E'Humano', E'Morto', E'Masculino', E'B', NULL, NULL, NULL),
(476, E'Jirōchō Wasabi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(477, E'Jiraiya', E'11 de novembro', E'Humano', E'Morto', E'Masculino', E'B', E'002301', E'6', NULL),
(478, E'Jiryū Sendō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(479, E'Junsai', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(480, E'K', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(481, E'Kabure Tokisuki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(482, E'Kabuto Yakushi', E'29 de fevereiro', E'Humano', NULL, E'Masculino', E'AB', E'012140', E'10', NULL),
(483, E'Kaede', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(484, E'Kaede Yoshino', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(485, E'Kagami Uchiha', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(486, E'Kagari', E'16 de novembro', E'Humano', E'Vivo', E'Masculino', E'O', E'R1-126', NULL, NULL),
(487, E'Kage (Anbu)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(488, E'Kagebōshi', NULL, E'Humano', E'Incapacitado', E'Masculino', NULL, NULL, NULL, NULL),
(489, E'Kageki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(490, E'Kagen Uchiha', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(491, E'Kagerō', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(492, E'Kagura (game)', NULL, E'Humano', E'Falecido', E'Feminino', NULL, NULL, NULL, NULL),
(493, E'Kagura Karatachi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(494, E'Kaguya Ōtsutsuki', NULL, E'Humano', E'Incapacitada', E'Feminino', NULL, NULL, NULL, NULL),
(495, E'Kahiko', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(496, E'Kahyō', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(497, E'Kaiza', E'21 de Agosto', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(498, E'Kajūra', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(499, E'Kaji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(500, E'Kajika', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(501, E'Kakō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(502, E'Kakashi Hatake', E'15 de setembro', E'Humano', NULL, E'Masculino', E'O', E'009720', E'5', E'6'),
(503, E'Kakeru Tsuki', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(504, E'Kakkō', E'5 de Julho', E'Humano', E'Morto', E'Masculino', E'B', E'IW-06219', NULL, NULL),
(505, E'Kakoi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(506, E'Kakuzu', E'15 de Agosto', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(507, E'Kamata', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(508, E'Kamatari', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(509, E'Kamikiri', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(510, E'Kamira', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(511, E'Kanabun', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(512, E'Kandachi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(513, E'Kaneki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(514, E'Kankurō', E'15 de maio', E'Humano', NULL, E'Masculino', E'B', E'54-002', E'12', E'16'),
(515, E'Kanna', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(516, E'Kanna (Carpinteiro)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(517, E'Kanoe', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(518, E'Kanoto', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(519, E'Kanpō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(520, E'Kanpu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(521, E'Kaori', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(522, E'Kara', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(523, E'Karai', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(524, E'Karashi', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(525, E'Karenbana', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(526, E'Karin', E'20 de Junho', E'Humano', NULL, E'Feminino', E'AB', NULL, NULL, NULL),
(527, E'Karui', E'14 de fevereiro', E'Humano', NULL, E'Feminino', E'A', E'CL6306', NULL, NULL),
(528, E'Karura', E'11 de Novembro', E'Humano', E'Morta', E'Feminino', E'B', NULL, NULL, NULL),
(529, E'Karyū', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(530, E'Kashike', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(531, E'Kasuga Nara', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(532, E'Kasumi', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(533, E'Katasuke Tōno', E'3 de marco', E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(534, E'Katazu', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(535, E'Katsura', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(536, E'Katsuyu', E'9 de Maio', E'Humano', NULL, E'Hermafrodita', NULL, NULL, NULL, NULL),
(537, E'Kawaki', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(538, E'Kawarama Senju', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(539, E'Kaya', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(540, E'Kayo', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(541, E'Kayui', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(542, E'Kazabune', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(543, E'Kazami', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(544, E'Kazan', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(545, E'Kazuma', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(546, E'Kedama', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(547, E'Kegon', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(548, E'Keiri', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(549, E'Kiba Inuzuka', E'7 de Julho', E'Humano', NULL, E'Masculino', E'B', NULL, E'12', E'14'),
(550, E'Kiba Inuzuka (Mundo Genjutsu)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(551, E'Kidōmaru', E'16 de Dezembro', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(552, E'Kido Tsumiki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(553, E'Kie', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(554, E'Kigiri', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(555, E'Kihō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(556, E'Kiji', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(557, E'Kiki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(558, E'Kiku', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(559, E'Kikunojō', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(560, E'Killer B', E'15 de Maio', E'Humano', E'Vivo', E'Masculino', E'B', E'CL3288', NULL, NULL),
(561, E'Kimimaro', E'15 de Junho', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(562, E'Kin (ator)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(563, E'Kin Tsuchi', E'6 de Julho', E'Humano', E'Morta', E'Feminino', E'O', NULL, NULL, NULL),
(564, E'Kina Kodon', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(565, E'King', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(566, E'Kinkaku', E'7 de Marco', E'Humano', E'Morto', E'Masculino', E'A', NULL, NULL, NULL),
(567, E'Kinoto', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(568, E'Kinshiki Ōtsutsuki', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(569, E'Kintoki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(570, E'Kirara', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(571, E'Kiri', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(572, E'Kiri (Monte Verde)', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(573, E'Kirisame', NULL, E'Humano', E'Incapacitado', E'Masculino', NULL, NULL, NULL, NULL),
(574, E'Kiruru', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(575, E'Kisame Hoshigaki', E'18 de Marco', E'Humano', E'Morto', E'Masculino', E'AB', E'012625', E'10 Anos', NULL),
(576, E'Kisuke Maboroshi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(577, E'Kitō', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(578, E'Kitane', NULL, E'Humano', E'Morto', NULL, NULL, NULL, NULL, NULL),
(579, E'Kitsuchi', E'22 de Marco', E'Humano', NULL, E'Masculino', E'O', E'IW-06112', NULL, NULL),
(580, E'Kiyoi Yotsuki', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(581, E'Kiyomu Fukuda', NULL, E'Humano', NULL, NULL, E'A', NULL, NULL, NULL),
(582, E'Kiyoyasu Kagetsu', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(583, E'Kizashi Haruno', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(584, E'Kogane', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(585, E'Kohada', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(586, E'Kohari Umino', NULL, E'Humano', E'Morta', E'Feminino', NULL, NULL, NULL, NULL),
(587, E'Koharu Utatane', E'1 de Setembro', E'Humano', E'Viva', E'Feminino', E'A', E'000256', NULL, NULL),
(588, E'Koji Kashin', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(589, E'Kokage Yanagikage', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(590, E'Kokuō', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(591, E'Kokuri', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(592, E'Kokuyō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(593, E'Kokuyō (marionetista)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(594, E'Komachi', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL),
(595, E'Komame', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(596, E'Komaza', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(597, E'Shuradō', NULL, E'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(598, E'Kū', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(599, E'Kō (Anbu)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(600, E'Kō Hyūga', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(601, E'Kōji (Suna)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(602, E'Kōji (estudante)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(603, E'Kōmei', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(604, E'Kōsuke (Cientista)', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(605, E'Kōta', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(606, E'Kōtarō Fūma', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(607, E'Kōza Kubisaki', NULL, E'Humano', E'Falecido', E'Masculino', NULL, NULL, NULL, NULL),
(608, E'Komejūcha', NULL, E'Humano', E'Desconhecido', NULL, NULL, NULL, NULL, NULL),
(609, E'Komichi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(610, E'Komugi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(611, E'Komushi', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(612, E'Konan', E'20 de Fevereiro', E'Humano', E'Morta', E'Feminino', E'O', NULL, NULL, NULL),
(613, E'Kongō', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(614, E'Konohamaru Sarutobi', E'30 de Dezembro', E'Humano', NULL, E'Masculino', E'B', E'012707', E'12', NULL),
(615, E'Kontsuchi', NULL, E'Humano', E'Vivo', E'Masculino', NULL, NULL, NULL, NULL),
(616, E'Korega', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(617, E'Korobi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(618, E'Koshō', NULL, E'Humano', E'Viva', E'Feminino', NULL, NULL, NULL, NULL),
(619, E'Kōsuke', NULL, E'Humano', E'Morto', E'Masculino', NULL, NULL, NULL, NULL),
(620, E'Kosuke Maruboshi', NULL, E'Humano', NULL, E'Masculino', NULL, NULL, NULL, NULL),
(621, E'Kotetsu Hagane', E'21 de Julho', E'Humano', NULL, E'Masculino', E'B', E'012050', NULL, NULL),
(622, E'Kotohime', NULL, E'Humano', NULL, E'Feminino', NULL, NULL, NULL, NULL);
