INSERT INTO `affiliation` (`id`, `name`) VALUES
(1, 'Kumogakure'),
(2, 'Forcas Aliadas Shinobi'),
(3, 'Cla Kamizuru'),
(4, 'Sunagakure'),
(5, 'Pais das Ondas'),
(6, 'Pais dos Ancestrais'),
(7, 'Amegakure'),
(8, 'Hoshigakure'),
(9, 'Konohagakure'),
(10, 'Iwagakure'),
(11, 'Pais das Florestas'),
(12, 'Pais do Mar'),
(13, 'Otogakure'),
(14, 'Kara'),
(15, 'Pais do Fogo'),
(16, 'Kirigakure'),
(17, 'Vila dos Bambus'),
(18, 'Moyagakure'),
(19, 'Caverna Ryuchi'),
(20, 'Sora-ku'),
(21, 'Pais do Relâmpago'),
(22, 'Yugakure'),
(23, 'Uzushiogakure'),
(24, 'Ilha Benisu'),
(25, 'Pais da Água'),
(26, 'Templo do Fogo'),
(27, 'Kusagakure'),
(28, 'Castelo Hozuki'),
(29, 'Yumegakure'),
(30, 'Pais do Cha'),
(31, 'Takigakure'),
(32, 'Vila Tonika'),
(33, 'Vila Tsuchigumo'),
(34, 'Pais dos Pântanos'),
(35, 'Pais do Macarrao'),
(36, 'Pais das Fontes Termais'),
(37, 'Pais dos Passaros'),
(38, 'Pais do Isto'),
(39, 'Pais do Ferro'),
(40, 'Akatsuki'),
(41, 'Pais da Geada'),
(42, 'Pais da Terra'),
(43, 'Pais do Vento'),
(44, 'Raiz'),
(45, 'Fortaleza de Gato'),
(46, 'Vila Hacho'),
(47, 'Yukigakure'),
(48, 'Lua'),
(49, 'Ishigakure'),
(50, 'Roran'),
(51, 'Vila do Mormaco'),
(52, 'Continente de Temujin'),
(53, 'Monte Myoboku'),
(54, 'Pais do Som'),
(55, 'Pais da Pedra'),
(56, 'Empresa Gato'),
(57, 'Pais da Neve'),
(58, 'Pais do Ka'),
(59, 'Pais do Silêncio'),
(60, 'Vila Inaho'),
(61, 'Vila Kagero'),
(62, 'Pais dos Demônios'),
(63, 'Vale das Nuvens e Relâmpago'),
(64, 'Pais dos Rios'),
(65, 'Vila Jomae'),
(66, 'Orfanato de Konoha'),
(67, 'Pais dos Vegetais'),
(68, 'Pais da Lua'),
(69, 'Monte Shumisen'),
(70, 'Vila Takumi'),
(71, 'Monte Verde'),
(72, 'Vila do Uivo do Lobo'),
(73, 'Vila da Árvore Caida'),
(74, 'Floresta Shikkotsu'),
(75, 'Pais do Mel'),
(76, 'Dimensao otsutsuki'),
(77, 'Castelo Kazahana'),
(78, 'Pais da Madeira'),
(79, 'Pais do Pescoco'),
(80, 'Vila Nadeshiko'),
(81, 'Pais dos Vales'),
(82, 'Vila de Shuku'),
(83, 'Pais do Céu'),
(84, 'Tsukigakure'),
(85, 'Corporacao Makibi'),
(86, 'Vila Daidai'),
(87, 'Cla Nara'),
(88, 'Enka Ninja'),
(89, 'Loja do Curry da Vida'),
(90, 'Cla Uzumaki'),
(91, 'Pais do Isso'),
(92, 'Caverna Oculta por Água'),
(93, 'Vila da Árvore Genjutsu'),
(94, 'Companhia Himeyuri'),
(95, 'Vila Oculta da Lua');
