INSERT INTO `Classification` (`id`, `name`) VALUES
(1, 'Kage'),
(2, 'Invocacao'),
(3, 'Ninken'),
(4, 'Iryo-nin'),
(5, 'Ninja Médico'),
(6, 'Tipo Sensor'),
(7, 'Oinin'),
(8, 'Nukenin'),
(9, 'Monge Ninja'),
(10, 'Ninja Médica'),
(11, 'Jinchuriki'),
(12, 'Pseudo-Jinchuriki'),
(13, 'Chefe de Aldeia'),
(14, 'Daimyo'),
(15, 'Samurai'),
(16, 'Besta com Cauda'),
(17, 'Rank S'),
(18, 'Ninja Mercenario'),
(19, 'Criminoso'),
(20, 'Sabio'),
(21, 'Sensor'),
(22, 'Sennin'),
(23, 'Ninja Cozinheiro'),
(24, 'Ninjas Mercenarios'),
(25, 'Jonin'),
(26, 'Ninja Mercenaria'),
(27, 'Kekkei Genkai, Ninjutsu, Dojutsu'),
(28, 'Biju'),
(29, 'Marionete'),
(30, 'Bandido'),
(31, 'Ninja Chefe'),
(32, 'Sannin'),
(33, 'Técnica de Invocacao'),
(34, 'Desaparecido'),
(35, 'Nukenin Anterior'),
(36, 'Rei do Pais da Lua'),
(37, 'Ministro do Pais da Lua'),
(38, 'Lorde'),
(39, 'Ninja Monge'),
(40, 'Tokubetsu Jonin'),
(41, 'Sênior'),
(42, 'Subordinado de Sasori');
