INSERT INTO `classification_jutsu` (`id`, `name`) VALUES
(1, 'Kekkei Genkai'),
(2, 'Senjutsu'),
(3, 'Ninjutsu'),
(4, 'Taijutsu'),
(5, 'Bukijutsu'),
(6, 'Fuinjutsu'),
(7, 'Hiden'),
(8, 'Kekkei Mora'),
(9, 'Genjutsu'),
(10, 'Juinjutsu'),
(11, 'Habilidade Geral'),
(12, 'Nintaijutsu'),
(13, 'Kenjutsu'),
(14, 'Konbijutsu'),
(15, 'Kyuinjutsu'),
(16, 'Ninjutsu Espaco-Tempo'),
(17, 'Shurikenjutsu'),
(18, 'Ninjutsu Médico'),
(19, 'Saiseijutsu'),
(20, 'Kinjutsu'),
(21, 'Armadilha'),
(22, 'Bunshinjutsu'),
(23, 'Fluxo de Chakra'),
(24, 'Dojutsu'),
(25, 'Pseudo-Kekkei Tota'),
(26, 'Formação'),
(27, 'Yugojutsu'),
(28, 'Konbijutu'),
(29, 'Iryo Ninjutsu'),
(30, 'Estilo de Luta'),
(31, 'Kekkaijutsu'),
(32, 'Kusarigamajutsu'),
(33, 'Tessenjutsu'),
(34, 'Kayakujutsu'),
(35, 'Acao Suicida'),
(36, 'Bojutsu'),
(37, 'Rank S'),
(38, 'Tipo Sensor'),
(39, 'Juinjutsu‏‎'),
(40, 'Kinkojutsu'),
(41, 'Tonjutsu'),
(42, 'Kekkei Tota'),
(43, 'Ninjutsu de Medicina Negra'),
(44, 'Kyūinjutsu'),
(45, 'Ninjutsu de Reencarnacao'),
(46, 'Kyujutsu'),
(47, 'Ofensivo'),
(48, 'Fukuwajutsu'),
(49, 'Ninjutsu Espaço-Tempo'),
(50, 'Fórmula de Selamento');
