INSERT INTO `Ninja` (`id`, `name`, `birthdate`, `specie`, `status`, `sex`, `bloodType`, `ninjaRegistration`, `academyGradAge`, `chuninPromAge`) VALUES
(1245, 'Tsurushi Hachiya', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1246, 'Tsuyu', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1247, 'Tsuzumi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1248, 'Tsuzumi Sarugaku', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1249, 'Uō', NULL, 'Humano', 'Incapacitado', 'Masculino', NULL, NULL, NULL, NULL),
(1250, 'Ubau', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1251, 'Udon Ise', '3 de Abril', 'Humano', NULL, 'Masculino', 'O', NULL, '12', NULL),
(1252, 'Ugai', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1253, 'Ugatsu', NULL, 'Humano', 'Presumivelmente Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1254, 'Umibōzu', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1255, 'Unagi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1256, 'Unidade Tempestuosa', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1257, 'Unkai Kurama', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1258, 'Unmo Samidare', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1259, 'Urakaku', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1260, 'Urashiki Ōtsutsuki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1261, 'Uroko Kurama', NULL, 'Humano', 'Morta', 'Feminino', NULL, NULL, NULL, NULL),
(1262, 'Uruchi Uchiha', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1263, 'Urushi', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1264, 'Urushi (invocação)', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1265, 'Ushi', NULL, 'Humano', 'Morto Presumivelmente', 'Masculino', NULL, NULL, NULL, NULL),
(1266, 'Utakata', NULL, 'Humano', 'Morto', 'Masculino', 'B', NULL, NULL, NULL),
(1267, 'Victor', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1268, 'Vinte Pelotões', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1269, 'Waraji', '6 de Abril', 'Humano', NULL, 'Masculino', 'O', NULL, NULL, NULL),
(1270, 'Wasabi Izuno', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1271, 'Watase', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1272, 'Yūdachi', NULL, 'Humano', 'Morto Presumido', 'Masculino', NULL, NULL, NULL, NULL),
(1273, 'Yūgao Uzuki', '3 de Novembro', 'Humano', NULL, 'Feminino', 'A', '012161', NULL, NULL),
(1274, 'Yōji Aburame', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1275, 'Yūki Minazuki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1276, 'Yūkimaru', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1277, 'Yōrō', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1278, 'Yūra', '31 de Outubro', 'Humano', 'Morto', 'Masculino', 'AB', '44-005', NULL, NULL),
(1279, 'Yūsuke', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1280, 'Yūto', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1281, 'Ya', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1282, 'Yagura', '3 de abril', 'Humano', 'Morto', 'Masculino', 'AB', NULL, NULL, NULL),
(1283, 'Yagura (anime)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1284, 'Yahiko', '20 de fevereiro', 'Humano', 'Morto', 'Masculino', 'O', NULL, NULL, NULL),
(1285, 'Yajirobee', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1286, 'Yakku', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1287, 'Yakumi Uchiha', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1288, 'Yakumo Kurama', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1289, 'Yamame', NULL, 'Humano', 'Presume Morto', 'Feminino', NULL, NULL, NULL, NULL),
(1290, 'Yamaoka', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1291, 'Yamato', '10 de agosto', 'Humano', NULL, 'Masculino', 'A', '010992', '6', '6'),
(1292, 'Yaoki', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1293, 'Yashamaru', '23 de Maio', 'Humano', 'Morto', 'Masculino', 'AB', '32-049', '11', '16'),
(1294, 'Yashiro Uchiha', NULL, 'Humano', 'Falecido', 'Masculino', NULL, NULL, NULL, NULL),
(1295, 'Yatogo Ryūgen', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1296, 'Yodo', '1 de dezembro', 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(1297, 'Yokaze', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1298, 'Yokozuna', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1299, 'Yome', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1300, 'Yomi', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1301, 'Yomito Hirasaka', NULL, 'Humano', 'Vivo', 'Masculino', NULL, NULL, NULL, NULL),
(1302, 'Yone', NULL, 'Humano', 'Viva', 'Feminino', NULL, NULL, NULL, NULL),
(1303, 'Yoroi Akadō', '21 de fevereiro', 'Humano', NULL, 'Masculino', 'O', '011930', NULL, NULL),
(1304, 'Yoshi', NULL, 'Humano', 'Provavelmente Morto', NULL, NULL, NULL, NULL, NULL),
(1305, 'Yoshino Nara', '24 de fevereiro', 'Humano', NULL, 'Feminino', 'A', '009091', NULL, NULL),
(1306, 'Yoshiteru', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1307, 'Yota Otenki', NULL, 'Humano', 'Morto', 'Masculino', NULL, NULL, NULL, NULL),
(1308, 'Yotaka', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1309, 'Yugito Nii', '24 de Julho', 'Humano', 'Morta', 'Feminino', 'A', 'CL5322', NULL, NULL),
(1310, 'Yui', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1311, 'Yuina Itomaki', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1312, 'Yukai', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1313, 'Yukata', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1314, 'Yukigakure', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1315, 'Yukimi', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1316, 'Yurika', NULL, 'Humano', NULL, 'Feminino', NULL, NULL, NULL, NULL),
(1317, 'Yurinojō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1318, 'Yurito', NULL, 'Humano', 'Incapacitado', 'Masculino', NULL, NULL, NULL, NULL),
(1319, 'Yurui', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1320, 'Yurui (anime)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1321, 'Zō', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1322, 'Zōri', '1 de Dezembro', 'Humano', NULL, 'Masculino', 'A', NULL, NULL, NULL),
(1323, 'Zōsui', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1324, 'Zabuza Momochi', '15 de Agosto', 'Humano', 'Morto', 'Masculino', 'A', NULL, '9', NULL),
(1325, 'Zaji', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1326, 'Zaji (jogador)', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1327, 'Zaku Abumi', '14 de setembro', 'Humano', 'Morto', 'Masculino', 'AB', NULL, NULL, NULL),
(1328, 'Zangei', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1329, 'Zenza', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1330, 'Zero-Caudas', NULL, 'Humano', NULL, 'Hermafrodita', NULL, NULL, NULL, NULL),
(1331, 'Zetsu', NULL, 'Humano', 'Morto', 'Masculino', 'B', NULL, NULL, NULL),
(1332, 'Zetsu Branco', NULL, 'Humano', 'Morto', 'Masculino', 'B', NULL, NULL, NULL),
(1333, 'Zetsu Branco Monstruoso', NULL, 'Humano', 'Morto', NULL, NULL, NULL, NULL, NULL),
(1334, 'Zetsu Negro', NULL, 'Humano', NULL, 'Masculino', NULL, NULL, NULL, NULL),
(1335, 'Águia Gigante', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL),
(1336, 'Árvore Divina', NULL, 'Humano', NULL, NULL, NULL, NULL, NULL, NULL);
